#!/bin/bash

KBD_SRC=$CACHE/kbd
KBD_RPM_NAME=KBD
KBD_VERSION="2.7.1"
KBD_FULLNAME=$KBD_RPM_NAME-$KBD_VERSION
$ROOT/download_and_untar.sh "https://web.git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/snapshot/kbd-2.7.1.tar.gz" "$KBD_SRC"
cd $KBD_SRC
./autogen.sh

if [ ! -d $KBD_SRC/build ]
then
  mkdir -p $KBD_SRC/build
  cd $KBD_SRC/build
  ../configure --prefix=/usr --build=$(../config/config.guess) --host=$TARGET --enable-optional-progs
  make -j$(nproc)
fi
cd $KBD_SRC/build
#make DESTDIR=$ISO_SYSROOT install

$ROOT/generate_tar.sh make $KBD_SRC/build/$KBD_FULLNAME.tar $KBD_FULLNAME \
                      usr/bin/{setkeycodes,vlock,spawn_console,setleds,getunimap,resizecons,spawn_login,setlogcons,psfgettable,setmetamode,outpsfheader,showkey,fgconsole,psfxtable,psfaddtable,dumpkeys,openvt,setvesablank,mapscrn,unicode_stop,loadunimap,unicode_start,setvtrgb,deallocvt,chvt,loadkeys,setpalette,setfont,kbdrate,clrunimap,psfstriptable,showconsolefont,screendump,kbd_mode,kbdinfo,getkeycodes} \
                      usr/etc/pam.d/vlock \
                      usr/share/consolefonts/{iso08.16.gz,lat9-16.psf.gz,iso04.16.gz,aply16.psf.gz,Lat2-Terminus16.psfu.gz,iso05.16.gz,lat5-16.psfu.gz,README.lat7,lat9-12.psf.gz,ruscii_8x16.psfu.gz,Mik_8x16.gz,gr737b-8x11.psfu.gz,cp857.14.gz,lat4-19.psfu.gz,lat4-16+.psfu.gz,altc-8x16.gz,alt-8x8.gz,lat0-14.psfu.gz,lat2-sun16.psfu.gz,eurlatgr.psfu.gz,972.cp.gz,partialfonts/8859-1.a0-ff.08.gz,partialfonts/8859-8.a0-ff.14.gz,partialfonts/8859-9.a0-ff.16.gz,partialfonts/8859-5.a0-ff.16.gz,partialfonts/8859-5.a0-ff.08.gz,partialfonts/8859-4.a0-ff.08.gz,partialfonts/8859-10.a0-ff.16.gz,partialfonts/8859-4.a0-ff.16.gz,partialfonts/8859-9.a0-ff.08.gz,partialfonts/8859-7.a0-ff.14.gz,partialfonts/ascii.20-7f.16.gz,partialfonts/8859-10.a0-ff.14.gz,partialfonts/8859-8.a0-ff.08.gz,partialfonts/none.00-17.08.gz,partialfonts/8859-6.a0-ff.08.gz,partialfonts/8859-7.a0-ff.16.gz,partialfonts/none.00-17.14.gz,partialfonts/8859-3.a0-ff.14.gz,partialfonts/none.00-17.16.gz,partialfonts/8859-6.a0-ff.14.gz,partialfonts/cp437.00-1f.14.gz,partialfonts/ascii.20-7f.14.gz,partialfonts/8859-8.a0-ff.16.gz,partialfonts/8859-6.a0-ff.16.gz,partialfonts/8859-9.a0-ff.14.gz,partialfonts/8859-4.a0-ff.14.gz,partialfonts/8859-7.a0-ff.08.gz,partialfonts/8859-2.a0-ff.14.gz,partialfonts/8859-3.a0-ff.16.gz,partialfonts/8859-10.a0-ff.08.gz,partialfonts/8859-3.a0-ff.08.gz,partialfonts/8859-1.a0-ff.14.gz,partialfonts/8859-2.a0-ff.16.gz,partialfonts/cp437.00-1f.16.gz,partialfonts/ascii.20-7f.08.gz,partialfonts/8859-2.a0-ff.08.gz,partialfonts/8859-1.a0-ff.16.gz,partialfonts/cp437.00-1f.08.gz,partialfonts/8859-5.a0-ff.14.gz,928.cp.gz,iso05.14.gz,iso08.14.gz,iso02.08.gz,latarcyrheb-sun16.psfu.gz,gr928a-8x16.psfu.gz,UniCyrExt_8x16.psf.gz,koi8u_8x14.psfu.gz,README.psfu,lat2a-16.psfu.gz,koi8c-8x16.gz,UniCyr_8x8.psf.gz,gr928-8x16-thin.psfu.gz,lat9v-08.psfu.gz,iso09.14.gz,iso08.08.gz,iso02.14.gz,737.cp.gz,lat0-16.psfu.gz,arm8.fnt.gz,default8x16.psfu.gz,lat9-14.psf.gz,lat5-14.psfu.gz,README.Ethiopic,README.Lat2-Terminus16,lat0-10.psfu.gz,iso01.16.gz,lat9w-16.psfu.gz,README.cybercafe,lat4-14.psfu.gz,LatArCyrHeb-08.psfu.gz,lat1-10.psfu.gz,gr928b-8x14.psfu.gz,README.Arabic,README.lat0,Cyr_a8x8.psfu.gz,koi8r.8x8.psfu.gz,lat7a-14.psfu.gz,lat0-sun16.psfu.gz,lat4-10.psfu.gz,cp866-8x16.psf.gz,gr737d-8x16.psfu.gz,lat9w-14.psfu.gz,lat4-16.psfu.gz,161.cp.gz,alt-8x14.gz,README.eurlatgr,default8x9.psfu.gz,gr737c-8x16.psfu.gz,lat0-08.psfu.gz,README.LatGrkCyr,cyr-sun16.psfu.gz,iso01-12x22.psfu.gz,t850b.fnt.gz,lat4a-19.psfu.gz,lat9v-14.psfu.gz,LatKaCyrHeb-14.psfu.gz,iso07.16.gz,lat1-16.psfu.gz,lat7-14.psfu.gz,LatGrkCyr-8x16.psfu.gz,koi8-14.psf.gz,README.12x22,lat4a-14.psfu.gz,gr737c-8x14.psfu.gz,drdos8x16.psfu.gz,iso09.16.gz,lat2-16.psfu.gz,cp850-8x16.psfu.gz,drdos8x6.psfu.gz,lat2-10.psfu.gz,UniCyr_8x14.psf.gz,iso05.08.gz,ERRORS,iso07.14.gz,iso06.16.gz,iso04.08.gz,lat4a-16+.psfu.gz,iso04.14.gz,lat4-12.psfu.gz,iso10.14.gz,README.lat9,lat9v-10.psfu.gz,gr737c-8x8.psfu.gz,LatArCyrHeb-16+.psfu.gz,lat9u-12.psfu.gz,lat2-12.psfu.gz,lat4a-16.psfu.gz,iso02.16.gz,Cyr_a8x16.psfu.gz,lat9u-08.psfu.gz,cp850-8x8.psfu.gz,163.cp.gz,lat4a-10.psfu.gz,gr737b-9x16-medieval.psfu.gz,README.Cyrillic,iso01.14.gz,tcvn8x16.psf.gz,lat0-12.psfu.gz,iso03.16.gz,cp865-8x16.psfu.gz,lat9u-14.psfu.gz,koi8u_8x8.psfu.gz,Goha-12.psfu.gz,lat9u-10.psfu.gz,UniCyr_8x16.psf.gz,lat1-08.psfu.gz,solar24x32.psfu.gz,LatGrkCyr-12x22.psfu.gz,lat4a-12.psfu.gz,lat9u-16.psfu.gz,lat4a-08.psfu.gz,lat4-08.psfu.gz,cp857.08.gz,LatArCyrHeb-16.psfu.gz,README.drdos,lat2-08.psfu.gz,greek-polytonic.psfu.gz,iso10.08.gz,README.eurlatgr.mappings,cp866-8x8.psf.gz,gr737c-8x7.psfu.gz,README.Sun,165.cp.gz,gr737a-8x8.psfu.gz,cp865-8x14.psfu.gz,pancyrillic.f16.psfu.gz,lat1-12.psfu.gz,iso03.08.gz,koi8r-8x14.gz,iso10.16.gz,iso06.14.gz,iso09.08.gz,164.cp.gz,lat2-14.psfu.gz,koi8u_8x16.psfu.gz,gr737c-8x6.psfu.gz,drdos8x14.psfu.gz,gr928a-8x14.psfu.gz,lat7a-16.psf.gz,162.cp.gz,gr928-9x16.psfu.gz,alt-8x16.gz,latarcyrheb-sun32.psfu.gz,iso06.08.gz,lat9-08.psf.gz,lat1-14.psfu.gz,lat9v-12.psfu.gz,GohaClassic-12.psfu.gz,lat5-12.psfu.gz,lat9w-10.psfu.gz,Goha-16.psfu.gz,koi8r-8x16.gz,drdos8x8.psfu.gz,cp850-8x14.psfu.gz,lat9v-16.psfu.gz,LatArCyrHeb-19.psfu.gz,README.Greek,gr928b-8x16.psfu.gz,ruscii_8x8.psfu.gz,LatArCyrHeb-14.psfu.gz,880.cp.gz,cybercafe.fnt.gz,cp865-8x8.psfu.gz,Goha-14.psfu.gz,iso02-12x22.psfu.gz,README.cp1250,cp866-8x14.psf.gz,gr737a-9x16.psfu.gz,lat9w-12.psfu.gz,t.fnt.gz,GohaClassic-14.psfu.gz,Cyr_a8x14.psfu.gz,gr928-9x14.psfu.gz,lat9w-08.psfu.gz,iso07u-16.psfu.gz,koi8r-8x8.gz,sun12x22.psfu.gz,iso03.14.gz,lat9-10.psf.gz,GohaClassic-16.psfu.gz,gr737a-9x14.psfu.gz,iso01.08.gz,README.Hebrew,viscii10-8x16.psfu.gz,cp1250.psfu.gz,cp857.16.gz} \
                      usr/share/consoletrans/{koi8u2ruscii,cp866_to_uni.trans,cp775_to_uni.trans,null,viscii1.0_to_viscii1.1.trans,cp874_to_uni.trans,iso02_to_cp1250.trans,cp850_to_iso01.trans,8859-13_to_uni.trans,trivial,koi8-r_to_uni.trans,8859-9_to_uni.trans,latin2u.trans,cp852_to_uni.trans,koi8-u_to_uni.trans,utflist,cp855_to_uni.trans,cp864_to_uni.trans,baltic.trans,cp869_to_uni.trans,koi2alt,space,8859-2_to_uni.trans,cp865_to_uni.trans,cp863_to_uni.trans,8859-3_to_uni.trans,cp437_to_iso01.trans,8859-7_to_uni.trans,viscii1.0_to_tcvn.trans,8859-8_to_uni.trans,8859-14_to_uni.trans,cp857_to_uni.trans,8859-10_to_uni.trans,8859-15_to_uni.trans,cp861_to_uni.trans,cp1250_to_uni.trans,cp850_to_uni.trans,cp860_to_uni.trans,8859-4_to_uni.trans,8859-5_to_uni.trans,vga2iso,8859-1_to_uni.trans,cp737_to_uni.trans,cp1251_to_uni.trans,cp853_to_uni.trans,cp437_to_uni.trans,zero,cp862_to_uni.trans,8859-6_to_uni.trans} \
                      usr/share/keymaps/{amiga/amiga-de.map.gz,amiga/amiga-us.map.gz,pine/en.map.gz,atari/atari-se.map.gz,atari/atari-us.map.gz,atari/atari-uk-falcon.map.gz,atari/atari-de.map.gz,include/compose.latin2,include/vim-compose.latin1,include/compose.latin1,include/compose.latin,include/compose.8859_8,include/compose.8859_7,include/compose.latin3,include/compose.latin4,ppc,sun/sun-pl.map.gz,sun/sunt4-fi-latin1.map.gz,sun/sunt5-es.map.gz,sun/sun-pl-altgraph.map.gz,sun/sunt4-no-latin1.map.gz,sun/sunt5-fi-latin1.map.gz,sun/sunt5-cz-us.map.gz,sun/sundvorak.map.gz,sun/sunt5-fr-latin1.map.gz,sun/sunt5-uk.map.gz,sun/sunt4-es.map.gz,sun/sunt5-ru.map.gz,sun/sunt5-de-latin1.map.gz,sun/sunt6-uk.map.gz,sun/sunt5-us-cz.map.gz,sun/sunkeymap.map.gz,mac/all/mac-pt-latin1.map.gz,mac/all/apple-internal-0x0253-sv-fn-reverse.map.gz,mac/all/mac-uk.map.gz,mac/all/mac-se.map.gz,mac/all/mac-es.map.gz,mac/all/mac-pl.map.gz,mac/all/mac-dvorak.map.gz,mac/all/mac-fr_CH-latin1.map.gz,mac/all/apple-a1243-sv-fn-reverse.map.gz,mac/all/mac-fr.map.gz,mac/all/mac-template.map.gz,mac/all/apple-a1048-sv.map.gz,mac/all/apple-a1243-sv.map.gz,mac/all/mac-de-latin1-nodeadkeys.map.gz,mac/all/mac-dk-latin1.map.gz,mac/all/mac-de_CH.map.gz,mac/all/mac-us.map.gz,mac/all/mac-fi-latin1.map.gz,mac/all/mac-no-latin1.map.gz,mac/all/mac-fr-legacy.map.gz,mac/all/mac-it.map.gz,mac/all/mac-de-latin1.map.gz,mac/all/mac-be.map.gz,mac/all/apple-internal-0x0253-sv.map.gz,mac/include/mac-euro2.map.gz,mac/include/apple-a1048-base.inc,mac/include/mac-azerty-layout.inc,mac/include/mac-linux-keys-bare.inc,mac/include/mac-qwertz-layout.inc,mac/include/mac-qwerty-layout.inc,mac/include/apple-a1243-fn-reverse.inc,mac/include/mac-euro.map.gz,mac/include/apple-a1243-fn.inc,i386/carpalx/carpalx-full.map.gz,i386/carpalx/carpalx.map.gz,i386/bepo/fr-bepo-latin9.map.gz,i386/bepo/fr-bepo.map.gz,i386/qwerty/no-latin1.map.gz,i386/qwerty/ttwin_ctrl-UTF-8.map.gz,i386/qwerty/ruwin_ctrl-KOI8-R.map.gz,i386/qwerty/uk.map.gz,i386/qwerty/cz-lat2-prog.map.gz,i386/qwerty/nl.map.gz,i386/qwerty/emacs2.map.gz,i386/qwerty/fa.map.gz,i386/qwerty/se-lat6.map.gz,i386/qwerty/it-ibm.map.gz,i386/qwerty/es.map.gz,i386/qwerty/ttwin_ct_sh-UTF-8.map.gz,i386/qwerty/mk-utf.map.gz,i386/qwerty/bg-cp855.map.gz,i386/qwerty/br-latin1-us.map.gz,i386/qwerty/sr-cy.map.gz,i386/qwerty/ruwin_cplk-UTF-8.map.gz,i386/qwerty/cf.map.gz,i386/qwerty/gr-pc.map.gz,i386/qwerty/cz.map.gz,i386/qwerty/ua-ws.map.gz,i386/qwerty/cz-lat2.map.gz,i386/qwerty/us1.map.gz,i386/qwerty/by-cp1251.map.gz,i386/qwerty/it.map.gz,i386/qwerty/pl3.map.gz,i386/qwerty/dk-latin1.map.gz,i386/qwerty/ua-utf-ws.map.gz,i386/qwerty/ruwin_cplk-CP1251.map.gz,i386/qwerty/lv-tilde.map.gz,i386/qwerty/il-phonetic.map.gz,i386/qwerty/kyrgyz.map.gz,i386/qwerty/tj_alt-UTF8.map.gz,i386/qwerty/ruwin_cplk-KOI8-R.map.gz,i386/qwerty/by.map.gz,i386/qwerty/ru2.map.gz,i386/qwerty/ru3.map.gz,i386/qwerty/bg-cp1251.map.gz,i386/qwerty/ru-cp1251.map.gz,i386/qwerty/tr_q-latin5.map.gz,i386/qwerty/ro_std.map.gz,i386/qwerty/is-latin1-us.map.gz,i386/qwerty/ruwin_ct_sh-CP1251.map.gz,i386/qwerty/ruwin_ctrl-CP1251.map.gz,i386/qwerty/lt.l4.map.gz,i386/qwerty/ua-utf.map.gz,i386/qwerty/tralt.map.gz,i386/qwerty/trf.map.gz,i386/qwerty/mk0.map.gz,i386/qwerty/ru-yawerty.map.gz,i386/qwerty/defkeymap.map.gz,i386/qwerty/bashkir.map.gz,i386/qwerty/hypermap.m4,i386/qwerty/trq.map.gz,i386/qwerty/nl2.map.gz,i386/qwerty/bg_bds-cp1251.map.gz,i386/qwerty/kazakh.map.gz,i386/qwerty/mk.map.gz,i386/qwerty/pt-latin1.map.gz,i386/qwerty/ruwin_alt_sh-UTF-8.map.gz,i386/qwerty/pl2.map.gz,i386/qwerty/ruwin_ct_sh-KOI8-R.map.gz,i386/qwerty/ky_alt_sh-UTF-8.map.gz,i386/qwerty/is-latin1.map.gz,i386/qwerty/es-cp850.map.gz,i386/qwerty/pl4.map.gz,i386/qwerty/ru4.map.gz,i386/qwerty/ua.map.gz,i386/qwerty/hu101.map.gz,i386/qwerty/bg_pho-utf8.map.gz,i386/qwerty/ttwin_cplk-UTF-8.map.gz,i386/qwerty/bg_pho-cp1251.map.gz,i386/qwerty/us.map.gz,i386/qwerty/pt-latin9.map.gz,i386/qwerty/br-abnt2.map.gz,i386/qwerty/no.map.gz,i386/qwerty/defkeymap_V1.0.map.gz,i386/qwerty/br-latin1-abnt2.map.gz,i386/qwerty/ruwin_alt-UTF-8.map.gz,i386/qwerty/il.map.gz,i386/qwerty/ru1.map.gz,i386/qwerty/sv-latin1.map.gz,i386/qwerty/ruwin_ctrl-UTF-8.map.gz,i386/qwerty/fi.map.gz,i386/qwerty/cz-cp1250.map.gz,i386/qwerty/ruwin_alt-CP1251.map.gz,i386/qwerty/sk-qwerty.map.gz,i386/qwerty/ru-ms.map.gz,i386/qwerty/se-ir209.map.gz,i386/qwerty/dk.map.gz,i386/qwerty/br-abnt.map.gz,i386/qwerty/ua-cp1251.map.gz,i386/qwerty/et-nodeadkeys.map.gz,i386/qwerty/lt.map.gz,i386/qwerty/il-heb.map.gz,i386/qwerty/emacs.map.gz,i386/qwerty/gr.map.gz,i386/qwerty/ro.map.gz,i386/qwerty/et.map.gz,i386/qwerty/bywin-cp1251.map.gz,i386/qwerty/lv.map.gz,i386/qwerty/se-fi-lat6.map.gz,i386/qwerty/la-latin1.map.gz,i386/qwerty/ca.map.gz,i386/qwerty/ttwin_alt-UTF-8.map.gz,i386/qwerty/ro_win.map.gz,i386/qwerty/mk-cp1251.map.gz,i386/qwerty/pc110.map.gz,i386/qwerty/ru.map.gz,i386/qwerty/ie.map.gz,i386/qwerty/bg_bds-utf8.map.gz,i386/qwerty/ru_win.map.gz,i386/qwerty/se-fi-ir209.map.gz,i386/qwerty/pl1.map.gz,i386/qwerty/jp106.map.gz,i386/qwerty/lt.baltic.map.gz,i386/qwerty/sk-prog-qwerty.map.gz,i386/qwerty/ruwin_ct_sh-UTF-8.map.gz,i386/qwerty/it2.map.gz,i386/qwerty/ruwin_alt-KOI8-R.map.gz,i386/qwerty/no-latin1.doc,i386/qwerty/pl.map.gz,i386/qwerty/us-acentos.map.gz,i386/dvorak/dvorak-r.map.gz,i386/dvorak/dvorak-ca-fr.map.gz,i386/dvorak/dvorak-es.map.gz,i386/dvorak/ANSI-dvorak.map.gz,i386/dvorak/dvorak-fr.map.gz,i386/dvorak/dvorak.map.gz,i386/dvorak/dvorak-ru.map.gz,i386/dvorak/dvorak-ukp.map.gz,i386/dvorak/dvorak-programmer.map.gz,i386/dvorak/dvorak-sv-a1.map.gz,i386/dvorak/dvorak-l.map.gz,i386/dvorak/dvorak-de.map.gz,i386/dvorak/dvorak-uk.map.gz,i386/dvorak/dvorak-no.map.gz,i386/dvorak/dvorak-la.map.gz,i386/dvorak/dvorak-sv-a5.map.gz,i386/include/euro.map.gz,i386/include/backspace.map.gz,i386/include/linux-keys-extd.inc,i386/include/qwertz-layout.inc,i386/include/linux-with-alt-and-altgr.inc,i386/include/applkey.map.gz,i386/include/euro2.map.gz,i386/include/linux-with-two-alt-keys.inc,i386/include/linux-with-modeshift-altgr.inc,i386/include/azerty-layout.inc,i386/include/euro1.map.gz,i386/include/ctrl.map.gz,i386/include/keypad.map.gz,i386/include/compose.inc,i386/include/windowkeys.map.gz,i386/include/unicode.map.gz,i386/include/linux-keys-bare.inc,i386/include/euro1.inc,i386/include/qwerty-layout.inc,i386/colemak/mod-dh-ansi-us-fatz-wide.map.gz,i386/colemak/mod-dh-iso-us-wide.map.gz,i386/colemak/mod-dh-iso-us.map.gz,i386/colemak/en-latin9.map.gz,i386/colemak/mod-dh-iso-uk-wide.map.gz,i386/colemak/mod-dh-ansi-us-fatz.map.gz,i386/colemak/mod-dh-ansi-us-awing.map.gz,i386/colemak/mod-dh-matrix-us.map.gz,i386/colemak/mod-dh-ansi-us-wide.map.gz,i386/colemak/mod-dh-ansi-us.map.gz,i386/colemak/mod-dh-iso-uk.map.gz,i386/qwertz/de.map.gz,i386/qwertz/fr_CH.map.gz,i386/qwertz/cz.map.gz,i386/qwertz/sk-prog-qwertz.map.gz,i386/qwertz/slovene.map.gz,i386/qwertz/de-latin1-nodeadkeys.map.gz,i386/qwertz/fr_CH-latin1.map.gz,i386/qwertz/croat.map.gz,i386/qwertz/de_CH-latin1.map.gz,i386/qwertz/sg-latin1.map.gz,i386/qwertz/sg-latin1-lk450.map.gz,i386/qwertz/de_alt_UTF-8.map.gz,i386/qwertz/sr-latin.map.gz,i386/qwertz/sk-qwertz.map.gz,i386/qwertz/cz-us-qwertz.map.gz,i386/qwertz/sg.map.gz,i386/qwertz/de-latin1.map.gz,i386/qwertz/de-mobii.map.gz,i386/qwertz/hu.map.gz,i386/neo/koy.map.gz,i386/neo/bone.map.gz,i386/neo/adnw.map.gz,i386/neo/neoqwertz.map.gz,i386/neo/neo.map.gz,i386/neo/README.md,i386/neo/3l.map.gz,i386/fgGIod/tr_f-latin5.map.gz,i386/fgGIod/trf.map.gz,i386/olpc/es.map.gz,i386/olpc/pt.map.gz,i386/azerty/wangbe.map.gz,i386/azerty/wangbe2.map.gz,i386/azerty/be-latin1.map.gz,i386/azerty/fr-latin1.map.gz,i386/azerty/fr.map.gz,i386/azerty/fr-pc.map.gz,i386/azerty/fr-latin9.map.gz,i386/azerty/azerty.map.gz} \
                      usr/share/locale/{de/LC_MESSAGES/kbd.mo,pt_BR/LC_MESSAGES/kbd.mo,tr/LC_MESSAGES/kbd.mo,hu/LC_MESSAGES/kbd.mo,da/LC_MESSAGES/kbd.mo,sr/LC_MESSAGES/kbd.mo,ka/LC_MESSAGES/kbd.mo,pl/LC_MESSAGES/kbd.mo,cs/LC_MESSAGES/kbd.mo,sq/LC_MESSAGES/kbd.mo,it/LC_MESSAGES/kbd.mo,nl/LC_MESSAGES/kbd.mo,es/LC_MESSAGES/kbd.mo,el/LC_MESSAGES/kbd.mo,eo/LC_MESSAGES/kbd.mo,uk/LC_MESSAGES/kbd.mo,vi/LC_MESSAGES/kbd.mo,ru/LC_MESSAGES/kbd.mo,sv/LC_MESSAGES/kbd.mo,zh_CN/LC_MESSAGES/kbd.mo,id/LC_MESSAGES/kbd.mo,ro/LC_MESSAGES/kbd.mo,pt/LC_MESSAGES/kbd.mo} \
                      usr/share/unimaps/{cp866.uni,iso15.uni,README,lat9v.uni,8859-3.a0-ff.uni,8859-8.a0-ff.uni,ethiopic.uni,ruscii.uni,cp737c.uni,8859-1.a0-ff.uni,iso07u.uni,cp865a.uni,cp1250.uni,lat1.uni,lat2.uni,iso04.uni,viscii.uni,cp437.00-1f.uni,lat7.uni,cybercafe.uni,armscii8.uni,cp437.uni,koi8u.uni,iso05.uni,8859-6.a0-ff.uni,8859-7.a0-ff.uni,cp737a.uni,iso01.uni,8859-14.a0-ff.uni,tcvn.uni,cp866a.uni,cp850z.uni,cp865.uni,cp737.uni,ECMA144.uni,iso03.uni,def.uni,lat4u.uni,cp737b.uni,iso02.uni,8859-5.a0-ff.uni,8859-9.a0-ff.uni,lat9w.uni,8859-13.a0-ff.uni,iso08.uni,8859-2.a0-ff.uni,cyralt.uni,lat2u.uni,koi8r.uni,ascii.20-7f.uni,empty.uni,cp850a.uni,lat1u.uni,cp850.uni,lat9u.uni,iso06.uni,lat4.uni,iso10.uni,cp850b.uni,iso09.uni,8859-15.a0-ff.uni,iso07.uni,8859-4.a0-ff.uni,8859-10.a0-ff.uni}

$ROOT/generate_rpm.sh "$ISO_RPMS" \
                      "$KBD_SRC/build/rpmbuild" \
                      "$KBD_RPM_NAME" \
                      "$KBD_VERSION" \
                      "Linux Keyboard Tools" \
                      "This package contains tools for managing Linux console (Linux console, virtual terminals, keyboard, etc.) – mainly, what they do is loading console fonts and keyboard maps." \
                      "custom" \
                      "$KBD_SRC/build/$KBD_FULLNAME.tar" \
"usr/bin/setkeycodes" "%{_bindir}/setkeycodes" \
"usr/bin/vlock" "%{_bindir}/vlock" \
"usr/bin/spawn_console" "%{_bindir}/spawn_console" \
"usr/bin/setleds" "%{_bindir}/setleds" \
"usr/bin/getunimap" "%{_bindir}/getunimap" \
"usr/bin/resizecons" "%{_bindir}/resizecons" \
"usr/bin/spawn_login" "%{_bindir}/spawn_login" \
"usr/bin/setlogcons" "%{_bindir}/setlogcons" \
"usr/bin/psfgettable" "%{_bindir}/psfgettable" \
"usr/bin/setmetamode" "%{_bindir}/setmetamode" \
"usr/bin/outpsfheader" "%{_bindir}/outpsfheader" \
"usr/bin/showkey" "%{_bindir}/showkey" \
"usr/bin/fgconsole" "%{_bindir}/fgconsole" \
"usr/bin/psfxtable" "%{_bindir}/psfxtable" \
"usr/bin/psfaddtable" "%{_bindir}/psfaddtable" \
"usr/bin/dumpkeys" "%{_bindir}/dumpkeys" \
"usr/bin/openvt" "%{_bindir}/openvt" \
"usr/bin/setvesablank" "%{_bindir}/setvesablank" \
"usr/bin/mapscrn" "%{_bindir}/mapscrn" \
"usr/bin/unicode_stop" "%{_bindir}/unicode_stop" \
"usr/bin/loadunimap" "%{_bindir}/loadunimap" \
"usr/bin/unicode_start" "%{_bindir}/unicode_start" \
"usr/bin/setvtrgb" "%{_bindir}/setvtrgb" \
"usr/bin/deallocvt" "%{_bindir}/deallocvt" \
"usr/bin/chvt" "%{_bindir}/chvt" \
"usr/bin/loadkeys" "%{_bindir}/loadkeys" \
"usr/bin/setpalette" "%{_bindir}/setpalette" \
"usr/bin/setfont" "%{_bindir}/setfont" \
"usr/bin/kbdrate" "%{_bindir}/kbdrate" \
"usr/bin/clrunimap" "%{_bindir}/clrunimap" \
"usr/bin/psfstriptable" "%{_bindir}/psfstriptable" \
"usr/bin/showconsolefont" "%{_bindir}/showconsolefont" \
"usr/bin/screendump" "%{_bindir}/screendump" \
"usr/bin/kbd_mode" "%{_bindir}/kbd_mode" \
"usr/bin/kbdinfo" "%{_bindir}/kbdinfo" \
"usr/bin/getkeycodes" "%{_bindir}/getkeycodes" \
"usr/etc/pam.d/vlock" "%{_sysconfdir}/pam.d/vlock" \
"usr/share/consolefonts/iso08.16.gz" "%{_datadir}/consolefonts/iso08.16.gz" \
"usr/share/consolefonts/lat9-16.psf.gz" "%{_datadir}/consolefonts/lat9-16.psf.gz" \
"usr/share/consolefonts/iso04.16.gz" "%{_datadir}/consolefonts/iso04.16.gz" \
"usr/share/consolefonts/aply16.psf.gz" "%{_datadir}/consolefonts/aply16.psf.gz" \
"usr/share/consolefonts/Lat2-Terminus16.psfu.gz" "%{_datadir}/consolefonts/Lat2-Terminus16.psfu.gz" \
"usr/share/consolefonts/iso05.16.gz" "%{_datadir}/consolefonts/iso05.16.gz" \
"usr/share/consolefonts/lat5-16.psfu.gz" "%{_datadir}/consolefonts/lat5-16.psfu.gz" \
"usr/share/consolefonts/README.lat7" "%{_datadir}/consolefonts/README.lat7" \
"usr/share/consolefonts/lat9-12.psf.gz" "%{_datadir}/consolefonts/lat9-12.psf.gz" \
"usr/share/consolefonts/ruscii_8x16.psfu.gz" "%{_datadir}/consolefonts/ruscii_8x16.psfu.gz" \
"usr/share/consolefonts/Mik_8x16.gz" "%{_datadir}/consolefonts/Mik_8x16.gz" \
"usr/share/consolefonts/gr737b-8x11.psfu.gz" "%{_datadir}/consolefonts/gr737b-8x11.psfu.gz" \
"usr/share/consolefonts/cp857.14.gz" "%{_datadir}/consolefonts/cp857.14.gz" \
"usr/share/consolefonts/lat4-19.psfu.gz" "%{_datadir}/consolefonts/lat4-19.psfu.gz" \
"usr/share/consolefonts/lat4-16+.psfu.gz" "%{_datadir}/consolefonts/lat4-16+.psfu.gz" \
"usr/share/consolefonts/altc-8x16.gz" "%{_datadir}/consolefonts/altc-8x16.gz" \
"usr/share/consolefonts/alt-8x8.gz" "%{_datadir}/consolefonts/alt-8x8.gz" \
"usr/share/consolefonts/lat0-14.psfu.gz" "%{_datadir}/consolefonts/lat0-14.psfu.gz" \
"usr/share/consolefonts/lat2-sun16.psfu.gz" "%{_datadir}/consolefonts/lat2-sun16.psfu.gz" \
"usr/share/consolefonts/eurlatgr.psfu.gz" "%{_datadir}/consolefonts/eurlatgr.psfu.gz" \
"usr/share/consolefonts/972.cp.gz" "%{_datadir}/consolefonts/972.cp.gz" \
"usr/share/consolefonts/partialfonts/8859-1.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-1.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-8.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-8.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/8859-9.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-9.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-5.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-5.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-5.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-5.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-4.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-4.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-10.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-10.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-4.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-4.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-9.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-9.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-7.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-7.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/ascii.20-7f.16.gz" "%{_datadir}/consolefonts/partialfonts/ascii.20-7f.16.gz" \
"usr/share/consolefonts/partialfonts/8859-10.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-10.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/8859-8.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-8.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/none.00-17.08.gz" "%{_datadir}/consolefonts/partialfonts/none.00-17.08.gz" \
"usr/share/consolefonts/partialfonts/8859-6.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-6.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-7.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-7.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/none.00-17.14.gz" "%{_datadir}/consolefonts/partialfonts/none.00-17.14.gz" \
"usr/share/consolefonts/partialfonts/8859-3.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-3.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/none.00-17.16.gz" "%{_datadir}/consolefonts/partialfonts/none.00-17.16.gz" \
"usr/share/consolefonts/partialfonts/8859-6.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-6.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/cp437.00-1f.14.gz" "%{_datadir}/consolefonts/partialfonts/cp437.00-1f.14.gz" \
"usr/share/consolefonts/partialfonts/ascii.20-7f.14.gz" "%{_datadir}/consolefonts/partialfonts/ascii.20-7f.14.gz" \
"usr/share/consolefonts/partialfonts/8859-8.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-8.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-6.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-6.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-9.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-9.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/8859-4.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-4.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/8859-7.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-7.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-2.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-2.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/8859-3.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-3.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/8859-10.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-10.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-3.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-3.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-1.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-1.a0-ff.14.gz" \
"usr/share/consolefonts/partialfonts/8859-2.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-2.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/cp437.00-1f.16.gz" "%{_datadir}/consolefonts/partialfonts/cp437.00-1f.16.gz" \
"usr/share/consolefonts/partialfonts/ascii.20-7f.08.gz" "%{_datadir}/consolefonts/partialfonts/ascii.20-7f.08.gz" \
"usr/share/consolefonts/partialfonts/8859-2.a0-ff.08.gz" "%{_datadir}/consolefonts/partialfonts/8859-2.a0-ff.08.gz" \
"usr/share/consolefonts/partialfonts/8859-1.a0-ff.16.gz" "%{_datadir}/consolefonts/partialfonts/8859-1.a0-ff.16.gz" \
"usr/share/consolefonts/partialfonts/cp437.00-1f.08.gz" "%{_datadir}/consolefonts/partialfonts/cp437.00-1f.08.gz" \
"usr/share/consolefonts/partialfonts/8859-5.a0-ff.14.gz" "%{_datadir}/consolefonts/partialfonts/8859-5.a0-ff.14.gz" \
"usr/share/consolefonts/928.cp.gz" "%{_datadir}/consolefonts/928.cp.gz" \
"usr/share/consolefonts/iso05.14.gz" "%{_datadir}/consolefonts/iso05.14.gz" \
"usr/share/consolefonts/iso08.14.gz" "%{_datadir}/consolefonts/iso08.14.gz" \
"usr/share/consolefonts/iso02.08.gz" "%{_datadir}/consolefonts/iso02.08.gz" \
"usr/share/consolefonts/latarcyrheb-sun16.psfu.gz" "%{_datadir}/consolefonts/latarcyrheb-sun16.psfu.gz" \
"usr/share/consolefonts/gr928a-8x16.psfu.gz" "%{_datadir}/consolefonts/gr928a-8x16.psfu.gz" \
"usr/share/consolefonts/UniCyrExt_8x16.psf.gz" "%{_datadir}/consolefonts/UniCyrExt_8x16.psf.gz" \
"usr/share/consolefonts/koi8u_8x14.psfu.gz" "%{_datadir}/consolefonts/koi8u_8x14.psfu.gz" \
"usr/share/consolefonts/README.psfu" "%{_datadir}/consolefonts/README.psfu" \
"usr/share/consolefonts/lat2a-16.psfu.gz" "%{_datadir}/consolefonts/lat2a-16.psfu.gz" \
"usr/share/consolefonts/koi8c-8x16.gz" "%{_datadir}/consolefonts/koi8c-8x16.gz" \
"usr/share/consolefonts/UniCyr_8x8.psf.gz" "%{_datadir}/consolefonts/UniCyr_8x8.psf.gz" \
"usr/share/consolefonts/gr928-8x16-thin.psfu.gz" "%{_datadir}/consolefonts/gr928-8x16-thin.psfu.gz" \
"usr/share/consolefonts/lat9v-08.psfu.gz" "%{_datadir}/consolefonts/lat9v-08.psfu.gz" \
"usr/share/consolefonts/iso09.14.gz" "%{_datadir}/consolefonts/iso09.14.gz" \
"usr/share/consolefonts/iso08.08.gz" "%{_datadir}/consolefonts/iso08.08.gz" \
"usr/share/consolefonts/iso02.14.gz" "%{_datadir}/consolefonts/iso02.14.gz" \
"usr/share/consolefonts/737.cp.gz" "%{_datadir}/consolefonts/737.cp.gz" \
"usr/share/consolefonts/lat0-16.psfu.gz" "%{_datadir}/consolefonts/lat0-16.psfu.gz" \
"usr/share/consolefonts/arm8.fnt.gz" "%{_datadir}/consolefonts/arm8.fnt.gz" \
"usr/share/consolefonts/default8x16.psfu.gz" "%{_datadir}/consolefonts/default8x16.psfu.gz" \
"usr/share/consolefonts/lat9-14.psf.gz" "%{_datadir}/consolefonts/lat9-14.psf.gz" \
"usr/share/consolefonts/lat5-14.psfu.gz" "%{_datadir}/consolefonts/lat5-14.psfu.gz" \
"usr/share/consolefonts/README.Ethiopic" "%{_datadir}/consolefonts/README.Ethiopic" \
"usr/share/consolefonts/README.Lat2-Terminus16" "%{_datadir}/consolefonts/README.Lat2-Terminus16" \
"usr/share/consolefonts/lat0-10.psfu.gz" "%{_datadir}/consolefonts/lat0-10.psfu.gz" \
"usr/share/consolefonts/iso01.16.gz" "%{_datadir}/consolefonts/iso01.16.gz" \
"usr/share/consolefonts/lat9w-16.psfu.gz" "%{_datadir}/consolefonts/lat9w-16.psfu.gz" \
"usr/share/consolefonts/README.cybercafe" "%{_datadir}/consolefonts/README.cybercafe" \
"usr/share/consolefonts/lat4-14.psfu.gz" "%{_datadir}/consolefonts/lat4-14.psfu.gz" \
"usr/share/consolefonts/LatArCyrHeb-08.psfu.gz" "%{_datadir}/consolefonts/LatArCyrHeb-08.psfu.gz" \
"usr/share/consolefonts/lat1-10.psfu.gz" "%{_datadir}/consolefonts/lat1-10.psfu.gz" \
"usr/share/consolefonts/gr928b-8x14.psfu.gz" "%{_datadir}/consolefonts/gr928b-8x14.psfu.gz" \
"usr/share/consolefonts/README.Arabic" "%{_datadir}/consolefonts/README.Arabic" \
"usr/share/consolefonts/README.lat0" "%{_datadir}/consolefonts/README.lat0" \
"usr/share/consolefonts/Cyr_a8x8.psfu.gz" "%{_datadir}/consolefonts/Cyr_a8x8.psfu.gz" \
"usr/share/consolefonts/koi8r.8x8.psfu.gz" "%{_datadir}/consolefonts/koi8r.8x8.psfu.gz" \
"usr/share/consolefonts/lat7a-14.psfu.gz" "%{_datadir}/consolefonts/lat7a-14.psfu.gz" \
"usr/share/consolefonts/lat0-sun16.psfu.gz" "%{_datadir}/consolefonts/lat0-sun16.psfu.gz" \
"usr/share/consolefonts/lat4-10.psfu.gz" "%{_datadir}/consolefonts/lat4-10.psfu.gz" \
"usr/share/consolefonts/cp866-8x16.psf.gz" "%{_datadir}/consolefonts/cp866-8x16.psf.gz" \
"usr/share/consolefonts/gr737d-8x16.psfu.gz" "%{_datadir}/consolefonts/gr737d-8x16.psfu.gz" \
"usr/share/consolefonts/lat9w-14.psfu.gz" "%{_datadir}/consolefonts/lat9w-14.psfu.gz" \
"usr/share/consolefonts/lat4-16.psfu.gz" "%{_datadir}/consolefonts/lat4-16.psfu.gz" \
"usr/share/consolefonts/161.cp.gz" "%{_datadir}/consolefonts/161.cp.gz" \
"usr/share/consolefonts/alt-8x14.gz" "%{_datadir}/consolefonts/alt-8x14.gz" \
"usr/share/consolefonts/README.eurlatgr" "%{_datadir}/consolefonts/README.eurlatgr" \
"usr/share/consolefonts/default8x9.psfu.gz" "%{_datadir}/consolefonts/default8x9.psfu.gz" \
"usr/share/consolefonts/gr737c-8x16.psfu.gz" "%{_datadir}/consolefonts/gr737c-8x16.psfu.gz" \
"usr/share/consolefonts/lat0-08.psfu.gz" "%{_datadir}/consolefonts/lat0-08.psfu.gz" \
"usr/share/consolefonts/README.LatGrkCyr" "%{_datadir}/consolefonts/README.LatGrkCyr" \
"usr/share/consolefonts/cyr-sun16.psfu.gz" "%{_datadir}/consolefonts/cyr-sun16.psfu.gz" \
"usr/share/consolefonts/iso01-12x22.psfu.gz" "%{_datadir}/consolefonts/iso01-12x22.psfu.gz" \
"usr/share/consolefonts/t850b.fnt.gz" "%{_datadir}/consolefonts/t850b.fnt.gz" \
"usr/share/consolefonts/lat4a-19.psfu.gz" "%{_datadir}/consolefonts/lat4a-19.psfu.gz" \
"usr/share/consolefonts/lat9v-14.psfu.gz" "%{_datadir}/consolefonts/lat9v-14.psfu.gz" \
"usr/share/consolefonts/LatKaCyrHeb-14.psfu.gz" "%{_datadir}/consolefonts/LatKaCyrHeb-14.psfu.gz" \
"usr/share/consolefonts/iso07.16.gz" "%{_datadir}/consolefonts/iso07.16.gz" \
"usr/share/consolefonts/lat1-16.psfu.gz" "%{_datadir}/consolefonts/lat1-16.psfu.gz" \
"usr/share/consolefonts/lat7-14.psfu.gz" "%{_datadir}/consolefonts/lat7-14.psfu.gz" \
"usr/share/consolefonts/LatGrkCyr-8x16.psfu.gz" "%{_datadir}/consolefonts/LatGrkCyr-8x16.psfu.gz" \
"usr/share/consolefonts/koi8-14.psf.gz" "%{_datadir}/consolefonts/koi8-14.psf.gz" \
"usr/share/consolefonts/README.12x22" "%{_datadir}/consolefonts/README.12x22" \
"usr/share/consolefonts/lat4a-14.psfu.gz" "%{_datadir}/consolefonts/lat4a-14.psfu.gz" \
"usr/share/consolefonts/gr737c-8x14.psfu.gz" "%{_datadir}/consolefonts/gr737c-8x14.psfu.gz" \
"usr/share/consolefonts/drdos8x16.psfu.gz" "%{_datadir}/consolefonts/drdos8x16.psfu.gz" \
"usr/share/consolefonts/iso09.16.gz" "%{_datadir}/consolefonts/iso09.16.gz" \
"usr/share/consolefonts/lat2-16.psfu.gz" "%{_datadir}/consolefonts/lat2-16.psfu.gz" \
"usr/share/consolefonts/cp850-8x16.psfu.gz" "%{_datadir}/consolefonts/cp850-8x16.psfu.gz" \
"usr/share/consolefonts/drdos8x6.psfu.gz" "%{_datadir}/consolefonts/drdos8x6.psfu.gz" \
"usr/share/consolefonts/lat2-10.psfu.gz" "%{_datadir}/consolefonts/lat2-10.psfu.gz" \
"usr/share/consolefonts/UniCyr_8x14.psf.gz" "%{_datadir}/consolefonts/UniCyr_8x14.psf.gz" \
"usr/share/consolefonts/iso05.08.gz" "%{_datadir}/consolefonts/iso05.08.gz" \
"usr/share/consolefonts/ERRORS" "%{_datadir}/consolefonts/ERRORS" \
"usr/share/consolefonts/iso07.14.gz" "%{_datadir}/consolefonts/iso07.14.gz" \
"usr/share/consolefonts/iso06.16.gz" "%{_datadir}/consolefonts/iso06.16.gz" \
"usr/share/consolefonts/iso04.08.gz" "%{_datadir}/consolefonts/iso04.08.gz" \
"usr/share/consolefonts/lat4a-16+.psfu.gz" "%{_datadir}/consolefonts/lat4a-16+.psfu.gz" \
"usr/share/consolefonts/iso04.14.gz" "%{_datadir}/consolefonts/iso04.14.gz" \
"usr/share/consolefonts/lat4-12.psfu.gz" "%{_datadir}/consolefonts/lat4-12.psfu.gz" \
"usr/share/consolefonts/iso10.14.gz" "%{_datadir}/consolefonts/iso10.14.gz" \
"usr/share/consolefonts/README.lat9" "%{_datadir}/consolefonts/README.lat9" \
"usr/share/consolefonts/lat9v-10.psfu.gz" "%{_datadir}/consolefonts/lat9v-10.psfu.gz" \
"usr/share/consolefonts/gr737c-8x8.psfu.gz" "%{_datadir}/consolefonts/gr737c-8x8.psfu.gz" \
"usr/share/consolefonts/LatArCyrHeb-16+.psfu.gz" "%{_datadir}/consolefonts/LatArCyrHeb-16+.psfu.gz" \
"usr/share/consolefonts/lat9u-12.psfu.gz" "%{_datadir}/consolefonts/lat9u-12.psfu.gz" \
"usr/share/consolefonts/lat2-12.psfu.gz" "%{_datadir}/consolefonts/lat2-12.psfu.gz" \
"usr/share/consolefonts/lat4a-16.psfu.gz" "%{_datadir}/consolefonts/lat4a-16.psfu.gz" \
"usr/share/consolefonts/iso02.16.gz" "%{_datadir}/consolefonts/iso02.16.gz" \
"usr/share/consolefonts/Cyr_a8x16.psfu.gz" "%{_datadir}/consolefonts/Cyr_a8x16.psfu.gz" \
"usr/share/consolefonts/lat9u-08.psfu.gz" "%{_datadir}/consolefonts/lat9u-08.psfu.gz" \
"usr/share/consolefonts/cp850-8x8.psfu.gz" "%{_datadir}/consolefonts/cp850-8x8.psfu.gz" \
"usr/share/consolefonts/163.cp.gz" "%{_datadir}/consolefonts/163.cp.gz" \
"usr/share/consolefonts/lat4a-10.psfu.gz" "%{_datadir}/consolefonts/lat4a-10.psfu.gz" \
"usr/share/consolefonts/gr737b-9x16-medieval.psfu.gz" "%{_datadir}/consolefonts/gr737b-9x16-medieval.psfu.gz" \
"usr/share/consolefonts/README.Cyrillic" "%{_datadir}/consolefonts/README.Cyrillic" \
"usr/share/consolefonts/iso01.14.gz" "%{_datadir}/consolefonts/iso01.14.gz" \
"usr/share/consolefonts/tcvn8x16.psf.gz" "%{_datadir}/consolefonts/tcvn8x16.psf.gz" \
"usr/share/consolefonts/lat0-12.psfu.gz" "%{_datadir}/consolefonts/lat0-12.psfu.gz" \
"usr/share/consolefonts/iso03.16.gz" "%{_datadir}/consolefonts/iso03.16.gz" \
"usr/share/consolefonts/cp865-8x16.psfu.gz" "%{_datadir}/consolefonts/cp865-8x16.psfu.gz" \
"usr/share/consolefonts/lat9u-14.psfu.gz" "%{_datadir}/consolefonts/lat9u-14.psfu.gz" \
"usr/share/consolefonts/koi8u_8x8.psfu.gz" "%{_datadir}/consolefonts/koi8u_8x8.psfu.gz" \
"usr/share/consolefonts/Goha-12.psfu.gz" "%{_datadir}/consolefonts/Goha-12.psfu.gz" \
"usr/share/consolefonts/lat9u-10.psfu.gz" "%{_datadir}/consolefonts/lat9u-10.psfu.gz" \
"usr/share/consolefonts/UniCyr_8x16.psf.gz" "%{_datadir}/consolefonts/UniCyr_8x16.psf.gz" \
"usr/share/consolefonts/lat1-08.psfu.gz" "%{_datadir}/consolefonts/lat1-08.psfu.gz" \
"usr/share/consolefonts/solar24x32.psfu.gz" "%{_datadir}/consolefonts/solar24x32.psfu.gz" \
"usr/share/consolefonts/LatGrkCyr-12x22.psfu.gz" "%{_datadir}/consolefonts/LatGrkCyr-12x22.psfu.gz" \
"usr/share/consolefonts/lat4a-12.psfu.gz" "%{_datadir}/consolefonts/lat4a-12.psfu.gz" \
"usr/share/consolefonts/lat9u-16.psfu.gz" "%{_datadir}/consolefonts/lat9u-16.psfu.gz" \
"usr/share/consolefonts/lat4a-08.psfu.gz" "%{_datadir}/consolefonts/lat4a-08.psfu.gz" \
"usr/share/consolefonts/lat4-08.psfu.gz" "%{_datadir}/consolefonts/lat4-08.psfu.gz" \
"usr/share/consolefonts/cp857.08.gz" "%{_datadir}/consolefonts/cp857.08.gz" \
"usr/share/consolefonts/LatArCyrHeb-16.psfu.gz" "%{_datadir}/consolefonts/LatArCyrHeb-16.psfu.gz" \
"usr/share/consolefonts/README.drdos" "%{_datadir}/consolefonts/README.drdos" \
"usr/share/consolefonts/lat2-08.psfu.gz" "%{_datadir}/consolefonts/lat2-08.psfu.gz" \
"usr/share/consolefonts/greek-polytonic.psfu.gz" "%{_datadir}/consolefonts/greek-polytonic.psfu.gz" \
"usr/share/consolefonts/iso10.08.gz" "%{_datadir}/consolefonts/iso10.08.gz" \
"usr/share/consolefonts/README.eurlatgr.mappings" "%{_datadir}/consolefonts/README.eurlatgr.mappings" \
"usr/share/consolefonts/cp866-8x8.psf.gz" "%{_datadir}/consolefonts/cp866-8x8.psf.gz" \
"usr/share/consolefonts/gr737c-8x7.psfu.gz" "%{_datadir}/consolefonts/gr737c-8x7.psfu.gz" \
"usr/share/consolefonts/README.Sun" "%{_datadir}/consolefonts/README.Sun" \
"usr/share/consolefonts/165.cp.gz" "%{_datadir}/consolefonts/165.cp.gz" \
"usr/share/consolefonts/gr737a-8x8.psfu.gz" "%{_datadir}/consolefonts/gr737a-8x8.psfu.gz" \
"usr/share/consolefonts/cp865-8x14.psfu.gz" "%{_datadir}/consolefonts/cp865-8x14.psfu.gz" \
"usr/share/consolefonts/pancyrillic.f16.psfu.gz" "%{_datadir}/consolefonts/pancyrillic.f16.psfu.gz" \
"usr/share/consolefonts/lat1-12.psfu.gz" "%{_datadir}/consolefonts/lat1-12.psfu.gz" \
"usr/share/consolefonts/iso03.08.gz" "%{_datadir}/consolefonts/iso03.08.gz" \
"usr/share/consolefonts/koi8r-8x14.gz" "%{_datadir}/consolefonts/koi8r-8x14.gz" \
"usr/share/consolefonts/iso10.16.gz" "%{_datadir}/consolefonts/iso10.16.gz" \
"usr/share/consolefonts/iso06.14.gz" "%{_datadir}/consolefonts/iso06.14.gz" \
"usr/share/consolefonts/iso09.08.gz" "%{_datadir}/consolefonts/iso09.08.gz" \
"usr/share/consolefonts/164.cp.gz" "%{_datadir}/consolefonts/164.cp.gz" \
"usr/share/consolefonts/lat2-14.psfu.gz" "%{_datadir}/consolefonts/lat2-14.psfu.gz" \
"usr/share/consolefonts/koi8u_8x16.psfu.gz" "%{_datadir}/consolefonts/koi8u_8x16.psfu.gz" \
"usr/share/consolefonts/gr737c-8x6.psfu.gz" "%{_datadir}/consolefonts/gr737c-8x6.psfu.gz" \
"usr/share/consolefonts/drdos8x14.psfu.gz" "%{_datadir}/consolefonts/drdos8x14.psfu.gz" \
"usr/share/consolefonts/gr928a-8x14.psfu.gz" "%{_datadir}/consolefonts/gr928a-8x14.psfu.gz" \
"usr/share/consolefonts/lat7a-16.psf.gz" "%{_datadir}/consolefonts/lat7a-16.psf.gz" \
"usr/share/consolefonts/162.cp.gz" "%{_datadir}/consolefonts/162.cp.gz" \
"usr/share/consolefonts/gr928-9x16.psfu.gz" "%{_datadir}/consolefonts/gr928-9x16.psfu.gz" \
"usr/share/consolefonts/alt-8x16.gz" "%{_datadir}/consolefonts/alt-8x16.gz" \
"usr/share/consolefonts/latarcyrheb-sun32.psfu.gz" "%{_datadir}/consolefonts/latarcyrheb-sun32.psfu.gz" \
"usr/share/consolefonts/iso06.08.gz" "%{_datadir}/consolefonts/iso06.08.gz" \
"usr/share/consolefonts/lat9-08.psf.gz" "%{_datadir}/consolefonts/lat9-08.psf.gz" \
"usr/share/consolefonts/lat1-14.psfu.gz" "%{_datadir}/consolefonts/lat1-14.psfu.gz" \
"usr/share/consolefonts/lat9v-12.psfu.gz" "%{_datadir}/consolefonts/lat9v-12.psfu.gz" \
"usr/share/consolefonts/GohaClassic-12.psfu.gz" "%{_datadir}/consolefonts/GohaClassic-12.psfu.gz" \
"usr/share/consolefonts/lat5-12.psfu.gz" "%{_datadir}/consolefonts/lat5-12.psfu.gz" \
"usr/share/consolefonts/lat9w-10.psfu.gz" "%{_datadir}/consolefonts/lat9w-10.psfu.gz" \
"usr/share/consolefonts/Goha-16.psfu.gz" "%{_datadir}/consolefonts/Goha-16.psfu.gz" \
"usr/share/consolefonts/koi8r-8x16.gz" "%{_datadir}/consolefonts/koi8r-8x16.gz" \
"usr/share/consolefonts/drdos8x8.psfu.gz" "%{_datadir}/consolefonts/drdos8x8.psfu.gz" \
"usr/share/consolefonts/cp850-8x14.psfu.gz" "%{_datadir}/consolefonts/cp850-8x14.psfu.gz" \
"usr/share/consolefonts/lat9v-16.psfu.gz" "%{_datadir}/consolefonts/lat9v-16.psfu.gz" \
"usr/share/consolefonts/LatArCyrHeb-19.psfu.gz" "%{_datadir}/consolefonts/LatArCyrHeb-19.psfu.gz" \
"usr/share/consolefonts/README.Greek" "%{_datadir}/consolefonts/README.Greek" \
"usr/share/consolefonts/gr928b-8x16.psfu.gz" "%{_datadir}/consolefonts/gr928b-8x16.psfu.gz" \
"usr/share/consolefonts/ruscii_8x8.psfu.gz" "%{_datadir}/consolefonts/ruscii_8x8.psfu.gz" \
"usr/share/consolefonts/LatArCyrHeb-14.psfu.gz" "%{_datadir}/consolefonts/LatArCyrHeb-14.psfu.gz" \
"usr/share/consolefonts/880.cp.gz" "%{_datadir}/consolefonts/880.cp.gz" \
"usr/share/consolefonts/cybercafe.fnt.gz" "%{_datadir}/consolefonts/cybercafe.fnt.gz" \
"usr/share/consolefonts/cp865-8x8.psfu.gz" "%{_datadir}/consolefonts/cp865-8x8.psfu.gz" \
"usr/share/consolefonts/Goha-14.psfu.gz" "%{_datadir}/consolefonts/Goha-14.psfu.gz" \
"usr/share/consolefonts/iso02-12x22.psfu.gz" "%{_datadir}/consolefonts/iso02-12x22.psfu.gz" \
"usr/share/consolefonts/README.cp1250" "%{_datadir}/consolefonts/README.cp1250" \
"usr/share/consolefonts/cp866-8x14.psf.gz" "%{_datadir}/consolefonts/cp866-8x14.psf.gz" \
"usr/share/consolefonts/gr737a-9x16.psfu.gz" "%{_datadir}/consolefonts/gr737a-9x16.psfu.gz" \
"usr/share/consolefonts/lat9w-12.psfu.gz" "%{_datadir}/consolefonts/lat9w-12.psfu.gz" \
"usr/share/consolefonts/t.fnt.gz" "%{_datadir}/consolefonts/t.fnt.gz" \
"usr/share/consolefonts/GohaClassic-14.psfu.gz" "%{_datadir}/consolefonts/GohaClassic-14.psfu.gz" \
"usr/share/consolefonts/Cyr_a8x14.psfu.gz" "%{_datadir}/consolefonts/Cyr_a8x14.psfu.gz" \
"usr/share/consolefonts/gr928-9x14.psfu.gz" "%{_datadir}/consolefonts/gr928-9x14.psfu.gz" \
"usr/share/consolefonts/lat9w-08.psfu.gz" "%{_datadir}/consolefonts/lat9w-08.psfu.gz" \
"usr/share/consolefonts/iso07u-16.psfu.gz" "%{_datadir}/consolefonts/iso07u-16.psfu.gz" \
"usr/share/consolefonts/koi8r-8x8.gz" "%{_datadir}/consolefonts/koi8r-8x8.gz" \
"usr/share/consolefonts/sun12x22.psfu.gz" "%{_datadir}/consolefonts/sun12x22.psfu.gz" \
"usr/share/consolefonts/iso03.14.gz" "%{_datadir}/consolefonts/iso03.14.gz" \
"usr/share/consolefonts/lat9-10.psf.gz" "%{_datadir}/consolefonts/lat9-10.psf.gz" \
"usr/share/consolefonts/GohaClassic-16.psfu.gz" "%{_datadir}/consolefonts/GohaClassic-16.psfu.gz" \
"usr/share/consolefonts/gr737a-9x14.psfu.gz" "%{_datadir}/consolefonts/gr737a-9x14.psfu.gz" \
"usr/share/consolefonts/iso01.08.gz" "%{_datadir}/consolefonts/iso01.08.gz" \
"usr/share/consolefonts/README.Hebrew" "%{_datadir}/consolefonts/README.Hebrew" \
"usr/share/consolefonts/viscii10-8x16.psfu.gz" "%{_datadir}/consolefonts/viscii10-8x16.psfu.gz" \
"usr/share/consolefonts/cp1250.psfu.gz" "%{_datadir}/consolefonts/cp1250.psfu.gz" \
"usr/share/consolefonts/cp857.16.gz" "%{_datadir}/consolefonts/cp857.16.gz" \
"usr/share/consoletrans/koi8u2ruscii" "%{_datadir}/consoletrans/koi8u2ruscii" \
"usr/share/consoletrans/cp866_to_uni.trans" "%{_datadir}/consoletrans/cp866_to_uni.trans" \
"usr/share/consoletrans/cp775_to_uni.trans" "%{_datadir}/consoletrans/cp775_to_uni.trans" \
"usr/share/consoletrans/null" "%{_datadir}/consoletrans/null" \
"usr/share/consoletrans/viscii1.0_to_viscii1.1.trans" "%{_datadir}/consoletrans/viscii1.0_to_viscii1.1.trans" \
"usr/share/consoletrans/cp874_to_uni.trans" "%{_datadir}/consoletrans/cp874_to_uni.trans" \
"usr/share/consoletrans/iso02_to_cp1250.trans" "%{_datadir}/consoletrans/iso02_to_cp1250.trans" \
"usr/share/consoletrans/cp850_to_iso01.trans" "%{_datadir}/consoletrans/cp850_to_iso01.trans" \
"usr/share/consoletrans/8859-13_to_uni.trans" "%{_datadir}/consoletrans/8859-13_to_uni.trans" \
"usr/share/consoletrans/trivial" "%{_datadir}/consoletrans/trivial" \
"usr/share/consoletrans/koi8-r_to_uni.trans" "%{_datadir}/consoletrans/koi8-r_to_uni.trans" \
"usr/share/consoletrans/8859-9_to_uni.trans" "%{_datadir}/consoletrans/8859-9_to_uni.trans" \
"usr/share/consoletrans/latin2u.trans" "%{_datadir}/consoletrans/latin2u.trans" \
"usr/share/consoletrans/cp852_to_uni.trans" "%{_datadir}/consoletrans/cp852_to_uni.trans" \
"usr/share/consoletrans/koi8-u_to_uni.trans" "%{_datadir}/consoletrans/koi8-u_to_uni.trans" \
"usr/share/consoletrans/utflist" "%{_datadir}/consoletrans/utflist" \
"usr/share/consoletrans/cp855_to_uni.trans" "%{_datadir}/consoletrans/cp855_to_uni.trans" \
"usr/share/consoletrans/cp864_to_uni.trans" "%{_datadir}/consoletrans/cp864_to_uni.trans" \
"usr/share/consoletrans/baltic.trans" "%{_datadir}/consoletrans/baltic.trans" \
"usr/share/consoletrans/cp869_to_uni.trans" "%{_datadir}/consoletrans/cp869_to_uni.trans" \
"usr/share/consoletrans/koi2alt" "%{_datadir}/consoletrans/koi2alt" \
"usr/share/consoletrans/space" "%{_datadir}/consoletrans/space" \
"usr/share/consoletrans/8859-2_to_uni.trans" "%{_datadir}/consoletrans/8859-2_to_uni.trans" \
"usr/share/consoletrans/cp865_to_uni.trans" "%{_datadir}/consoletrans/cp865_to_uni.trans" \
"usr/share/consoletrans/cp863_to_uni.trans" "%{_datadir}/consoletrans/cp863_to_uni.trans" \
"usr/share/consoletrans/8859-3_to_uni.trans" "%{_datadir}/consoletrans/8859-3_to_uni.trans" \
"usr/share/consoletrans/cp437_to_iso01.trans" "%{_datadir}/consoletrans/cp437_to_iso01.trans" \
"usr/share/consoletrans/8859-7_to_uni.trans" "%{_datadir}/consoletrans/8859-7_to_uni.trans" \
"usr/share/consoletrans/viscii1.0_to_tcvn.trans" "%{_datadir}/consoletrans/viscii1.0_to_tcvn.trans" \
"usr/share/consoletrans/8859-8_to_uni.trans" "%{_datadir}/consoletrans/8859-8_to_uni.trans" \
"usr/share/consoletrans/8859-14_to_uni.trans" "%{_datadir}/consoletrans/8859-14_to_uni.trans" \
"usr/share/consoletrans/cp857_to_uni.trans" "%{_datadir}/consoletrans/cp857_to_uni.trans" \
"usr/share/consoletrans/8859-10_to_uni.trans" "%{_datadir}/consoletrans/8859-10_to_uni.trans" \
"usr/share/consoletrans/8859-15_to_uni.trans" "%{_datadir}/consoletrans/8859-15_to_uni.trans" \
"usr/share/consoletrans/cp861_to_uni.trans" "%{_datadir}/consoletrans/cp861_to_uni.trans" \
"usr/share/consoletrans/cp1250_to_uni.trans" "%{_datadir}/consoletrans/cp1250_to_uni.trans" \
"usr/share/consoletrans/cp850_to_uni.trans" "%{_datadir}/consoletrans/cp850_to_uni.trans" \
"usr/share/consoletrans/cp860_to_uni.trans" "%{_datadir}/consoletrans/cp860_to_uni.trans" \
"usr/share/consoletrans/8859-4_to_uni.trans" "%{_datadir}/consoletrans/8859-4_to_uni.trans" \
"usr/share/consoletrans/8859-5_to_uni.trans" "%{_datadir}/consoletrans/8859-5_to_uni.trans" \
"usr/share/consoletrans/vga2iso" "%{_datadir}/consoletrans/vga2iso" \
"usr/share/consoletrans/8859-1_to_uni.trans" "%{_datadir}/consoletrans/8859-1_to_uni.trans" \
"usr/share/consoletrans/cp737_to_uni.trans" "%{_datadir}/consoletrans/cp737_to_uni.trans" \
"usr/share/consoletrans/cp1251_to_uni.trans" "%{_datadir}/consoletrans/cp1251_to_uni.trans" \
"usr/share/consoletrans/cp853_to_uni.trans" "%{_datadir}/consoletrans/cp853_to_uni.trans" \
"usr/share/consoletrans/cp437_to_uni.trans" "%{_datadir}/consoletrans/cp437_to_uni.trans" \
"usr/share/consoletrans/zero" "%{_datadir}/consoletrans/zero" \
"usr/share/consoletrans/cp862_to_uni.trans" "%{_datadir}/consoletrans/cp862_to_uni.trans" \
"usr/share/consoletrans/8859-6_to_uni.trans" "%{_datadir}/consoletrans/8859-6_to_uni.trans" \
"usr/share/locale/de/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/de/LC_MESSAGES/kbd.mo" \
"usr/share/locale/pt_BR/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/pt_BR/LC_MESSAGES/kbd.mo" \
"usr/share/locale/tr/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/tr/LC_MESSAGES/kbd.mo" \
"usr/share/locale/hu/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/hu/LC_MESSAGES/kbd.mo" \
"usr/share/locale/da/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/da/LC_MESSAGES/kbd.mo" \
"usr/share/locale/sr/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/sr/LC_MESSAGES/kbd.mo" \
"usr/share/locale/ka/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/ka/LC_MESSAGES/kbd.mo" \
"usr/share/locale/pl/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/pl/LC_MESSAGES/kbd.mo" \
"usr/share/locale/cs/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/cs/LC_MESSAGES/kbd.mo" \
"usr/share/locale/sq/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/sq/LC_MESSAGES/kbd.mo" \
"usr/share/locale/it/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/it/LC_MESSAGES/kbd.mo" \
"usr/share/locale/nl/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/nl/LC_MESSAGES/kbd.mo" \
"usr/share/locale/es/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/es/LC_MESSAGES/kbd.mo" \
"usr/share/locale/el/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/el/LC_MESSAGES/kbd.mo" \
"usr/share/locale/eo/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/eo/LC_MESSAGES/kbd.mo" \
"usr/share/locale/uk/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/uk/LC_MESSAGES/kbd.mo" \
"usr/share/locale/vi/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/vi/LC_MESSAGES/kbd.mo" \
"usr/share/locale/ru/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/ru/LC_MESSAGES/kbd.mo" \
"usr/share/locale/sv/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/sv/LC_MESSAGES/kbd.mo" \
"usr/share/locale/zh_CN/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/zh_CN/LC_MESSAGES/kbd.mo" \
"usr/share/locale/id/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/id/LC_MESSAGES/kbd.mo" \
"usr/share/locale/ro/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/ro/LC_MESSAGES/kbd.mo" \
"usr/share/locale/pt/LC_MESSAGES/kbd.mo" "%{_datadir}/locale/pt/LC_MESSAGES/kbd.mo" \
"usr/share/unimaps/cp866.uni" "%{_datadir}/unimaps/cp866.uni" \
"usr/share/unimaps/iso15.uni" "%{_datadir}/unimaps/iso15.uni" \
"usr/share/unimaps/README" "%{_datadir}/unimaps/README" \
"usr/share/unimaps/lat9v.uni" "%{_datadir}/unimaps/lat9v.uni" \
"usr/share/unimaps/8859-3.a0-ff.uni" "%{_datadir}/unimaps/8859-3.a0-ff.uni" \
"usr/share/unimaps/8859-8.a0-ff.uni" "%{_datadir}/unimaps/8859-8.a0-ff.uni" \
"usr/share/unimaps/ethiopic.uni" "%{_datadir}/unimaps/ethiopic.uni" \
"usr/share/unimaps/ruscii.uni" "%{_datadir}/unimaps/ruscii.uni" \
"usr/share/unimaps/cp737c.uni" "%{_datadir}/unimaps/cp737c.uni" \
"usr/share/unimaps/8859-1.a0-ff.uni" "%{_datadir}/unimaps/8859-1.a0-ff.uni" \
"usr/share/unimaps/iso07u.uni" "%{_datadir}/unimaps/iso07u.uni" \
"usr/share/unimaps/cp865a.uni" "%{_datadir}/unimaps/cp865a.uni" \
"usr/share/unimaps/cp1250.uni" "%{_datadir}/unimaps/cp1250.uni" \
"usr/share/unimaps/lat1.uni" "%{_datadir}/unimaps/lat1.uni" \
"usr/share/unimaps/lat2.uni" "%{_datadir}/unimaps/lat2.uni" \
"usr/share/unimaps/iso04.uni" "%{_datadir}/unimaps/iso04.uni" \
"usr/share/unimaps/viscii.uni" "%{_datadir}/unimaps/viscii.uni" \
"usr/share/unimaps/cp437.00-1f.uni" "%{_datadir}/unimaps/cp437.00-1f.uni" \
"usr/share/unimaps/lat7.uni" "%{_datadir}/unimaps/lat7.uni" \
"usr/share/unimaps/cybercafe.uni" "%{_datadir}/unimaps/cybercafe.uni" \
"usr/share/unimaps/armscii8.uni" "%{_datadir}/unimaps/armscii8.uni" \
"usr/share/unimaps/cp437.uni" "%{_datadir}/unimaps/cp437.uni" \
"usr/share/unimaps/koi8u.uni" "%{_datadir}/unimaps/koi8u.uni" \
"usr/share/unimaps/iso05.uni" "%{_datadir}/unimaps/iso05.uni" \
"usr/share/unimaps/8859-6.a0-ff.uni" "%{_datadir}/unimaps/8859-6.a0-ff.uni" \
"usr/share/unimaps/8859-7.a0-ff.uni" "%{_datadir}/unimaps/8859-7.a0-ff.uni" \
"usr/share/unimaps/cp737a.uni" "%{_datadir}/unimaps/cp737a.uni" \
"usr/share/unimaps/iso01.uni" "%{_datadir}/unimaps/iso01.uni" \
"usr/share/unimaps/8859-14.a0-ff.uni" "%{_datadir}/unimaps/8859-14.a0-ff.uni" \
"usr/share/unimaps/tcvn.uni" "%{_datadir}/unimaps/tcvn.uni" \
"usr/share/unimaps/cp866a.uni" "%{_datadir}/unimaps/cp866a.uni" \
"usr/share/unimaps/cp850z.uni" "%{_datadir}/unimaps/cp850z.uni" \
"usr/share/unimaps/cp865.uni" "%{_datadir}/unimaps/cp865.uni" \
"usr/share/unimaps/cp737.uni" "%{_datadir}/unimaps/cp737.uni" \
"usr/share/unimaps/ECMA144.uni" "%{_datadir}/unimaps/ECMA144.uni" \
"usr/share/unimaps/iso03.uni" "%{_datadir}/unimaps/iso03.uni" \
"usr/share/unimaps/def.uni" "%{_datadir}/unimaps/def.uni" \
"usr/share/unimaps/lat4u.uni" "%{_datadir}/unimaps/lat4u.uni" \
"usr/share/unimaps/cp737b.uni" "%{_datadir}/unimaps/cp737b.uni" \
"usr/share/unimaps/iso02.uni" "%{_datadir}/unimaps/iso02.uni" \
"usr/share/unimaps/8859-5.a0-ff.uni" "%{_datadir}/unimaps/8859-5.a0-ff.uni" \
"usr/share/unimaps/8859-9.a0-ff.uni" "%{_datadir}/unimaps/8859-9.a0-ff.uni" \
"usr/share/unimaps/lat9w.uni" "%{_datadir}/unimaps/lat9w.uni" \
"usr/share/unimaps/8859-13.a0-ff.uni" "%{_datadir}/unimaps/8859-13.a0-ff.uni" \
"usr/share/unimaps/iso08.uni" "%{_datadir}/unimaps/iso08.uni" \
"usr/share/unimaps/8859-2.a0-ff.uni" "%{_datadir}/unimaps/8859-2.a0-ff.uni" \
"usr/share/unimaps/cyralt.uni" "%{_datadir}/unimaps/cyralt.uni" \
"usr/share/unimaps/lat2u.uni" "%{_datadir}/unimaps/lat2u.uni" \
"usr/share/unimaps/koi8r.uni" "%{_datadir}/unimaps/koi8r.uni" \
"usr/share/unimaps/ascii.20-7f.uni" "%{_datadir}/unimaps/ascii.20-7f.uni" \
"usr/share/unimaps/empty.uni" "%{_datadir}/unimaps/empty.uni" \
"usr/share/unimaps/cp850a.uni" "%{_datadir}/unimaps/cp850a.uni" \
"usr/share/unimaps/lat1u.uni" "%{_datadir}/unimaps/lat1u.uni" \
"usr/share/unimaps/cp850.uni" "%{_datadir}/unimaps/cp850.uni" \
"usr/share/unimaps/lat9u.uni" "%{_datadir}/unimaps/lat9u.uni" \
"usr/share/unimaps/iso06.uni" "%{_datadir}/unimaps/iso06.uni" \
"usr/share/unimaps/lat4.uni" "%{_datadir}/unimaps/lat4.uni" \
"usr/share/unimaps/iso10.uni" "%{_datadir}/unimaps/iso10.uni" \
"usr/share/unimaps/cp850b.uni" "%{_datadir}/unimaps/cp850b.uni" \
"usr/share/unimaps/iso09.uni" "%{_datadir}/unimaps/iso09.uni" \
"usr/share/unimaps/8859-15.a0-ff.uni" "%{_datadir}/unimaps/8859-15.a0-ff.uni" \
"usr/share/unimaps/iso07.uni" "%{_datadir}/unimaps/iso07.uni" \
"usr/share/unimaps/8859-4.a0-ff.uni" "%{_datadir}/unimaps/8859-4.a0-ff.uni" \
"usr/share/unimaps/8859-10.a0-ff.uni" "%{_datadir}/unimaps/8859-10.a0-ff.uni" \
"usr/share/keymaps/amiga/amiga-de.map.gz" "%{_datadir}/keymaps/amiga/amiga-de.map.gz" \
"usr/share/keymaps/amiga/amiga-us.map.gz" "%{_datadir}/keymaps/amiga/amiga-us.map.gz" \
"usr/share/keymaps/pine/en.map.gz" "%{_datadir}/keymaps/pine/en.map.gz" \
"usr/share/keymaps/atari/atari-se.map.gz" "%{_datadir}/keymaps/atari/atari-se.map.gz" \
"usr/share/keymaps/atari/atari-us.map.gz" "%{_datadir}/keymaps/atari/atari-us.map.gz" \
"usr/share/keymaps/atari/atari-uk-falcon.map.gz" "%{_datadir}/keymaps/atari/atari-uk-falcon.map.gz" \
"usr/share/keymaps/atari/atari-de.map.gz" "%{_datadir}/keymaps/atari/atari-de.map.gz" \
"usr/share/keymaps/include/compose.latin2" "%{_datadir}/keymaps/include/compose.latin2" \
"usr/share/keymaps/include/vim-compose.latin1" "%{_datadir}/keymaps/include/vim-compose.latin1" \
"usr/share/keymaps/include/compose.latin1" "%{_datadir}/keymaps/include/compose.latin1" \
"usr/share/keymaps/include/compose.latin" "%{_datadir}/keymaps/include/compose.latin" \
"usr/share/keymaps/include/compose.8859_8" "%{_datadir}/keymaps/include/compose.8859_8" \
"usr/share/keymaps/include/compose.8859_7" "%{_datadir}/keymaps/include/compose.8859_7" \
"usr/share/keymaps/include/compose.latin3" "%{_datadir}/keymaps/include/compose.latin3" \
"usr/share/keymaps/include/compose.latin4" "%{_datadir}/keymaps/include/compose.latin4" \
"usr/share/keymaps/ppc" "%{_datadir}/keymaps/ppc" \
"usr/share/keymaps/sun/sun-pl.map.gz" "%{_datadir}/keymaps/sun/sun-pl.map.gz" \
"usr/share/keymaps/sun/sunt4-fi-latin1.map.gz" "%{_datadir}/keymaps/sun/sunt4-fi-latin1.map.gz" \
"usr/share/keymaps/sun/sunt5-es.map.gz" "%{_datadir}/keymaps/sun/sunt5-es.map.gz" \
"usr/share/keymaps/sun/sun-pl-altgraph.map.gz" "%{_datadir}/keymaps/sun/sun-pl-altgraph.map.gz" \
"usr/share/keymaps/sun/sunt4-no-latin1.map.gz" "%{_datadir}/keymaps/sun/sunt4-no-latin1.map.gz" \
"usr/share/keymaps/sun/sunt5-fi-latin1.map.gz" "%{_datadir}/keymaps/sun/sunt5-fi-latin1.map.gz" \
"usr/share/keymaps/sun/sunt5-cz-us.map.gz" "%{_datadir}/keymaps/sun/sunt5-cz-us.map.gz" \
"usr/share/keymaps/sun/sundvorak.map.gz" "%{_datadir}/keymaps/sun/sundvorak.map.gz" \
"usr/share/keymaps/sun/sunt5-fr-latin1.map.gz" "%{_datadir}/keymaps/sun/sunt5-fr-latin1.map.gz" \
"usr/share/keymaps/sun/sunt5-uk.map.gz" "%{_datadir}/keymaps/sun/sunt5-uk.map.gz" \
"usr/share/keymaps/sun/sunt4-es.map.gz" "%{_datadir}/keymaps/sun/sunt4-es.map.gz" \
"usr/share/keymaps/sun/sunt5-ru.map.gz" "%{_datadir}/keymaps/sun/sunt5-ru.map.gz" \
"usr/share/keymaps/sun/sunt5-de-latin1.map.gz" "%{_datadir}/keymaps/sun/sunt5-de-latin1.map.gz" \
"usr/share/keymaps/sun/sunt6-uk.map.gz" "%{_datadir}/keymaps/sun/sunt6-uk.map.gz" \
"usr/share/keymaps/sun/sunt5-us-cz.map.gz" "%{_datadir}/keymaps/sun/sunt5-us-cz.map.gz" \
"usr/share/keymaps/sun/sunkeymap.map.gz" "%{_datadir}/keymaps/sun/sunkeymap.map.gz" \
"usr/share/keymaps/mac/all/mac-pt-latin1.map.gz" "%{_datadir}/keymaps/mac/all/mac-pt-latin1.map.gz" \
"usr/share/keymaps/mac/all/apple-internal-0x0253-sv-fn-reverse.map.gz" "%{_datadir}/keymaps/mac/all/apple-internal-0x0253-sv-fn-reverse.map.gz" \
"usr/share/keymaps/mac/all/mac-uk.map.gz" "%{_datadir}/keymaps/mac/all/mac-uk.map.gz" \
"usr/share/keymaps/mac/all/mac-se.map.gz" "%{_datadir}/keymaps/mac/all/mac-se.map.gz" \
"usr/share/keymaps/mac/all/mac-es.map.gz" "%{_datadir}/keymaps/mac/all/mac-es.map.gz" \
"usr/share/keymaps/mac/all/mac-pl.map.gz" "%{_datadir}/keymaps/mac/all/mac-pl.map.gz" \
"usr/share/keymaps/mac/all/mac-dvorak.map.gz" "%{_datadir}/keymaps/mac/all/mac-dvorak.map.gz" \
"usr/share/keymaps/mac/all/mac-fr_CH-latin1.map.gz" "%{_datadir}/keymaps/mac/all/mac-fr_CH-latin1.map.gz" \
"usr/share/keymaps/mac/all/apple-a1243-sv-fn-reverse.map.gz" "%{_datadir}/keymaps/mac/all/apple-a1243-sv-fn-reverse.map.gz" \
"usr/share/keymaps/mac/all/mac-fr.map.gz" "%{_datadir}/keymaps/mac/all/mac-fr.map.gz" \
"usr/share/keymaps/mac/all/mac-template.map.gz" "%{_datadir}/keymaps/mac/all/mac-template.map.gz" \
"usr/share/keymaps/mac/all/apple-a1048-sv.map.gz" "%{_datadir}/keymaps/mac/all/apple-a1048-sv.map.gz" \
"usr/share/keymaps/mac/all/apple-a1243-sv.map.gz" "%{_datadir}/keymaps/mac/all/apple-a1243-sv.map.gz" \
"usr/share/keymaps/mac/all/mac-de-latin1-nodeadkeys.map.gz" "%{_datadir}/keymaps/mac/all/mac-de-latin1-nodeadkeys.map.gz" \
"usr/share/keymaps/mac/all/mac-dk-latin1.map.gz" "%{_datadir}/keymaps/mac/all/mac-dk-latin1.map.gz" \
"usr/share/keymaps/mac/all/mac-de_CH.map.gz" "%{_datadir}/keymaps/mac/all/mac-de_CH.map.gz" \
"usr/share/keymaps/mac/all/mac-us.map.gz" "%{_datadir}/keymaps/mac/all/mac-us.map.gz" \
"usr/share/keymaps/mac/all/mac-fi-latin1.map.gz" "%{_datadir}/keymaps/mac/all/mac-fi-latin1.map.gz" \
"usr/share/keymaps/mac/all/mac-no-latin1.map.gz" "%{_datadir}/keymaps/mac/all/mac-no-latin1.map.gz" \
"usr/share/keymaps/mac/all/mac-fr-legacy.map.gz" "%{_datadir}/keymaps/mac/all/mac-fr-legacy.map.gz" \
"usr/share/keymaps/mac/all/mac-it.map.gz" "%{_datadir}/keymaps/mac/all/mac-it.map.gz" \
"usr/share/keymaps/mac/all/mac-de-latin1.map.gz" "%{_datadir}/keymaps/mac/all/mac-de-latin1.map.gz" \
"usr/share/keymaps/mac/all/mac-be.map.gz" "%{_datadir}/keymaps/mac/all/mac-be.map.gz" \
"usr/share/keymaps/mac/all/apple-internal-0x0253-sv.map.gz" "%{_datadir}/keymaps/mac/all/apple-internal-0x0253-sv.map.gz" \
"usr/share/keymaps/mac/include/mac-euro2.map.gz" "%{_datadir}/keymaps/mac/include/mac-euro2.map.gz" \
"usr/share/keymaps/mac/include/apple-a1048-base.inc" "%{_datadir}/keymaps/mac/include/apple-a1048-base.inc" \
"usr/share/keymaps/mac/include/mac-azerty-layout.inc" "%{_datadir}/keymaps/mac/include/mac-azerty-layout.inc" \
"usr/share/keymaps/mac/include/mac-linux-keys-bare.inc" "%{_datadir}/keymaps/mac/include/mac-linux-keys-bare.inc" \
"usr/share/keymaps/mac/include/mac-qwertz-layout.inc" "%{_datadir}/keymaps/mac/include/mac-qwertz-layout.inc" \
"usr/share/keymaps/mac/include/mac-qwerty-layout.inc" "%{_datadir}/keymaps/mac/include/mac-qwerty-layout.inc" \
"usr/share/keymaps/mac/include/apple-a1243-fn-reverse.inc" "%{_datadir}/keymaps/mac/include/apple-a1243-fn-reverse.inc" \
"usr/share/keymaps/mac/include/mac-euro.map.gz" "%{_datadir}/keymaps/mac/include/mac-euro.map.gz" \
"usr/share/keymaps/mac/include/apple-a1243-fn.inc" "%{_datadir}/keymaps/mac/include/apple-a1243-fn.inc" \
"usr/share/keymaps/i386/carpalx/carpalx-full.map.gz" "%{_datadir}/keymaps/i386/carpalx/carpalx-full.map.gz" \
"usr/share/keymaps/i386/carpalx/carpalx.map.gz" "%{_datadir}/keymaps/i386/carpalx/carpalx.map.gz" \
"usr/share/keymaps/i386/bepo/fr-bepo-latin9.map.gz" "%{_datadir}/keymaps/i386/bepo/fr-bepo-latin9.map.gz" \
"usr/share/keymaps/i386/bepo/fr-bepo.map.gz" "%{_datadir}/keymaps/i386/bepo/fr-bepo.map.gz" \
"usr/share/keymaps/i386/qwerty/no-latin1.map.gz" "%{_datadir}/keymaps/i386/qwerty/no-latin1.map.gz" \
"usr/share/keymaps/i386/qwerty/ttwin_ctrl-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ttwin_ctrl-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_ctrl-KOI8-R.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_ctrl-KOI8-R.map.gz" \
"usr/share/keymaps/i386/qwerty/uk.map.gz" "%{_datadir}/keymaps/i386/qwerty/uk.map.gz" \
"usr/share/keymaps/i386/qwerty/cz-lat2-prog.map.gz" "%{_datadir}/keymaps/i386/qwerty/cz-lat2-prog.map.gz" \
"usr/share/keymaps/i386/qwerty/nl.map.gz" "%{_datadir}/keymaps/i386/qwerty/nl.map.gz" \
"usr/share/keymaps/i386/qwerty/emacs2.map.gz" "%{_datadir}/keymaps/i386/qwerty/emacs2.map.gz" \
"usr/share/keymaps/i386/qwerty/fa.map.gz" "%{_datadir}/keymaps/i386/qwerty/fa.map.gz" \
"usr/share/keymaps/i386/qwerty/se-lat6.map.gz" "%{_datadir}/keymaps/i386/qwerty/se-lat6.map.gz" \
"usr/share/keymaps/i386/qwerty/it-ibm.map.gz" "%{_datadir}/keymaps/i386/qwerty/it-ibm.map.gz" \
"usr/share/keymaps/i386/qwerty/es.map.gz" "%{_datadir}/keymaps/i386/qwerty/es.map.gz" \
"usr/share/keymaps/i386/qwerty/ttwin_ct_sh-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ttwin_ct_sh-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/mk-utf.map.gz" "%{_datadir}/keymaps/i386/qwerty/mk-utf.map.gz" \
"usr/share/keymaps/i386/qwerty/bg-cp855.map.gz" "%{_datadir}/keymaps/i386/qwerty/bg-cp855.map.gz" \
"usr/share/keymaps/i386/qwerty/br-latin1-us.map.gz" "%{_datadir}/keymaps/i386/qwerty/br-latin1-us.map.gz" \
"usr/share/keymaps/i386/qwerty/sr-cy.map.gz" "%{_datadir}/keymaps/i386/qwerty/sr-cy.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_cplk-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_cplk-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/cf.map.gz" "%{_datadir}/keymaps/i386/qwerty/cf.map.gz" \
"usr/share/keymaps/i386/qwerty/gr-pc.map.gz" "%{_datadir}/keymaps/i386/qwerty/gr-pc.map.gz" \
"usr/share/keymaps/i386/qwerty/cz.map.gz" "%{_datadir}/keymaps/i386/qwerty/cz.map.gz" \
"usr/share/keymaps/i386/qwerty/ua-ws.map.gz" "%{_datadir}/keymaps/i386/qwerty/ua-ws.map.gz" \
"usr/share/keymaps/i386/qwerty/cz-lat2.map.gz" "%{_datadir}/keymaps/i386/qwerty/cz-lat2.map.gz" \
"usr/share/keymaps/i386/qwerty/us1.map.gz" "%{_datadir}/keymaps/i386/qwerty/us1.map.gz" \
"usr/share/keymaps/i386/qwerty/by-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/by-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/it.map.gz" "%{_datadir}/keymaps/i386/qwerty/it.map.gz" \
"usr/share/keymaps/i386/qwerty/pl3.map.gz" "%{_datadir}/keymaps/i386/qwerty/pl3.map.gz" \
"usr/share/keymaps/i386/qwerty/dk-latin1.map.gz" "%{_datadir}/keymaps/i386/qwerty/dk-latin1.map.gz" \
"usr/share/keymaps/i386/qwerty/ua-utf-ws.map.gz" "%{_datadir}/keymaps/i386/qwerty/ua-utf-ws.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_cplk-CP1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_cplk-CP1251.map.gz" \
"usr/share/keymaps/i386/qwerty/lv-tilde.map.gz" "%{_datadir}/keymaps/i386/qwerty/lv-tilde.map.gz" \
"usr/share/keymaps/i386/qwerty/il-phonetic.map.gz" "%{_datadir}/keymaps/i386/qwerty/il-phonetic.map.gz" \
"usr/share/keymaps/i386/qwerty/kyrgyz.map.gz" "%{_datadir}/keymaps/i386/qwerty/kyrgyz.map.gz" \
"usr/share/keymaps/i386/qwerty/tj_alt-UTF8.map.gz" "%{_datadir}/keymaps/i386/qwerty/tj_alt-UTF8.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_cplk-KOI8-R.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_cplk-KOI8-R.map.gz" \
"usr/share/keymaps/i386/qwerty/by.map.gz" "%{_datadir}/keymaps/i386/qwerty/by.map.gz" \
"usr/share/keymaps/i386/qwerty/ru2.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru2.map.gz" \
"usr/share/keymaps/i386/qwerty/ru3.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru3.map.gz" \
"usr/share/keymaps/i386/qwerty/bg-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/bg-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/ru-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/tr_q-latin5.map.gz" "%{_datadir}/keymaps/i386/qwerty/tr_q-latin5.map.gz" \
"usr/share/keymaps/i386/qwerty/ro_std.map.gz" "%{_datadir}/keymaps/i386/qwerty/ro_std.map.gz" \
"usr/share/keymaps/i386/qwerty/is-latin1-us.map.gz" "%{_datadir}/keymaps/i386/qwerty/is-latin1-us.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_ct_sh-CP1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_ct_sh-CP1251.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_ctrl-CP1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_ctrl-CP1251.map.gz" \
"usr/share/keymaps/i386/qwerty/lt.l4.map.gz" "%{_datadir}/keymaps/i386/qwerty/lt.l4.map.gz" \
"usr/share/keymaps/i386/qwerty/ua-utf.map.gz" "%{_datadir}/keymaps/i386/qwerty/ua-utf.map.gz" \
"usr/share/keymaps/i386/qwerty/tralt.map.gz" "%{_datadir}/keymaps/i386/qwerty/tralt.map.gz" \
"usr/share/keymaps/i386/qwerty/trf.map.gz" "%{_datadir}/keymaps/i386/qwerty/trf.map.gz" \
"usr/share/keymaps/i386/qwerty/mk0.map.gz" "%{_datadir}/keymaps/i386/qwerty/mk0.map.gz" \
"usr/share/keymaps/i386/qwerty/ru-yawerty.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru-yawerty.map.gz" \
"usr/share/keymaps/i386/qwerty/defkeymap.map.gz" "%{_datadir}/keymaps/i386/qwerty/defkeymap.map.gz" \
"usr/share/keymaps/i386/qwerty/bashkir.map.gz" "%{_datadir}/keymaps/i386/qwerty/bashkir.map.gz" \
"usr/share/keymaps/i386/qwerty/hypermap.m4" "%{_datadir}/keymaps/i386/qwerty/hypermap.m4" \
"usr/share/keymaps/i386/qwerty/trq.map.gz" "%{_datadir}/keymaps/i386/qwerty/trq.map.gz" \
"usr/share/keymaps/i386/qwerty/nl2.map.gz" "%{_datadir}/keymaps/i386/qwerty/nl2.map.gz" \
"usr/share/keymaps/i386/qwerty/bg_bds-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/bg_bds-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/kazakh.map.gz" "%{_datadir}/keymaps/i386/qwerty/kazakh.map.gz" \
"usr/share/keymaps/i386/qwerty/mk.map.gz" "%{_datadir}/keymaps/i386/qwerty/mk.map.gz" \
"usr/share/keymaps/i386/qwerty/pt-latin1.map.gz" "%{_datadir}/keymaps/i386/qwerty/pt-latin1.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_alt_sh-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_alt_sh-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/pl2.map.gz" "%{_datadir}/keymaps/i386/qwerty/pl2.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_ct_sh-KOI8-R.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_ct_sh-KOI8-R.map.gz" \
"usr/share/keymaps/i386/qwerty/ky_alt_sh-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ky_alt_sh-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/is-latin1.map.gz" "%{_datadir}/keymaps/i386/qwerty/is-latin1.map.gz" \
"usr/share/keymaps/i386/qwerty/es-cp850.map.gz" "%{_datadir}/keymaps/i386/qwerty/es-cp850.map.gz" \
"usr/share/keymaps/i386/qwerty/pl4.map.gz" "%{_datadir}/keymaps/i386/qwerty/pl4.map.gz" \
"usr/share/keymaps/i386/qwerty/ru4.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru4.map.gz" \
"usr/share/keymaps/i386/qwerty/ua.map.gz" "%{_datadir}/keymaps/i386/qwerty/ua.map.gz" \
"usr/share/keymaps/i386/qwerty/hu101.map.gz" "%{_datadir}/keymaps/i386/qwerty/hu101.map.gz" \
"usr/share/keymaps/i386/qwerty/bg_pho-utf8.map.gz" "%{_datadir}/keymaps/i386/qwerty/bg_pho-utf8.map.gz" \
"usr/share/keymaps/i386/qwerty/ttwin_cplk-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ttwin_cplk-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/bg_pho-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/bg_pho-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/us.map.gz" "%{_datadir}/keymaps/i386/qwerty/us.map.gz" \
"usr/share/keymaps/i386/qwerty/pt-latin9.map.gz" "%{_datadir}/keymaps/i386/qwerty/pt-latin9.map.gz" \
"usr/share/keymaps/i386/qwerty/br-abnt2.map.gz" "%{_datadir}/keymaps/i386/qwerty/br-abnt2.map.gz" \
"usr/share/keymaps/i386/qwerty/no.map.gz" "%{_datadir}/keymaps/i386/qwerty/no.map.gz" \
"usr/share/keymaps/i386/qwerty/defkeymap_V1.0.map.gz" "%{_datadir}/keymaps/i386/qwerty/defkeymap_V1.0.map.gz" \
"usr/share/keymaps/i386/qwerty/br-latin1-abnt2.map.gz" "%{_datadir}/keymaps/i386/qwerty/br-latin1-abnt2.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_alt-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_alt-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/il.map.gz" "%{_datadir}/keymaps/i386/qwerty/il.map.gz" \
"usr/share/keymaps/i386/qwerty/ru1.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru1.map.gz" \
"usr/share/keymaps/i386/qwerty/sv-latin1.map.gz" "%{_datadir}/keymaps/i386/qwerty/sv-latin1.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_ctrl-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_ctrl-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/fi.map.gz" "%{_datadir}/keymaps/i386/qwerty/fi.map.gz" \
"usr/share/keymaps/i386/qwerty/cz-cp1250.map.gz" "%{_datadir}/keymaps/i386/qwerty/cz-cp1250.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_alt-CP1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_alt-CP1251.map.gz" \
"usr/share/keymaps/i386/qwerty/sk-qwerty.map.gz" "%{_datadir}/keymaps/i386/qwerty/sk-qwerty.map.gz" \
"usr/share/keymaps/i386/qwerty/ru-ms.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru-ms.map.gz" \
"usr/share/keymaps/i386/qwerty/se-ir209.map.gz" "%{_datadir}/keymaps/i386/qwerty/se-ir209.map.gz" \
"usr/share/keymaps/i386/qwerty/dk.map.gz" "%{_datadir}/keymaps/i386/qwerty/dk.map.gz" \
"usr/share/keymaps/i386/qwerty/br-abnt.map.gz" "%{_datadir}/keymaps/i386/qwerty/br-abnt.map.gz" \
"usr/share/keymaps/i386/qwerty/ua-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/ua-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/et-nodeadkeys.map.gz" "%{_datadir}/keymaps/i386/qwerty/et-nodeadkeys.map.gz" \
"usr/share/keymaps/i386/qwerty/lt.map.gz" "%{_datadir}/keymaps/i386/qwerty/lt.map.gz" \
"usr/share/keymaps/i386/qwerty/il-heb.map.gz" "%{_datadir}/keymaps/i386/qwerty/il-heb.map.gz" \
"usr/share/keymaps/i386/qwerty/emacs.map.gz" "%{_datadir}/keymaps/i386/qwerty/emacs.map.gz" \
"usr/share/keymaps/i386/qwerty/gr.map.gz" "%{_datadir}/keymaps/i386/qwerty/gr.map.gz" \
"usr/share/keymaps/i386/qwerty/ro.map.gz" "%{_datadir}/keymaps/i386/qwerty/ro.map.gz" \
"usr/share/keymaps/i386/qwerty/et.map.gz" "%{_datadir}/keymaps/i386/qwerty/et.map.gz" \
"usr/share/keymaps/i386/qwerty/bywin-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/bywin-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/lv.map.gz" "%{_datadir}/keymaps/i386/qwerty/lv.map.gz" \
"usr/share/keymaps/i386/qwerty/se-fi-lat6.map.gz" "%{_datadir}/keymaps/i386/qwerty/se-fi-lat6.map.gz" \
"usr/share/keymaps/i386/qwerty/la-latin1.map.gz" "%{_datadir}/keymaps/i386/qwerty/la-latin1.map.gz" \
"usr/share/keymaps/i386/qwerty/ca.map.gz" "%{_datadir}/keymaps/i386/qwerty/ca.map.gz" \
"usr/share/keymaps/i386/qwerty/ttwin_alt-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ttwin_alt-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/ro_win.map.gz" "%{_datadir}/keymaps/i386/qwerty/ro_win.map.gz" \
"usr/share/keymaps/i386/qwerty/mk-cp1251.map.gz" "%{_datadir}/keymaps/i386/qwerty/mk-cp1251.map.gz" \
"usr/share/keymaps/i386/qwerty/pc110.map.gz" "%{_datadir}/keymaps/i386/qwerty/pc110.map.gz" \
"usr/share/keymaps/i386/qwerty/ru.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru.map.gz" \
"usr/share/keymaps/i386/qwerty/ie.map.gz" "%{_datadir}/keymaps/i386/qwerty/ie.map.gz" \
"usr/share/keymaps/i386/qwerty/bg_bds-utf8.map.gz" "%{_datadir}/keymaps/i386/qwerty/bg_bds-utf8.map.gz" \
"usr/share/keymaps/i386/qwerty/ru_win.map.gz" "%{_datadir}/keymaps/i386/qwerty/ru_win.map.gz" \
"usr/share/keymaps/i386/qwerty/se-fi-ir209.map.gz" "%{_datadir}/keymaps/i386/qwerty/se-fi-ir209.map.gz" \
"usr/share/keymaps/i386/qwerty/pl1.map.gz" "%{_datadir}/keymaps/i386/qwerty/pl1.map.gz" \
"usr/share/keymaps/i386/qwerty/jp106.map.gz" "%{_datadir}/keymaps/i386/qwerty/jp106.map.gz" \
"usr/share/keymaps/i386/qwerty/lt.baltic.map.gz" "%{_datadir}/keymaps/i386/qwerty/lt.baltic.map.gz" \
"usr/share/keymaps/i386/qwerty/sk-prog-qwerty.map.gz" "%{_datadir}/keymaps/i386/qwerty/sk-prog-qwerty.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_ct_sh-UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_ct_sh-UTF-8.map.gz" \
"usr/share/keymaps/i386/qwerty/it2.map.gz" "%{_datadir}/keymaps/i386/qwerty/it2.map.gz" \
"usr/share/keymaps/i386/qwerty/ruwin_alt-KOI8-R.map.gz" "%{_datadir}/keymaps/i386/qwerty/ruwin_alt-KOI8-R.map.gz" \
"usr/share/keymaps/i386/qwerty/no-latin1.doc" "%{_datadir}/keymaps/i386/qwerty/no-latin1.doc" \
"usr/share/keymaps/i386/qwerty/pl.map.gz" "%{_datadir}/keymaps/i386/qwerty/pl.map.gz" \
"usr/share/keymaps/i386/qwerty/us-acentos.map.gz" "%{_datadir}/keymaps/i386/qwerty/us-acentos.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-r.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-r.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-ca-fr.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-ca-fr.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-es.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-es.map.gz" \
"usr/share/keymaps/i386/dvorak/ANSI-dvorak.map.gz" "%{_datadir}/keymaps/i386/dvorak/ANSI-dvorak.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-fr.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-fr.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-ru.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-ru.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-ukp.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-ukp.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-programmer.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-programmer.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-sv-a1.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-sv-a1.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-l.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-l.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-de.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-de.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-uk.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-uk.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-no.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-no.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-la.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-la.map.gz" \
"usr/share/keymaps/i386/dvorak/dvorak-sv-a5.map.gz" "%{_datadir}/keymaps/i386/dvorak/dvorak-sv-a5.map.gz" \
"usr/share/keymaps/i386/include/euro.map.gz" "%{_datadir}/keymaps/i386/include/euro.map.gz" \
"usr/share/keymaps/i386/include/backspace.map.gz" "%{_datadir}/keymaps/i386/include/backspace.map.gz" \
"usr/share/keymaps/i386/include/linux-keys-extd.inc" "%{_datadir}/keymaps/i386/include/linux-keys-extd.inc" \
"usr/share/keymaps/i386/include/qwertz-layout.inc" "%{_datadir}/keymaps/i386/include/qwertz-layout.inc" \
"usr/share/keymaps/i386/include/linux-with-alt-and-altgr.inc" "%{_datadir}/keymaps/i386/include/linux-with-alt-and-altgr.inc" \
"usr/share/keymaps/i386/include/applkey.map.gz" "%{_datadir}/keymaps/i386/include/applkey.map.gz" \
"usr/share/keymaps/i386/include/euro2.map.gz" "%{_datadir}/keymaps/i386/include/euro2.map.gz" \
"usr/share/keymaps/i386/include/linux-with-two-alt-keys.inc" "%{_datadir}/keymaps/i386/include/linux-with-two-alt-keys.inc" \
"usr/share/keymaps/i386/include/linux-with-modeshift-altgr.inc" "%{_datadir}/keymaps/i386/include/linux-with-modeshift-altgr.inc" \
"usr/share/keymaps/i386/include/azerty-layout.inc" "%{_datadir}/keymaps/i386/include/azerty-layout.inc" \
"usr/share/keymaps/i386/include/euro1.map.gz" "%{_datadir}/keymaps/i386/include/euro1.map.gz" \
"usr/share/keymaps/i386/include/ctrl.map.gz" "%{_datadir}/keymaps/i386/include/ctrl.map.gz" \
"usr/share/keymaps/i386/include/keypad.map.gz" "%{_datadir}/keymaps/i386/include/keypad.map.gz" \
"usr/share/keymaps/i386/include/compose.inc" "%{_datadir}/keymaps/i386/include/compose.inc" \
"usr/share/keymaps/i386/include/windowkeys.map.gz" "%{_datadir}/keymaps/i386/include/windowkeys.map.gz" \
"usr/share/keymaps/i386/include/unicode.map.gz" "%{_datadir}/keymaps/i386/include/unicode.map.gz" \
"usr/share/keymaps/i386/include/linux-keys-bare.inc" "%{_datadir}/keymaps/i386/include/linux-keys-bare.inc" \
"usr/share/keymaps/i386/include/euro1.inc" "%{_datadir}/keymaps/i386/include/euro1.inc" \
"usr/share/keymaps/i386/include/qwerty-layout.inc" "%{_datadir}/keymaps/i386/include/qwerty-layout.inc" \
"usr/share/keymaps/i386/colemak/mod-dh-ansi-us-fatz-wide.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-ansi-us-fatz-wide.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-iso-us-wide.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-iso-us-wide.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-iso-us.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-iso-us.map.gz" \
"usr/share/keymaps/i386/colemak/en-latin9.map.gz" "%{_datadir}/keymaps/i386/colemak/en-latin9.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-iso-uk-wide.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-iso-uk-wide.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-ansi-us-fatz.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-ansi-us-fatz.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-ansi-us-awing.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-ansi-us-awing.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-matrix-us.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-matrix-us.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-ansi-us-wide.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-ansi-us-wide.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-ansi-us.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-ansi-us.map.gz" \
"usr/share/keymaps/i386/colemak/mod-dh-iso-uk.map.gz" "%{_datadir}/keymaps/i386/colemak/mod-dh-iso-uk.map.gz" \
"usr/share/keymaps/i386/qwertz/de.map.gz" "%{_datadir}/keymaps/i386/qwertz/de.map.gz" \
"usr/share/keymaps/i386/qwertz/fr_CH.map.gz" "%{_datadir}/keymaps/i386/qwertz/fr_CH.map.gz" \
"usr/share/keymaps/i386/qwertz/cz.map.gz" "%{_datadir}/keymaps/i386/qwertz/cz.map.gz" \
"usr/share/keymaps/i386/qwertz/sk-prog-qwertz.map.gz" "%{_datadir}/keymaps/i386/qwertz/sk-prog-qwertz.map.gz" \
"usr/share/keymaps/i386/qwertz/slovene.map.gz" "%{_datadir}/keymaps/i386/qwertz/slovene.map.gz" \
"usr/share/keymaps/i386/qwertz/de-latin1-nodeadkeys.map.gz" "%{_datadir}/keymaps/i386/qwertz/de-latin1-nodeadkeys.map.gz" \
"usr/share/keymaps/i386/qwertz/fr_CH-latin1.map.gz" "%{_datadir}/keymaps/i386/qwertz/fr_CH-latin1.map.gz" \
"usr/share/keymaps/i386/qwertz/croat.map.gz" "%{_datadir}/keymaps/i386/qwertz/croat.map.gz" \
"usr/share/keymaps/i386/qwertz/de_CH-latin1.map.gz" "%{_datadir}/keymaps/i386/qwertz/de_CH-latin1.map.gz" \
"usr/share/keymaps/i386/qwertz/sg-latin1.map.gz" "%{_datadir}/keymaps/i386/qwertz/sg-latin1.map.gz" \
"usr/share/keymaps/i386/qwertz/sg-latin1-lk450.map.gz" "%{_datadir}/keymaps/i386/qwertz/sg-latin1-lk450.map.gz" \
"usr/share/keymaps/i386/qwertz/de_alt_UTF-8.map.gz" "%{_datadir}/keymaps/i386/qwertz/de_alt_UTF-8.map.gz" \
"usr/share/keymaps/i386/qwertz/sr-latin.map.gz" "%{_datadir}/keymaps/i386/qwertz/sr-latin.map.gz" \
"usr/share/keymaps/i386/qwertz/sk-qwertz.map.gz" "%{_datadir}/keymaps/i386/qwertz/sk-qwertz.map.gz" \
"usr/share/keymaps/i386/qwertz/cz-us-qwertz.map.gz" "%{_datadir}/keymaps/i386/qwertz/cz-us-qwertz.map.gz" \
"usr/share/keymaps/i386/qwertz/sg.map.gz" "%{_datadir}/keymaps/i386/qwertz/sg.map.gz" \
"usr/share/keymaps/i386/qwertz/de-latin1.map.gz" "%{_datadir}/keymaps/i386/qwertz/de-latin1.map.gz" \
"usr/share/keymaps/i386/qwertz/de-mobii.map.gz" "%{_datadir}/keymaps/i386/qwertz/de-mobii.map.gz" \
"usr/share/keymaps/i386/qwertz/hu.map.gz" "%{_datadir}/keymaps/i386/qwertz/hu.map.gz" \
"usr/share/keymaps/i386/neo/koy.map.gz" "%{_datadir}/keymaps/i386/neo/koy.map.gz" \
"usr/share/keymaps/i386/neo/bone.map.gz" "%{_datadir}/keymaps/i386/neo/bone.map.gz" \
"usr/share/keymaps/i386/neo/adnw.map.gz" "%{_datadir}/keymaps/i386/neo/adnw.map.gz" \
"usr/share/keymaps/i386/neo/neoqwertz.map.gz" "%{_datadir}/keymaps/i386/neo/neoqwertz.map.gz" \
"usr/share/keymaps/i386/neo/neo.map.gz" "%{_datadir}/keymaps/i386/neo/neo.map.gz" \
"usr/share/keymaps/i386/neo/README.md" "%{_datadir}/keymaps/i386/neo/README.md" \
"usr/share/keymaps/i386/neo/3l.map.gz" "%{_datadir}/keymaps/i386/neo/3l.map.gz" \
"usr/share/keymaps/i386/fgGIod/tr_f-latin5.map.gz" "%{_datadir}/keymaps/i386/fgGIod/tr_f-latin5.map.gz" \
"usr/share/keymaps/i386/fgGIod/trf.map.gz" "%{_datadir}/keymaps/i386/fgGIod/trf.map.gz" \
"usr/share/keymaps/i386/olpc/es.map.gz" "%{_datadir}/keymaps/i386/olpc/es.map.gz" \
"usr/share/keymaps/i386/olpc/pt.map.gz" "%{_datadir}/keymaps/i386/olpc/pt.map.gz" \
"usr/share/keymaps/i386/azerty/wangbe.map.gz" "%{_datadir}/keymaps/i386/azerty/wangbe.map.gz" \
"usr/share/keymaps/i386/azerty/wangbe2.map.gz" "%{_datadir}/keymaps/i386/azerty/wangbe2.map.gz" \
"usr/share/keymaps/i386/azerty/be-latin1.map.gz" "%{_datadir}/keymaps/i386/azerty/be-latin1.map.gz" \
"usr/share/keymaps/i386/azerty/fr-latin1.map.gz" "%{_datadir}/keymaps/i386/azerty/fr-latin1.map.gz" \
"usr/share/keymaps/i386/azerty/fr.map.gz" "%{_datadir}/keymaps/i386/azerty/fr.map.gz" \
"usr/share/keymaps/i386/azerty/fr-pc.map.gz" "%{_datadir}/keymaps/i386/azerty/fr-pc.map.gz" \
"usr/share/keymaps/i386/azerty/fr-latin9.map.gz" "%{_datadir}/keymaps/i386/azerty/fr-latin9.map.gz" \
"usr/share/keymaps/i386/azerty/azerty.map.gz" "%{_datadir}/keymaps/i386/azerty/azerty.map.gz"
