#!/bin/bash

FINDUTILS_SRC=$CACHE/findutils
FINDUTILS_RPM_NAME=FindUtils
FINDUTILS_VERSION="4.10.0"
FINDUTILS_FULLNAME=${FINDUTILS_RPM_NAME}-${FINDUTILS_VERSION}
$ROOT/download_and_untar.sh "https://ftp.gnu.org/gnu/findutils/findutils-4.10.0.tar.xz" "$FINDUTILS_SRC"

if [ ! -d $FINDUTILS_SRC/build ]
then
  mkdir -p $FINDUTILS_SRC/build
  cd $FINDUTILS_SRC/build
  ../configure --prefix=/usr --build=$(../build-aux/config.guess) --host=$TARGET
  make -j$(nproc)
fi
cd $FINDUTILS_SRC/build
#make DESTDIR=$ISO_SYSROOT install
$ROOT/generate_tar.sh make $FINDUTILS_SRC/build/$FINDUTILS_FULLNAME.tar $FINDUTILS_FULLNAME \
                      usr/bin/{find,locate,updatedb,xargs} \
                      usr/libexec/frcode

cd $FINDUTILS_SRC/build
$ROOT/generate_rpm.sh "$ISO_RPMS" \
                      "$FINDUTILS_SRC/build/rpmbuild" \
                      "$FINDUTILS_RPM_NAME" \
                      "$FINDUTILS_VERSION" \
                      "The GNU Find Utilities are the basic directory searching utilities of the GNU operating system. These programs are typically used in conjunction with other programs to provide modular and powerful directory search and file locating capabilities to other commands." \
                      "The find program searches a directory tree to find a file or group of files. It traverses the directory tree and reports all occurrences of a file matching the user's specifications. The find program includes very powerful searching capability.\nThe locate program scans one or more databases of filenames and displays any matches. This can be used as a very fast find command if the file was present during the last file name database update.\nThe updatedb program updates the file name database used by the locate program. The file name database contains lists of files that were in particular directory trees when the databases were last updated. This is usually run nightly by the cron system daemon.\nThe xargs program builds and executes command lines by gathering together arguments it reads on the standard input. Most often, these arguments are lists of file names generated by find." \
                      "GPL" \
                      "$FINDUTILS_SRC/build/$FINDUTILS_FULLNAME.tar" \
                      "usr/bin/find" "%{_bindir}/find" \
                      "usr/bin/locate" "%{_bindir}/locate" \
                      "usr/bin/updatedb" "%{_bindir}/updatedb" \
                      "usr/bin/xargs" "%{_bindir}/xargs" \
                      "usr/libexec/frcode" "%{_libexecdir}/frcode"
