#!/bin/bash

GRUB_SRC=$CACHE/grub
GRUB_RPM_NAME=Grub
GRUB_VERSION="2.12"
GRUB_FULLNAME=$GRUB_RPM_NAME-$GRUB_VERSION

$ROOT/download_and_untar.sh "https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz" "$GRUB_SRC"

if [ ! -d $GRUB_SRC/build ]
then
  mkdir -p $GRUB_SRC/build
  cd $GRUB_SRC/build
  ../configure --prefix=/usr \
                --sysconfdir=/etc \
                --build=$(../build-aux/config.guess) \
                --host=$TARGET \
                --target=$TARGET
  touch ../grub-core/extra_deps.lst
  make -j$(nproc)
fi
cd $GRUB_SRC/build
#make DESTDIR=$ISO_SYSROOT install

$ROOT/generate_tar.sh make $GRUB_SRC/build/$GRUB_FULLNAME.tar $GRUB_FULLNAME \
                      etc/bash_completion.d/grub \
                      etc/grub.d/{41_custom,20_linux_xen,README,10_linux,25_bli,00_header,30_uefi-firmware,30_os-prober,40_custom} \
                      usr/bin/{grub-mkrelpath,grub-fstest,grub-mkpasswd-pbkdf2,grub-menulst2cfg,grub-render-label,grub-mkrescue,grub-mklayout,grub-mkstandalone,grub-editenv,grub-script-check,grub-glue-efi,grub-mknetdir,grub-file,grub-mkimage,grub-kbdcomp,grub-syslinux2cfg} \
                      usr/lib/grub/i386-pc/{pxechain.module,acpi.module,adler32.module,gcry_sha1.module,echo.module,font.mod,part_msdos.mod,ldm.mod,gcry_md4.module,scsi.mod,bswap_test.mod,fshelp.module,part_sunpc.mod,linux16.mod,minix2.mod,zstd.module,macho.module,vga.mod,hashsum.module,tar.module,gcry_blowfish.mod,ext2.module,btrfs.mod,morse.mod,backtrace.module,gcry_cast5.mod,cmp_test.mod,odc.mod,shift_test.mod,part_dfly.mod,net.mod,keylayouts.module,lvm.mod,testspeed.module,part_bsd.mod,time.module,gzio.module,cpio.mod,cbtime.module,nilfs2.mod,video_colors.module,loadenv.mod,search_fs_uuid.mod,configfile.mod,lzopio.mod,diskfilter.mod,afsplitter.module,video_cirrus.module,jfs.mod,legacy_password_test.module,squash4.mod,raid5rec.module,elf.mod,mdraid09.mod,gcry_seed.module,iso9660.mod,offsetio.mod,cbls.module,cpio.module,archelp.mod,lsmmap.module,cpuid.mod,all_video.module,newc.mod,http.mod,mdraid09_be.mod,mpi.mod,xzio.mod,strtoull_test.mod,mdraid09_be.module,minix3_be.module,password_pbkdf2.mod,video_fb.module,f2fs.mod,minix_be.module,json.module,cbls.mod,video_fb.mod,gcry_tiger.mod,crypto.lst,smbios.module,memrw.mod,usbserial_common.mod,gptsync.module,offsetio.module,hfsplus.module,truecrypt.module,aout.module,ntfscomp.mod,mpi.module,spkmodem.module,regexp.mod,gettext.module,sleep_test.module,pbkdf2.mod,usb_keyboard.module,pcidump.mod,pci.module,probe.mod,div.module,backtrace.mod,uhci.mod,ahci.mod,search_fs_file.module,zfs.module,freedos.mod,gcry_whirlpool.module,cbtime.mod,usbtest.mod,legacycfg.mod,geli.mod,videotest.mod,sendkey.mod,videotest_checksum.mod,pxe.module,affs.module,gcry_md4.mod,luks.mod,dm_nv.module,iso9660.module,hfsplus.mod,gcry_md5.module,f2fs.module,setpci.module,video.module,extcmd.mod,gcry_serpent.mod,procfs.module,usb.mod,gcry_rfc2268.mod,true.module,archelp.module,crypto.module,gfxmenu.mod,cryptodisk.mod,tr.mod,cat.module,raid5rec.mod,cryptodisk.module,shift_test.module,gzio.mod,efiemu.mod,biosdisk.module,progress.module,raid6rec.module,cdboot.image,scsi.module,usbserial_usbdebug.mod,pbkdf2_test.mod,mda_text.module,bsd.module,gdb.module,play.mod,part_msdos.module,ehci.module,div_test.mod,sfs.module,keylayouts.mod,part_sun.mod,random.module,gfxterm_background.module,newc.module,config.h,udf.mod,usbserial_ftdi.mod,pcidump.module,xnu_uuid_test.mod,eval.mod,video_cirrus.mod,videoinfo.module,jpeg.module,gcry_rsa.mod,gfxterm_background.mod,jpeg.mod,memrw.module,zfsinfo.mod,pxe.mod,sleep_test.mod,usbserial_pl2303.mod,xnu_uuid_test.module,linux16.module,zstd.mod,pxechain.mod,terminal.lst,part_dvh.module,video_colors.mod,partmap.lst,tga.module,gdb_helper.py,search.mod,ctz_test.module,progress.mod,vga_text.module,sleep.module,gcry_arcfour.module,btrfs.module,gcry_sha512.mod,setjmp.mod,wrmsr.mod,lspci.mod,vbe.mod,reboot.mod,keystatus.module,terminfo.mod,mmap.module,signature_test.module,cmdline_cat_test.mod,part_amiga.mod,xnu_uuid.module,cbtable.module,bitmap_scale.mod,minix_be.mod,part_apple.module,ufs1.module,disk.mod,cbfs.module,gcry_twofish.mod,password_pbkdf2.module,mul_test.mod,date.mod,net.module,reboot.module,priority_queue.mod,xfs.module,gfxmenu.module,gcry_sha256.mod,part_sun.module,parttool.lst,part_plan.mod,vga.module,affs.mod,boot_hybrid.image,xfs.mod,usbms.mod,legacy_password_test.mod,parttool.mod,cmp_test.module,command.lst,ntfs.mod,memdisk.module,testspeed.mod,minix3_be.mod,plan9.mod,romfs.module,reiserfs.mod,multiboot2.module,setjmp_test.mod,blocklist.module,echo.mod,legacycfg.module,rdmsr.mod,vbe.module,ata.mod,bsd.mod,ls.mod,bitmap.module,gcry_rmd160.mod,videoinfo.mod,videotest_checksum.module,bfs.mod,lvm.module,minix.module,ext2.mod,gcry_rijndael.module,exfctest.mod,lnxboot.img,gcry_camellia.mod,png.mod,loopback.module,gcry_des.mod,bufio.module,pgp.module,usbserial_ftdi.module,ntldr.mod,regexp.module,datehook.mod,functional_test.mod,gcry_sha512.module,cbfs.mod,gcry_sha1.mod,part_gpt.mod,gcry_tiger.module,hfspluscomp.mod,testload.mod,gcry_rijndael.mod,spkmodem.mod,gcry_camellia.module,gfxterm.mod,adler32.mod,fat.mod,biosdisk.mod,div_test.module,cmostest.module,usbserial_usbdebug.module,cmp.module,iorw.mod,trig.mod,video.lst,signature_test.mod,bfs.module,diskfilter.module,luks2.module,zfscrypt.mod,nativedisk.mod,gcry_serpent.module,minix2.module,modinfo.sh,wrmsr.module,bufio.mod,gcry_twofish.module,mdraid1x.mod,configfile.module,disk.module,cmp.mod,linux.module,part_bsd.module,parttool.module,test_blockarg.mod,search.module,video_bochs.mod,date.module,dm_nv.mod,strtoull_test.module,pata.mod,ufs1_be.module,keystatus.mod,minix3.module,ntfscomp.module,drivemap.mod,pbkdf2_test.module,jfs.module,xnu.module,usbserial_pl2303.module,reiserfs.module,sfs.mod,kernel.img,gcry_seed.mod,freedos.module,gcry_crc.module,video.mod,pxeboot.image,setjmp.module,all_video.mod,sendkey.module,moddep.lst,terminal.module,terminal.mod,gptsync.mod,test_blockarg.module,file.module,smbios.mod,lzopio.module,minicmd.mod,help.mod,plainmount.module,probe.module,efiemu32.o,tr.module,chain.mod,videotest.module,gcry_idea.module,fshelp.mod,cpio_be.module,linux.mod,normal.mod,bitmap_scale.module,part_plan.module,gcry_whirlpool.mod,fs.lst,diskboot.img,gcry_rmd160.module,crc64.module,lnxboot.image,romfs.mod,tar.mod,uhci.module,mmap.mod,search_label.mod,time.mod,usb_keyboard.mod,part_amiga.module,minicmd.module,gcry_arcfour.mod,zfscrypt.module,xnu_uuid.mod,read.module,afs.mod,cmosdump.module,png.module,pata.module,drivemap.module,json.mod,gcry_rsa.module,afsplitter.mod,boot_hybrid.img,test.mod,datehook.module,syslinuxcfg.mod,trig.module,priority_queue.module,iorw.module,ohci.module,pci.mod,part_apple.mod,serial.mod,loopback.mod,msdospart.module,ls.module,datetime.module,part_acorn.module,part_sunpc.module,sleep.mod,extcmd.module,zfsinfo.module,mdraid1x.module,nilfs2.module,relocator.mod,gdb.mod,odc.module,part_acorn.mod,boot.module,gettext.mod,memdisk.mod,halt.module,halt.mod,eval.module,diskboot.image,part_gpt.module,true.mod,minix3.mod,macho.mod,pxeboot.img,morse.module,cmostest.mod,xnu.mod,geli.module,usbtest.module,search_fs_uuid.module,exfat.mod,nativedisk.module,mul_test.module,random.mod,normal.module,cpio_be.mod,cdboot.img,test.module,video_bochs.module,div.mod,macbless.module,syslinuxcfg.module,bitmap.mod,hdparm.mod,hfspluscomp.module,blocklist.mod,exfctest.module,ufs1_be.mod,kernel.exec,terminfo.module,cbmemc.module,minix.mod,gcry_dsa.module,usb.module,gcry_dsa.mod,gcry_md5.mod,gfxterm_menu.module,usbms.module,lsapm.module,crc64.mod,pbkdf2.module,gfxterm.module,at_keyboard.mod,lzma_decompress.image,functional_test.module,cs5536.module,cmosdump.mod,search_fs_file.mod,cs5536.mod,serial.module,minix2_be.mod,testload.module,read.mod,http.module,pgp.mod,elf.module,cbmemc.mod,ehci.mod,chain.module,luks2.mod,cbtable.mod,xzio.module,play.module,ufs1.mod,password.module,setpci.mod,mda_text.mod,exfat.module,bswap_test.module,cpuid.module,luks.module,msdospart.mod,cmdline_cat_test.module,gdb_grub,tga.mod,lsmmap.mod,hfs.module,help.module,tftp.module,search_label.module,truecrypt.mod,plan9.module,font.module,ntfs.module,gcry_des.module,file.mod,procfs.mod,lsacpi.mod,ufs2.module,hexdump.mod,crypto.mod,plainmount.mod,fat.module,gfxterm_menu.mod,ntldr.module,part_dvh.mod,hello.module,relocator.module,gcry_rfc2268.module,ldm.module,tftp.mod,raid6rec.mod,zfs.mod,at_keyboard.module,usbserial_common.module,efiemu.module,rdmsr.module,lspci.module,multiboot.mod,boot.image,boot.mod,vga_text.mod,datetime.mod,gcry_crc.mod,afs.module,setjmp_test.module,ctz_test.mod,multiboot2.mod,mdraid09.module,hashsum.mod,ohci.mod,acpi.mod,part_dfly.module,fdt.lst,loadenv.module,lsapm.mod,boot.img,hfs.mod,ufs2.mod,macbless.mod,cat.mod,squash4.module,ahci.module,lsacpi.module,minix2_be.module,ata.module,aout.mod,lzma_decompress.img,hello.mod,multiboot.module,gcry_blowfish.module,udf.module,gcry_cast5.module,password.mod,efiemu64.o,hdparm.module,gcry_sha256.module,gcry_idea.mod,hexdump.module} \
                      usr/sbin/{grub-probe,grub-mkconfig,grub-bios-setup,grub-set-default,grub-sparc64-setup,grub-ofpathname,grub-macbless,grub-install,grub-reboot} \
                      usr/share/grub/grub-mkconfig_lib \
                      usr/share/locale/{de/LC_MESSAGES/grub.mo,en@arabic/LC_MESSAGES/grub.mo,ast/LC_MESSAGES/grub.mo,pt_BR/LC_MESSAGES/grub.mo,lg/LC_MESSAGES/grub.mo,tr/LC_MESSAGES/grub.mo,hu/LC_MESSAGES/grub.mo,gl/LC_MESSAGES/grub.mo,da/LC_MESSAGES/grub.mo,hr/LC_MESSAGES/grub.mo,he/LC_MESSAGES/grub.mo,en@greek/LC_MESSAGES/grub.mo,sr/LC_MESSAGES/grub.mo,fi/LC_MESSAGES/grub.mo,de_CH/LC_MESSAGES/grub.mo,pa/LC_MESSAGES/grub.mo,ka/LC_MESSAGES/grub.mo,pl/LC_MESSAGES/grub.mo,lt/LC_MESSAGES/grub.mo,ca/LC_MESSAGES/grub.mo,it/LC_MESSAGES/grub.mo,nl/LC_MESSAGES/grub.mo,es/LC_MESSAGES/grub.mo,eo/LC_MESSAGES/grub.mo,ko/LC_MESSAGES/grub.mo,sl/LC_MESSAGES/grub.mo,fr/LC_MESSAGES/grub.mo,uk/LC_MESSAGES/grub.mo,en@hebrew/LC_MESSAGES/grub.mo,zh_TW/LC_MESSAGES/grub.mo,vi/LC_MESSAGES/grub.mo,en@piglatin/LC_MESSAGES/grub.mo,ja/LC_MESSAGES/grub.mo,en@cyrillic/LC_MESSAGES/grub.mo,nb/LC_MESSAGES/grub.mo,ru/LC_MESSAGES/grub.mo,sv/LC_MESSAGES/grub.mo,zh_CN/LC_MESSAGES/grub.mo,id/LC_MESSAGES/grub.mo,en@quot/LC_MESSAGES/grub.mo,de@hebrew/LC_MESSAGES/grub.mo,ro/LC_MESSAGES/grub.mo,pt/LC_MESSAGES/grub.mo}

$ROOT/generate_rpm.sh "$ISO_RPMS" \
                      "$GRUB_SRC/build/rpmbuild" \
                      "$GRUB_RPM_NAME" \
                      "$GRUB_VERSION" \
                      "Grub2 bootloader" \
                      "Grub2 is the second version of the GRand Unified Bootloader" \
                      "GPL-3" \
                      "$GRUB_SRC/build/$GRUB_FULLNAME.tar" \
"etc/grub.d/41_custom" "%{_sysconfdir}/grub.d/41_custom" \
"etc/grub.d/20_linux_xen" "%{_sysconfdir}/grub.d/20_linux_xen" \
"etc/grub.d/README" "%{_sysconfdir}/grub.d/README" \
"etc/grub.d/10_linux" "%{_sysconfdir}/grub.d/10_linux" \
"etc/grub.d/25_bli" "%{_sysconfdir}/grub.d/25_bli" \
"etc/grub.d/00_header" "%{_sysconfdir}/grub.d/00_header" \
"etc/grub.d/30_uefi-firmware" "%{_sysconfdir}/grub.d/30_uefi-firmware" \
"etc/grub.d/30_os-prober" "%{_sysconfdir}/grub.d/30_os-prober" \
"etc/grub.d/40_custom" "%{_sysconfdir}/grub.d/40_custom" \
"etc/bash_completion.d/grub" "%{_sysconfdir}/bash_completion.d/grub" \
"usr/bin/grub-mkrelpath" "%{_bindir}/grub-mkrelpath" \
"usr/bin/grub-fstest" "%{_bindir}/grub-fstest" \
"usr/bin/grub-mkpasswd-pbkdf2" "%{_bindir}/grub-mkpasswd-pbkdf2" \
"usr/bin/grub-menulst2cfg" "%{_bindir}/grub-menulst2cfg" \
"usr/bin/grub-render-label" "%{_bindir}/grub-render-label" \
"usr/bin/grub-mkrescue" "%{_bindir}/grub-mkrescue" \
"usr/bin/grub-mklayout" "%{_bindir}/grub-mklayout" \
"usr/bin/grub-mkstandalone" "%{_bindir}/grub-mkstandalone" \
"usr/bin/grub-editenv" "%{_bindir}/grub-editenv" \
"usr/bin/grub-script-check" "%{_bindir}/grub-script-check" \
"usr/bin/grub-glue-efi" "%{_bindir}/grub-glue-efi" \
"usr/bin/grub-mknetdir" "%{_bindir}/grub-mknetdir" \
"usr/bin/grub-file" "%{_bindir}/grub-file" \
"usr/bin/grub-mkimage" "%{_bindir}/grub-mkimage" \
"usr/bin/grub-kbdcomp" "%{_bindir}/grub-kbdcomp" \
"usr/bin/grub-syslinux2cfg" "%{_bindir}/grub-syslinux2cfg" \
"usr/lib/grub/i386-pc/pxechain.module" "%{_libdir}/grub/i386-pc/pxechain.module" \
"usr/lib/grub/i386-pc/acpi.module" "%{_libdir}/grub/i386-pc/acpi.module" \
"usr/lib/grub/i386-pc/adler32.module" "%{_libdir}/grub/i386-pc/adler32.module" \
"usr/lib/grub/i386-pc/gcry_sha1.module" "%{_libdir}/grub/i386-pc/gcry_sha1.module" \
"usr/lib/grub/i386-pc/echo.module" "%{_libdir}/grub/i386-pc/echo.module" \
"usr/lib/grub/i386-pc/font.mod" "%{_libdir}/grub/i386-pc/font.mod" \
"usr/lib/grub/i386-pc/part_msdos.mod" "%{_libdir}/grub/i386-pc/part_msdos.mod" \
"usr/lib/grub/i386-pc/ldm.mod" "%{_libdir}/grub/i386-pc/ldm.mod" \
"usr/lib/grub/i386-pc/gcry_md4.module" "%{_libdir}/grub/i386-pc/gcry_md4.module" \
"usr/lib/grub/i386-pc/scsi.mod" "%{_libdir}/grub/i386-pc/scsi.mod" \
"usr/lib/grub/i386-pc/bswap_test.mod" "%{_libdir}/grub/i386-pc/bswap_test.mod" \
"usr/lib/grub/i386-pc/fshelp.module" "%{_libdir}/grub/i386-pc/fshelp.module" \
"usr/lib/grub/i386-pc/part_sunpc.mod" "%{_libdir}/grub/i386-pc/part_sunpc.mod" \
"usr/lib/grub/i386-pc/linux16.mod" "%{_libdir}/grub/i386-pc/linux16.mod" \
"usr/lib/grub/i386-pc/minix2.mod" "%{_libdir}/grub/i386-pc/minix2.mod" \
"usr/lib/grub/i386-pc/zstd.module" "%{_libdir}/grub/i386-pc/zstd.module" \
"usr/lib/grub/i386-pc/macho.module" "%{_libdir}/grub/i386-pc/macho.module" \
"usr/lib/grub/i386-pc/vga.mod" "%{_libdir}/grub/i386-pc/vga.mod" \
"usr/lib/grub/i386-pc/hashsum.module" "%{_libdir}/grub/i386-pc/hashsum.module" \
"usr/lib/grub/i386-pc/tar.module" "%{_libdir}/grub/i386-pc/tar.module" \
"usr/lib/grub/i386-pc/gcry_blowfish.mod" "%{_libdir}/grub/i386-pc/gcry_blowfish.mod" \
"usr/lib/grub/i386-pc/ext2.module" "%{_libdir}/grub/i386-pc/ext2.module" \
"usr/lib/grub/i386-pc/btrfs.mod" "%{_libdir}/grub/i386-pc/btrfs.mod" \
"usr/lib/grub/i386-pc/morse.mod" "%{_libdir}/grub/i386-pc/morse.mod" \
"usr/lib/grub/i386-pc/backtrace.module" "%{_libdir}/grub/i386-pc/backtrace.module" \
"usr/lib/grub/i386-pc/gcry_cast5.mod" "%{_libdir}/grub/i386-pc/gcry_cast5.mod" \
"usr/lib/grub/i386-pc/cmp_test.mod" "%{_libdir}/grub/i386-pc/cmp_test.mod" \
"usr/lib/grub/i386-pc/odc.mod" "%{_libdir}/grub/i386-pc/odc.mod" \
"usr/lib/grub/i386-pc/shift_test.mod" "%{_libdir}/grub/i386-pc/shift_test.mod" \
"usr/lib/grub/i386-pc/part_dfly.mod" "%{_libdir}/grub/i386-pc/part_dfly.mod" \
"usr/lib/grub/i386-pc/net.mod" "%{_libdir}/grub/i386-pc/net.mod" \
"usr/lib/grub/i386-pc/keylayouts.module" "%{_libdir}/grub/i386-pc/keylayouts.module" \
"usr/lib/grub/i386-pc/lvm.mod" "%{_libdir}/grub/i386-pc/lvm.mod" \
"usr/lib/grub/i386-pc/testspeed.module" "%{_libdir}/grub/i386-pc/testspeed.module" \
"usr/lib/grub/i386-pc/part_bsd.mod" "%{_libdir}/grub/i386-pc/part_bsd.mod" \
"usr/lib/grub/i386-pc/time.module" "%{_libdir}/grub/i386-pc/time.module" \
"usr/lib/grub/i386-pc/gzio.module" "%{_libdir}/grub/i386-pc/gzio.module" \
"usr/lib/grub/i386-pc/cpio.mod" "%{_libdir}/grub/i386-pc/cpio.mod" \
"usr/lib/grub/i386-pc/cbtime.module" "%{_libdir}/grub/i386-pc/cbtime.module" \
"usr/lib/grub/i386-pc/nilfs2.mod" "%{_libdir}/grub/i386-pc/nilfs2.mod" \
"usr/lib/grub/i386-pc/video_colors.module" "%{_libdir}/grub/i386-pc/video_colors.module" \
"usr/lib/grub/i386-pc/loadenv.mod" "%{_libdir}/grub/i386-pc/loadenv.mod" \
"usr/lib/grub/i386-pc/search_fs_uuid.mod" "%{_libdir}/grub/i386-pc/search_fs_uuid.mod" \
"usr/lib/grub/i386-pc/configfile.mod" "%{_libdir}/grub/i386-pc/configfile.mod" \
"usr/lib/grub/i386-pc/lzopio.mod" "%{_libdir}/grub/i386-pc/lzopio.mod" \
"usr/lib/grub/i386-pc/diskfilter.mod" "%{_libdir}/grub/i386-pc/diskfilter.mod" \
"usr/lib/grub/i386-pc/afsplitter.module" "%{_libdir}/grub/i386-pc/afsplitter.module" \
"usr/lib/grub/i386-pc/video_cirrus.module" "%{_libdir}/grub/i386-pc/video_cirrus.module" \
"usr/lib/grub/i386-pc/jfs.mod" "%{_libdir}/grub/i386-pc/jfs.mod" \
"usr/lib/grub/i386-pc/legacy_password_test.module" "%{_libdir}/grub/i386-pc/legacy_password_test.module" \
"usr/lib/grub/i386-pc/squash4.mod" "%{_libdir}/grub/i386-pc/squash4.mod" \
"usr/lib/grub/i386-pc/raid5rec.module" "%{_libdir}/grub/i386-pc/raid5rec.module" \
"usr/lib/grub/i386-pc/elf.mod" "%{_libdir}/grub/i386-pc/elf.mod" \
"usr/lib/grub/i386-pc/mdraid09.mod" "%{_libdir}/grub/i386-pc/mdraid09.mod" \
"usr/lib/grub/i386-pc/gcry_seed.module" "%{_libdir}/grub/i386-pc/gcry_seed.module" \
"usr/lib/grub/i386-pc/iso9660.mod" "%{_libdir}/grub/i386-pc/iso9660.mod" \
"usr/lib/grub/i386-pc/offsetio.mod" "%{_libdir}/grub/i386-pc/offsetio.mod" \
"usr/lib/grub/i386-pc/cbls.module" "%{_libdir}/grub/i386-pc/cbls.module" \
"usr/lib/grub/i386-pc/cpio.module" "%{_libdir}/grub/i386-pc/cpio.module" \
"usr/lib/grub/i386-pc/archelp.mod" "%{_libdir}/grub/i386-pc/archelp.mod" \
"usr/lib/grub/i386-pc/lsmmap.module" "%{_libdir}/grub/i386-pc/lsmmap.module" \
"usr/lib/grub/i386-pc/cpuid.mod" "%{_libdir}/grub/i386-pc/cpuid.mod" \
"usr/lib/grub/i386-pc/all_video.module" "%{_libdir}/grub/i386-pc/all_video.module" \
"usr/lib/grub/i386-pc/newc.mod" "%{_libdir}/grub/i386-pc/newc.mod" \
"usr/lib/grub/i386-pc/http.mod" "%{_libdir}/grub/i386-pc/http.mod" \
"usr/lib/grub/i386-pc/mdraid09_be.mod" "%{_libdir}/grub/i386-pc/mdraid09_be.mod" \
"usr/lib/grub/i386-pc/mpi.mod" "%{_libdir}/grub/i386-pc/mpi.mod" \
"usr/lib/grub/i386-pc/xzio.mod" "%{_libdir}/grub/i386-pc/xzio.mod" \
"usr/lib/grub/i386-pc/strtoull_test.mod" "%{_libdir}/grub/i386-pc/strtoull_test.mod" \
"usr/lib/grub/i386-pc/mdraid09_be.module" "%{_libdir}/grub/i386-pc/mdraid09_be.module" \
"usr/lib/grub/i386-pc/minix3_be.module" "%{_libdir}/grub/i386-pc/minix3_be.module" \
"usr/lib/grub/i386-pc/password_pbkdf2.mod" "%{_libdir}/grub/i386-pc/password_pbkdf2.mod" \
"usr/lib/grub/i386-pc/video_fb.module" "%{_libdir}/grub/i386-pc/video_fb.module" \
"usr/lib/grub/i386-pc/f2fs.mod" "%{_libdir}/grub/i386-pc/f2fs.mod" \
"usr/lib/grub/i386-pc/minix_be.module" "%{_libdir}/grub/i386-pc/minix_be.module" \
"usr/lib/grub/i386-pc/json.module" "%{_libdir}/grub/i386-pc/json.module" \
"usr/lib/grub/i386-pc/cbls.mod" "%{_libdir}/grub/i386-pc/cbls.mod" \
"usr/lib/grub/i386-pc/video_fb.mod" "%{_libdir}/grub/i386-pc/video_fb.mod" \
"usr/lib/grub/i386-pc/gcry_tiger.mod" "%{_libdir}/grub/i386-pc/gcry_tiger.mod" \
"usr/lib/grub/i386-pc/crypto.lst" "%{_libdir}/grub/i386-pc/crypto.lst" \
"usr/lib/grub/i386-pc/smbios.module" "%{_libdir}/grub/i386-pc/smbios.module" \
"usr/lib/grub/i386-pc/memrw.mod" "%{_libdir}/grub/i386-pc/memrw.mod" \
"usr/lib/grub/i386-pc/usbserial_common.mod" "%{_libdir}/grub/i386-pc/usbserial_common.mod" \
"usr/lib/grub/i386-pc/gptsync.module" "%{_libdir}/grub/i386-pc/gptsync.module" \
"usr/lib/grub/i386-pc/offsetio.module" "%{_libdir}/grub/i386-pc/offsetio.module" \
"usr/lib/grub/i386-pc/hfsplus.module" "%{_libdir}/grub/i386-pc/hfsplus.module" \
"usr/lib/grub/i386-pc/truecrypt.module" "%{_libdir}/grub/i386-pc/truecrypt.module" \
"usr/lib/grub/i386-pc/aout.module" "%{_libdir}/grub/i386-pc/aout.module" \
"usr/lib/grub/i386-pc/ntfscomp.mod" "%{_libdir}/grub/i386-pc/ntfscomp.mod" \
"usr/lib/grub/i386-pc/mpi.module" "%{_libdir}/grub/i386-pc/mpi.module" \
"usr/lib/grub/i386-pc/spkmodem.module" "%{_libdir}/grub/i386-pc/spkmodem.module" \
"usr/lib/grub/i386-pc/regexp.mod" "%{_libdir}/grub/i386-pc/regexp.mod" \
"usr/lib/grub/i386-pc/gettext.module" "%{_libdir}/grub/i386-pc/gettext.module" \
"usr/lib/grub/i386-pc/sleep_test.module" "%{_libdir}/grub/i386-pc/sleep_test.module" \
"usr/lib/grub/i386-pc/pbkdf2.mod" "%{_libdir}/grub/i386-pc/pbkdf2.mod" \
"usr/lib/grub/i386-pc/usb_keyboard.module" "%{_libdir}/grub/i386-pc/usb_keyboard.module" \
"usr/lib/grub/i386-pc/pcidump.mod" "%{_libdir}/grub/i386-pc/pcidump.mod" \
"usr/lib/grub/i386-pc/pci.module" "%{_libdir}/grub/i386-pc/pci.module" \
"usr/lib/grub/i386-pc/probe.mod" "%{_libdir}/grub/i386-pc/probe.mod" \
"usr/lib/grub/i386-pc/div.module" "%{_libdir}/grub/i386-pc/div.module" \
"usr/lib/grub/i386-pc/backtrace.mod" "%{_libdir}/grub/i386-pc/backtrace.mod" \
"usr/lib/grub/i386-pc/uhci.mod" "%{_libdir}/grub/i386-pc/uhci.mod" \
"usr/lib/grub/i386-pc/ahci.mod" "%{_libdir}/grub/i386-pc/ahci.mod" \
"usr/lib/grub/i386-pc/search_fs_file.module" "%{_libdir}/grub/i386-pc/search_fs_file.module" \
"usr/lib/grub/i386-pc/zfs.module" "%{_libdir}/grub/i386-pc/zfs.module" \
"usr/lib/grub/i386-pc/freedos.mod" "%{_libdir}/grub/i386-pc/freedos.mod" \
"usr/lib/grub/i386-pc/gcry_whirlpool.module" "%{_libdir}/grub/i386-pc/gcry_whirlpool.module" \
"usr/lib/grub/i386-pc/cbtime.mod" "%{_libdir}/grub/i386-pc/cbtime.mod" \
"usr/lib/grub/i386-pc/usbtest.mod" "%{_libdir}/grub/i386-pc/usbtest.mod" \
"usr/lib/grub/i386-pc/legacycfg.mod" "%{_libdir}/grub/i386-pc/legacycfg.mod" \
"usr/lib/grub/i386-pc/geli.mod" "%{_libdir}/grub/i386-pc/geli.mod" \
"usr/lib/grub/i386-pc/videotest.mod" "%{_libdir}/grub/i386-pc/videotest.mod" \
"usr/lib/grub/i386-pc/sendkey.mod" "%{_libdir}/grub/i386-pc/sendkey.mod" \
"usr/lib/grub/i386-pc/videotest_checksum.mod" "%{_libdir}/grub/i386-pc/videotest_checksum.mod" \
"usr/lib/grub/i386-pc/pxe.module" "%{_libdir}/grub/i386-pc/pxe.module" \
"usr/lib/grub/i386-pc/affs.module" "%{_libdir}/grub/i386-pc/affs.module" \
"usr/lib/grub/i386-pc/gcry_md4.mod" "%{_libdir}/grub/i386-pc/gcry_md4.mod" \
"usr/lib/grub/i386-pc/luks.mod" "%{_libdir}/grub/i386-pc/luks.mod" \
"usr/lib/grub/i386-pc/dm_nv.module" "%{_libdir}/grub/i386-pc/dm_nv.module" \
"usr/lib/grub/i386-pc/iso9660.module" "%{_libdir}/grub/i386-pc/iso9660.module" \
"usr/lib/grub/i386-pc/hfsplus.mod" "%{_libdir}/grub/i386-pc/hfsplus.mod" \
"usr/lib/grub/i386-pc/gcry_md5.module" "%{_libdir}/grub/i386-pc/gcry_md5.module" \
"usr/lib/grub/i386-pc/f2fs.module" "%{_libdir}/grub/i386-pc/f2fs.module" \
"usr/lib/grub/i386-pc/setpci.module" "%{_libdir}/grub/i386-pc/setpci.module" \
"usr/lib/grub/i386-pc/video.module" "%{_libdir}/grub/i386-pc/video.module" \
"usr/lib/grub/i386-pc/extcmd.mod" "%{_libdir}/grub/i386-pc/extcmd.mod" \
"usr/lib/grub/i386-pc/gcry_serpent.mod" "%{_libdir}/grub/i386-pc/gcry_serpent.mod" \
"usr/lib/grub/i386-pc/procfs.module" "%{_libdir}/grub/i386-pc/procfs.module" \
"usr/lib/grub/i386-pc/usb.mod" "%{_libdir}/grub/i386-pc/usb.mod" \
"usr/lib/grub/i386-pc/gcry_rfc2268.mod" "%{_libdir}/grub/i386-pc/gcry_rfc2268.mod" \
"usr/lib/grub/i386-pc/true.module" "%{_libdir}/grub/i386-pc/true.module" \
"usr/lib/grub/i386-pc/archelp.module" "%{_libdir}/grub/i386-pc/archelp.module" \
"usr/lib/grub/i386-pc/crypto.module" "%{_libdir}/grub/i386-pc/crypto.module" \
"usr/lib/grub/i386-pc/gfxmenu.mod" "%{_libdir}/grub/i386-pc/gfxmenu.mod" \
"usr/lib/grub/i386-pc/cryptodisk.mod" "%{_libdir}/grub/i386-pc/cryptodisk.mod" \
"usr/lib/grub/i386-pc/tr.mod" "%{_libdir}/grub/i386-pc/tr.mod" \
"usr/lib/grub/i386-pc/cat.module" "%{_libdir}/grub/i386-pc/cat.module" \
"usr/lib/grub/i386-pc/raid5rec.mod" "%{_libdir}/grub/i386-pc/raid5rec.mod" \
"usr/lib/grub/i386-pc/cryptodisk.module" "%{_libdir}/grub/i386-pc/cryptodisk.module" \
"usr/lib/grub/i386-pc/shift_test.module" "%{_libdir}/grub/i386-pc/shift_test.module" \
"usr/lib/grub/i386-pc/gzio.mod" "%{_libdir}/grub/i386-pc/gzio.mod" \
"usr/lib/grub/i386-pc/efiemu.mod" "%{_libdir}/grub/i386-pc/efiemu.mod" \
"usr/lib/grub/i386-pc/biosdisk.module" "%{_libdir}/grub/i386-pc/biosdisk.module" \
"usr/lib/grub/i386-pc/progress.module" "%{_libdir}/grub/i386-pc/progress.module" \
"usr/lib/grub/i386-pc/raid6rec.module" "%{_libdir}/grub/i386-pc/raid6rec.module" \
"usr/lib/grub/i386-pc/cdboot.image" "%{_libdir}/grub/i386-pc/cdboot.image" \
"usr/lib/grub/i386-pc/scsi.module" "%{_libdir}/grub/i386-pc/scsi.module" \
"usr/lib/grub/i386-pc/usbserial_usbdebug.mod" "%{_libdir}/grub/i386-pc/usbserial_usbdebug.mod" \
"usr/lib/grub/i386-pc/pbkdf2_test.mod" "%{_libdir}/grub/i386-pc/pbkdf2_test.mod" \
"usr/lib/grub/i386-pc/mda_text.module" "%{_libdir}/grub/i386-pc/mda_text.module" \
"usr/lib/grub/i386-pc/bsd.module" "%{_libdir}/grub/i386-pc/bsd.module" \
"usr/lib/grub/i386-pc/gdb.module" "%{_libdir}/grub/i386-pc/gdb.module" \
"usr/lib/grub/i386-pc/play.mod" "%{_libdir}/grub/i386-pc/play.mod" \
"usr/lib/grub/i386-pc/part_msdos.module" "%{_libdir}/grub/i386-pc/part_msdos.module" \
"usr/lib/grub/i386-pc/ehci.module" "%{_libdir}/grub/i386-pc/ehci.module" \
"usr/lib/grub/i386-pc/div_test.mod" "%{_libdir}/grub/i386-pc/div_test.mod" \
"usr/lib/grub/i386-pc/sfs.module" "%{_libdir}/grub/i386-pc/sfs.module" \
"usr/lib/grub/i386-pc/keylayouts.mod" "%{_libdir}/grub/i386-pc/keylayouts.mod" \
"usr/lib/grub/i386-pc/part_sun.mod" "%{_libdir}/grub/i386-pc/part_sun.mod" \
"usr/lib/grub/i386-pc/random.module" "%{_libdir}/grub/i386-pc/random.module" \
"usr/lib/grub/i386-pc/gfxterm_background.module" "%{_libdir}/grub/i386-pc/gfxterm_background.module" \
"usr/lib/grub/i386-pc/newc.module" "%{_libdir}/grub/i386-pc/newc.module" \
"usr/lib/grub/i386-pc/config.h" "%{_libdir}/grub/i386-pc/config.h" \
"usr/lib/grub/i386-pc/udf.mod" "%{_libdir}/grub/i386-pc/udf.mod" \
"usr/lib/grub/i386-pc/usbserial_ftdi.mod" "%{_libdir}/grub/i386-pc/usbserial_ftdi.mod" \
"usr/lib/grub/i386-pc/pcidump.module" "%{_libdir}/grub/i386-pc/pcidump.module" \
"usr/lib/grub/i386-pc/xnu_uuid_test.mod" "%{_libdir}/grub/i386-pc/xnu_uuid_test.mod" \
"usr/lib/grub/i386-pc/eval.mod" "%{_libdir}/grub/i386-pc/eval.mod" \
"usr/lib/grub/i386-pc/video_cirrus.mod" "%{_libdir}/grub/i386-pc/video_cirrus.mod" \
"usr/lib/grub/i386-pc/videoinfo.module" "%{_libdir}/grub/i386-pc/videoinfo.module" \
"usr/lib/grub/i386-pc/jpeg.module" "%{_libdir}/grub/i386-pc/jpeg.module" \
"usr/lib/grub/i386-pc/gcry_rsa.mod" "%{_libdir}/grub/i386-pc/gcry_rsa.mod" \
"usr/lib/grub/i386-pc/gfxterm_background.mod" "%{_libdir}/grub/i386-pc/gfxterm_background.mod" \
"usr/lib/grub/i386-pc/jpeg.mod" "%{_libdir}/grub/i386-pc/jpeg.mod" \
"usr/lib/grub/i386-pc/memrw.module" "%{_libdir}/grub/i386-pc/memrw.module" \
"usr/lib/grub/i386-pc/zfsinfo.mod" "%{_libdir}/grub/i386-pc/zfsinfo.mod" \
"usr/lib/grub/i386-pc/pxe.mod" "%{_libdir}/grub/i386-pc/pxe.mod" \
"usr/lib/grub/i386-pc/sleep_test.mod" "%{_libdir}/grub/i386-pc/sleep_test.mod" \
"usr/lib/grub/i386-pc/usbserial_pl2303.mod" "%{_libdir}/grub/i386-pc/usbserial_pl2303.mod" \
"usr/lib/grub/i386-pc/xnu_uuid_test.module" "%{_libdir}/grub/i386-pc/xnu_uuid_test.module" \
"usr/lib/grub/i386-pc/linux16.module" "%{_libdir}/grub/i386-pc/linux16.module" \
"usr/lib/grub/i386-pc/zstd.mod" "%{_libdir}/grub/i386-pc/zstd.mod" \
"usr/lib/grub/i386-pc/pxechain.mod" "%{_libdir}/grub/i386-pc/pxechain.mod" \
"usr/lib/grub/i386-pc/terminal.lst" "%{_libdir}/grub/i386-pc/terminal.lst" \
"usr/lib/grub/i386-pc/part_dvh.module" "%{_libdir}/grub/i386-pc/part_dvh.module" \
"usr/lib/grub/i386-pc/video_colors.mod" "%{_libdir}/grub/i386-pc/video_colors.mod" \
"usr/lib/grub/i386-pc/partmap.lst" "%{_libdir}/grub/i386-pc/partmap.lst" \
"usr/lib/grub/i386-pc/tga.module" "%{_libdir}/grub/i386-pc/tga.module" \
"usr/lib/grub/i386-pc/gdb_helper.py" "%{_libdir}/grub/i386-pc/gdb_helper.py" \
"usr/lib/grub/i386-pc/search.mod" "%{_libdir}/grub/i386-pc/search.mod" \
"usr/lib/grub/i386-pc/ctz_test.module" "%{_libdir}/grub/i386-pc/ctz_test.module" \
"usr/lib/grub/i386-pc/progress.mod" "%{_libdir}/grub/i386-pc/progress.mod" \
"usr/lib/grub/i386-pc/vga_text.module" "%{_libdir}/grub/i386-pc/vga_text.module" \
"usr/lib/grub/i386-pc/sleep.module" "%{_libdir}/grub/i386-pc/sleep.module" \
"usr/lib/grub/i386-pc/gcry_arcfour.module" "%{_libdir}/grub/i386-pc/gcry_arcfour.module" \
"usr/lib/grub/i386-pc/btrfs.module" "%{_libdir}/grub/i386-pc/btrfs.module" \
"usr/lib/grub/i386-pc/gcry_sha512.mod" "%{_libdir}/grub/i386-pc/gcry_sha512.mod" \
"usr/lib/grub/i386-pc/setjmp.mod" "%{_libdir}/grub/i386-pc/setjmp.mod" \
"usr/lib/grub/i386-pc/wrmsr.mod" "%{_libdir}/grub/i386-pc/wrmsr.mod" \
"usr/lib/grub/i386-pc/lspci.mod" "%{_libdir}/grub/i386-pc/lspci.mod" \
"usr/lib/grub/i386-pc/vbe.mod" "%{_libdir}/grub/i386-pc/vbe.mod" \
"usr/lib/grub/i386-pc/reboot.mod" "%{_libdir}/grub/i386-pc/reboot.mod" \
"usr/lib/grub/i386-pc/keystatus.module" "%{_libdir}/grub/i386-pc/keystatus.module" \
"usr/lib/grub/i386-pc/terminfo.mod" "%{_libdir}/grub/i386-pc/terminfo.mod" \
"usr/lib/grub/i386-pc/mmap.module" "%{_libdir}/grub/i386-pc/mmap.module" \
"usr/lib/grub/i386-pc/signature_test.module" "%{_libdir}/grub/i386-pc/signature_test.module" \
"usr/lib/grub/i386-pc/cmdline_cat_test.mod" "%{_libdir}/grub/i386-pc/cmdline_cat_test.mod" \
"usr/lib/grub/i386-pc/part_amiga.mod" "%{_libdir}/grub/i386-pc/part_amiga.mod" \
"usr/lib/grub/i386-pc/xnu_uuid.module" "%{_libdir}/grub/i386-pc/xnu_uuid.module" \
"usr/lib/grub/i386-pc/cbtable.module" "%{_libdir}/grub/i386-pc/cbtable.module" \
"usr/lib/grub/i386-pc/bitmap_scale.mod" "%{_libdir}/grub/i386-pc/bitmap_scale.mod" \
"usr/lib/grub/i386-pc/minix_be.mod" "%{_libdir}/grub/i386-pc/minix_be.mod" \
"usr/lib/grub/i386-pc/part_apple.module" "%{_libdir}/grub/i386-pc/part_apple.module" \
"usr/lib/grub/i386-pc/ufs1.module" "%{_libdir}/grub/i386-pc/ufs1.module" \
"usr/lib/grub/i386-pc/disk.mod" "%{_libdir}/grub/i386-pc/disk.mod" \
"usr/lib/grub/i386-pc/cbfs.module" "%{_libdir}/grub/i386-pc/cbfs.module" \
"usr/lib/grub/i386-pc/gcry_twofish.mod" "%{_libdir}/grub/i386-pc/gcry_twofish.mod" \
"usr/lib/grub/i386-pc/password_pbkdf2.module" "%{_libdir}/grub/i386-pc/password_pbkdf2.module" \
"usr/lib/grub/i386-pc/mul_test.mod" "%{_libdir}/grub/i386-pc/mul_test.mod" \
"usr/lib/grub/i386-pc/date.mod" "%{_libdir}/grub/i386-pc/date.mod" \
"usr/lib/grub/i386-pc/net.module" "%{_libdir}/grub/i386-pc/net.module" \
"usr/lib/grub/i386-pc/reboot.module" "%{_libdir}/grub/i386-pc/reboot.module" \
"usr/lib/grub/i386-pc/priority_queue.mod" "%{_libdir}/grub/i386-pc/priority_queue.mod" \
"usr/lib/grub/i386-pc/xfs.module" "%{_libdir}/grub/i386-pc/xfs.module" \
"usr/lib/grub/i386-pc/gfxmenu.module" "%{_libdir}/grub/i386-pc/gfxmenu.module" \
"usr/lib/grub/i386-pc/gcry_sha256.mod" "%{_libdir}/grub/i386-pc/gcry_sha256.mod" \
"usr/lib/grub/i386-pc/part_sun.module" "%{_libdir}/grub/i386-pc/part_sun.module" \
"usr/lib/grub/i386-pc/parttool.lst" "%{_libdir}/grub/i386-pc/parttool.lst" \
"usr/lib/grub/i386-pc/part_plan.mod" "%{_libdir}/grub/i386-pc/part_plan.mod" \
"usr/lib/grub/i386-pc/vga.module" "%{_libdir}/grub/i386-pc/vga.module" \
"usr/lib/grub/i386-pc/affs.mod" "%{_libdir}/grub/i386-pc/affs.mod" \
"usr/lib/grub/i386-pc/boot_hybrid.image" "%{_libdir}/grub/i386-pc/boot_hybrid.image" \
"usr/lib/grub/i386-pc/xfs.mod" "%{_libdir}/grub/i386-pc/xfs.mod" \
"usr/lib/grub/i386-pc/usbms.mod" "%{_libdir}/grub/i386-pc/usbms.mod" \
"usr/lib/grub/i386-pc/legacy_password_test.mod" "%{_libdir}/grub/i386-pc/legacy_password_test.mod" \
"usr/lib/grub/i386-pc/parttool.mod" "%{_libdir}/grub/i386-pc/parttool.mod" \
"usr/lib/grub/i386-pc/cmp_test.module" "%{_libdir}/grub/i386-pc/cmp_test.module" \
"usr/lib/grub/i386-pc/command.lst" "%{_libdir}/grub/i386-pc/command.lst" \
"usr/lib/grub/i386-pc/ntfs.mod" "%{_libdir}/grub/i386-pc/ntfs.mod" \
"usr/lib/grub/i386-pc/memdisk.module" "%{_libdir}/grub/i386-pc/memdisk.module" \
"usr/lib/grub/i386-pc/testspeed.mod" "%{_libdir}/grub/i386-pc/testspeed.mod" \
"usr/lib/grub/i386-pc/minix3_be.mod" "%{_libdir}/grub/i386-pc/minix3_be.mod" \
"usr/lib/grub/i386-pc/plan9.mod" "%{_libdir}/grub/i386-pc/plan9.mod" \
"usr/lib/grub/i386-pc/romfs.module" "%{_libdir}/grub/i386-pc/romfs.module" \
"usr/lib/grub/i386-pc/reiserfs.mod" "%{_libdir}/grub/i386-pc/reiserfs.mod" \
"usr/lib/grub/i386-pc/multiboot2.module" "%{_libdir}/grub/i386-pc/multiboot2.module" \
"usr/lib/grub/i386-pc/setjmp_test.mod" "%{_libdir}/grub/i386-pc/setjmp_test.mod" \
"usr/lib/grub/i386-pc/blocklist.module" "%{_libdir}/grub/i386-pc/blocklist.module" \
"usr/lib/grub/i386-pc/echo.mod" "%{_libdir}/grub/i386-pc/echo.mod" \
"usr/lib/grub/i386-pc/legacycfg.module" "%{_libdir}/grub/i386-pc/legacycfg.module" \
"usr/lib/grub/i386-pc/rdmsr.mod" "%{_libdir}/grub/i386-pc/rdmsr.mod" \
"usr/lib/grub/i386-pc/vbe.module" "%{_libdir}/grub/i386-pc/vbe.module" \
"usr/lib/grub/i386-pc/ata.mod" "%{_libdir}/grub/i386-pc/ata.mod" \
"usr/lib/grub/i386-pc/bsd.mod" "%{_libdir}/grub/i386-pc/bsd.mod" \
"usr/lib/grub/i386-pc/ls.mod" "%{_libdir}/grub/i386-pc/ls.mod" \
"usr/lib/grub/i386-pc/bitmap.module" "%{_libdir}/grub/i386-pc/bitmap.module" \
"usr/lib/grub/i386-pc/gcry_rmd160.mod" "%{_libdir}/grub/i386-pc/gcry_rmd160.mod" \
"usr/lib/grub/i386-pc/videoinfo.mod" "%{_libdir}/grub/i386-pc/videoinfo.mod" \
"usr/lib/grub/i386-pc/videotest_checksum.module" "%{_libdir}/grub/i386-pc/videotest_checksum.module" \
"usr/lib/grub/i386-pc/bfs.mod" "%{_libdir}/grub/i386-pc/bfs.mod" \
"usr/lib/grub/i386-pc/lvm.module" "%{_libdir}/grub/i386-pc/lvm.module" \
"usr/lib/grub/i386-pc/minix.module" "%{_libdir}/grub/i386-pc/minix.module" \
"usr/lib/grub/i386-pc/ext2.mod" "%{_libdir}/grub/i386-pc/ext2.mod" \
"usr/lib/grub/i386-pc/gcry_rijndael.module" "%{_libdir}/grub/i386-pc/gcry_rijndael.module" \
"usr/lib/grub/i386-pc/exfctest.mod" "%{_libdir}/grub/i386-pc/exfctest.mod" \
"usr/lib/grub/i386-pc/lnxboot.img" "%{_libdir}/grub/i386-pc/lnxboot.img" \
"usr/lib/grub/i386-pc/gcry_camellia.mod" "%{_libdir}/grub/i386-pc/gcry_camellia.mod" \
"usr/lib/grub/i386-pc/png.mod" "%{_libdir}/grub/i386-pc/png.mod" \
"usr/lib/grub/i386-pc/loopback.module" "%{_libdir}/grub/i386-pc/loopback.module" \
"usr/lib/grub/i386-pc/gcry_des.mod" "%{_libdir}/grub/i386-pc/gcry_des.mod" \
"usr/lib/grub/i386-pc/bufio.module" "%{_libdir}/grub/i386-pc/bufio.module" \
"usr/lib/grub/i386-pc/pgp.module" "%{_libdir}/grub/i386-pc/pgp.module" \
"usr/lib/grub/i386-pc/usbserial_ftdi.module" "%{_libdir}/grub/i386-pc/usbserial_ftdi.module" \
"usr/lib/grub/i386-pc/ntldr.mod" "%{_libdir}/grub/i386-pc/ntldr.mod" \
"usr/lib/grub/i386-pc/regexp.module" "%{_libdir}/grub/i386-pc/regexp.module" \
"usr/lib/grub/i386-pc/datehook.mod" "%{_libdir}/grub/i386-pc/datehook.mod" \
"usr/lib/grub/i386-pc/functional_test.mod" "%{_libdir}/grub/i386-pc/functional_test.mod" \
"usr/lib/grub/i386-pc/gcry_sha512.module" "%{_libdir}/grub/i386-pc/gcry_sha512.module" \
"usr/lib/grub/i386-pc/cbfs.mod" "%{_libdir}/grub/i386-pc/cbfs.mod" \
"usr/lib/grub/i386-pc/gcry_sha1.mod" "%{_libdir}/grub/i386-pc/gcry_sha1.mod" \
"usr/lib/grub/i386-pc/part_gpt.mod" "%{_libdir}/grub/i386-pc/part_gpt.mod" \
"usr/lib/grub/i386-pc/gcry_tiger.module" "%{_libdir}/grub/i386-pc/gcry_tiger.module" \
"usr/lib/grub/i386-pc/hfspluscomp.mod" "%{_libdir}/grub/i386-pc/hfspluscomp.mod" \
"usr/lib/grub/i386-pc/testload.mod" "%{_libdir}/grub/i386-pc/testload.mod" \
"usr/lib/grub/i386-pc/gcry_rijndael.mod" "%{_libdir}/grub/i386-pc/gcry_rijndael.mod" \
"usr/lib/grub/i386-pc/spkmodem.mod" "%{_libdir}/grub/i386-pc/spkmodem.mod" \
"usr/lib/grub/i386-pc/gcry_camellia.module" "%{_libdir}/grub/i386-pc/gcry_camellia.module" \
"usr/lib/grub/i386-pc/gfxterm.mod" "%{_libdir}/grub/i386-pc/gfxterm.mod" \
"usr/lib/grub/i386-pc/adler32.mod" "%{_libdir}/grub/i386-pc/adler32.mod" \
"usr/lib/grub/i386-pc/fat.mod" "%{_libdir}/grub/i386-pc/fat.mod" \
"usr/lib/grub/i386-pc/biosdisk.mod" "%{_libdir}/grub/i386-pc/biosdisk.mod" \
"usr/lib/grub/i386-pc/div_test.module" "%{_libdir}/grub/i386-pc/div_test.module" \
"usr/lib/grub/i386-pc/cmostest.module" "%{_libdir}/grub/i386-pc/cmostest.module" \
"usr/lib/grub/i386-pc/usbserial_usbdebug.module" "%{_libdir}/grub/i386-pc/usbserial_usbdebug.module" \
"usr/lib/grub/i386-pc/cmp.module" "%{_libdir}/grub/i386-pc/cmp.module" \
"usr/lib/grub/i386-pc/iorw.mod" "%{_libdir}/grub/i386-pc/iorw.mod" \
"usr/lib/grub/i386-pc/trig.mod" "%{_libdir}/grub/i386-pc/trig.mod" \
"usr/lib/grub/i386-pc/video.lst" "%{_libdir}/grub/i386-pc/video.lst" \
"usr/lib/grub/i386-pc/signature_test.mod" "%{_libdir}/grub/i386-pc/signature_test.mod" \
"usr/lib/grub/i386-pc/bfs.module" "%{_libdir}/grub/i386-pc/bfs.module" \
"usr/lib/grub/i386-pc/diskfilter.module" "%{_libdir}/grub/i386-pc/diskfilter.module" \
"usr/lib/grub/i386-pc/luks2.module" "%{_libdir}/grub/i386-pc/luks2.module" \
"usr/lib/grub/i386-pc/zfscrypt.mod" "%{_libdir}/grub/i386-pc/zfscrypt.mod" \
"usr/lib/grub/i386-pc/nativedisk.mod" "%{_libdir}/grub/i386-pc/nativedisk.mod" \
"usr/lib/grub/i386-pc/gcry_serpent.module" "%{_libdir}/grub/i386-pc/gcry_serpent.module" \
"usr/lib/grub/i386-pc/minix2.module" "%{_libdir}/grub/i386-pc/minix2.module" \
"usr/lib/grub/i386-pc/modinfo.sh" "%{_libdir}/grub/i386-pc/modinfo.sh" \
"usr/lib/grub/i386-pc/wrmsr.module" "%{_libdir}/grub/i386-pc/wrmsr.module" \
"usr/lib/grub/i386-pc/bufio.mod" "%{_libdir}/grub/i386-pc/bufio.mod" \
"usr/lib/grub/i386-pc/gcry_twofish.module" "%{_libdir}/grub/i386-pc/gcry_twofish.module" \
"usr/lib/grub/i386-pc/mdraid1x.mod" "%{_libdir}/grub/i386-pc/mdraid1x.mod" \
"usr/lib/grub/i386-pc/configfile.module" "%{_libdir}/grub/i386-pc/configfile.module" \
"usr/lib/grub/i386-pc/disk.module" "%{_libdir}/grub/i386-pc/disk.module" \
"usr/lib/grub/i386-pc/cmp.mod" "%{_libdir}/grub/i386-pc/cmp.mod" \
"usr/lib/grub/i386-pc/linux.module" "%{_libdir}/grub/i386-pc/linux.module" \
"usr/lib/grub/i386-pc/part_bsd.module" "%{_libdir}/grub/i386-pc/part_bsd.module" \
"usr/lib/grub/i386-pc/parttool.module" "%{_libdir}/grub/i386-pc/parttool.module" \
"usr/lib/grub/i386-pc/test_blockarg.mod" "%{_libdir}/grub/i386-pc/test_blockarg.mod" \
"usr/lib/grub/i386-pc/search.module" "%{_libdir}/grub/i386-pc/search.module" \
"usr/lib/grub/i386-pc/video_bochs.mod" "%{_libdir}/grub/i386-pc/video_bochs.mod" \
"usr/lib/grub/i386-pc/date.module" "%{_libdir}/grub/i386-pc/date.module" \
"usr/lib/grub/i386-pc/dm_nv.mod" "%{_libdir}/grub/i386-pc/dm_nv.mod" \
"usr/lib/grub/i386-pc/strtoull_test.module" "%{_libdir}/grub/i386-pc/strtoull_test.module" \
"usr/lib/grub/i386-pc/pata.mod" "%{_libdir}/grub/i386-pc/pata.mod" \
"usr/lib/grub/i386-pc/ufs1_be.module" "%{_libdir}/grub/i386-pc/ufs1_be.module" \
"usr/lib/grub/i386-pc/keystatus.mod" "%{_libdir}/grub/i386-pc/keystatus.mod" \
"usr/lib/grub/i386-pc/minix3.module" "%{_libdir}/grub/i386-pc/minix3.module" \
"usr/lib/grub/i386-pc/ntfscomp.module" "%{_libdir}/grub/i386-pc/ntfscomp.module" \
"usr/lib/grub/i386-pc/drivemap.mod" "%{_libdir}/grub/i386-pc/drivemap.mod" \
"usr/lib/grub/i386-pc/pbkdf2_test.module" "%{_libdir}/grub/i386-pc/pbkdf2_test.module" \
"usr/lib/grub/i386-pc/jfs.module" "%{_libdir}/grub/i386-pc/jfs.module" \
"usr/lib/grub/i386-pc/xnu.module" "%{_libdir}/grub/i386-pc/xnu.module" \
"usr/lib/grub/i386-pc/usbserial_pl2303.module" "%{_libdir}/grub/i386-pc/usbserial_pl2303.module" \
"usr/lib/grub/i386-pc/reiserfs.module" "%{_libdir}/grub/i386-pc/reiserfs.module" \
"usr/lib/grub/i386-pc/sfs.mod" "%{_libdir}/grub/i386-pc/sfs.mod" \
"usr/lib/grub/i386-pc/kernel.img" "%{_libdir}/grub/i386-pc/kernel.img" \
"usr/lib/grub/i386-pc/gcry_seed.mod" "%{_libdir}/grub/i386-pc/gcry_seed.mod" \
"usr/lib/grub/i386-pc/freedos.module" "%{_libdir}/grub/i386-pc/freedos.module" \
"usr/lib/grub/i386-pc/gcry_crc.module" "%{_libdir}/grub/i386-pc/gcry_crc.module" \
"usr/lib/grub/i386-pc/video.mod" "%{_libdir}/grub/i386-pc/video.mod" \
"usr/lib/grub/i386-pc/pxeboot.image" "%{_libdir}/grub/i386-pc/pxeboot.image" \
"usr/lib/grub/i386-pc/setjmp.module" "%{_libdir}/grub/i386-pc/setjmp.module" \
"usr/lib/grub/i386-pc/all_video.mod" "%{_libdir}/grub/i386-pc/all_video.mod" \
"usr/lib/grub/i386-pc/sendkey.module" "%{_libdir}/grub/i386-pc/sendkey.module" \
"usr/lib/grub/i386-pc/moddep.lst" "%{_libdir}/grub/i386-pc/moddep.lst" \
"usr/lib/grub/i386-pc/terminal.module" "%{_libdir}/grub/i386-pc/terminal.module" \
"usr/lib/grub/i386-pc/terminal.mod" "%{_libdir}/grub/i386-pc/terminal.mod" \
"usr/lib/grub/i386-pc/gptsync.mod" "%{_libdir}/grub/i386-pc/gptsync.mod" \
"usr/lib/grub/i386-pc/test_blockarg.module" "%{_libdir}/grub/i386-pc/test_blockarg.module" \
"usr/lib/grub/i386-pc/file.module" "%{_libdir}/grub/i386-pc/file.module" \
"usr/lib/grub/i386-pc/smbios.mod" "%{_libdir}/grub/i386-pc/smbios.mod" \
"usr/lib/grub/i386-pc/lzopio.module" "%{_libdir}/grub/i386-pc/lzopio.module" \
"usr/lib/grub/i386-pc/minicmd.mod" "%{_libdir}/grub/i386-pc/minicmd.mod" \
"usr/lib/grub/i386-pc/help.mod" "%{_libdir}/grub/i386-pc/help.mod" \
"usr/lib/grub/i386-pc/plainmount.module" "%{_libdir}/grub/i386-pc/plainmount.module" \
"usr/lib/grub/i386-pc/probe.module" "%{_libdir}/grub/i386-pc/probe.module" \
"usr/lib/grub/i386-pc/efiemu32.o" "%{_libdir}/grub/i386-pc/efiemu32.o" \
"usr/lib/grub/i386-pc/tr.module" "%{_libdir}/grub/i386-pc/tr.module" \
"usr/lib/grub/i386-pc/chain.mod" "%{_libdir}/grub/i386-pc/chain.mod" \
"usr/lib/grub/i386-pc/videotest.module" "%{_libdir}/grub/i386-pc/videotest.module" \
"usr/lib/grub/i386-pc/gcry_idea.module" "%{_libdir}/grub/i386-pc/gcry_idea.module" \
"usr/lib/grub/i386-pc/fshelp.mod" "%{_libdir}/grub/i386-pc/fshelp.mod" \
"usr/lib/grub/i386-pc/cpio_be.module" "%{_libdir}/grub/i386-pc/cpio_be.module" \
"usr/lib/grub/i386-pc/linux.mod" "%{_libdir}/grub/i386-pc/linux.mod" \
"usr/lib/grub/i386-pc/normal.mod" "%{_libdir}/grub/i386-pc/normal.mod" \
"usr/lib/grub/i386-pc/bitmap_scale.module" "%{_libdir}/grub/i386-pc/bitmap_scale.module" \
"usr/lib/grub/i386-pc/part_plan.module" "%{_libdir}/grub/i386-pc/part_plan.module" \
"usr/lib/grub/i386-pc/gcry_whirlpool.mod" "%{_libdir}/grub/i386-pc/gcry_whirlpool.mod" \
"usr/lib/grub/i386-pc/fs.lst" "%{_libdir}/grub/i386-pc/fs.lst" \
"usr/lib/grub/i386-pc/diskboot.img" "%{_libdir}/grub/i386-pc/diskboot.img" \
"usr/lib/grub/i386-pc/gcry_rmd160.module" "%{_libdir}/grub/i386-pc/gcry_rmd160.module" \
"usr/lib/grub/i386-pc/crc64.module" "%{_libdir}/grub/i386-pc/crc64.module" \
"usr/lib/grub/i386-pc/lnxboot.image" "%{_libdir}/grub/i386-pc/lnxboot.image" \
"usr/lib/grub/i386-pc/romfs.mod" "%{_libdir}/grub/i386-pc/romfs.mod" \
"usr/lib/grub/i386-pc/tar.mod" "%{_libdir}/grub/i386-pc/tar.mod" \
"usr/lib/grub/i386-pc/uhci.module" "%{_libdir}/grub/i386-pc/uhci.module" \
"usr/lib/grub/i386-pc/mmap.mod" "%{_libdir}/grub/i386-pc/mmap.mod" \
"usr/lib/grub/i386-pc/search_label.mod" "%{_libdir}/grub/i386-pc/search_label.mod" \
"usr/lib/grub/i386-pc/time.mod" "%{_libdir}/grub/i386-pc/time.mod" \
"usr/lib/grub/i386-pc/usb_keyboard.mod" "%{_libdir}/grub/i386-pc/usb_keyboard.mod" \
"usr/lib/grub/i386-pc/part_amiga.module" "%{_libdir}/grub/i386-pc/part_amiga.module" \
"usr/lib/grub/i386-pc/minicmd.module" "%{_libdir}/grub/i386-pc/minicmd.module" \
"usr/lib/grub/i386-pc/gcry_arcfour.mod" "%{_libdir}/grub/i386-pc/gcry_arcfour.mod" \
"usr/lib/grub/i386-pc/zfscrypt.module" "%{_libdir}/grub/i386-pc/zfscrypt.module" \
"usr/lib/grub/i386-pc/xnu_uuid.mod" "%{_libdir}/grub/i386-pc/xnu_uuid.mod" \
"usr/lib/grub/i386-pc/read.module" "%{_libdir}/grub/i386-pc/read.module" \
"usr/lib/grub/i386-pc/afs.mod" "%{_libdir}/grub/i386-pc/afs.mod" \
"usr/lib/grub/i386-pc/cmosdump.module" "%{_libdir}/grub/i386-pc/cmosdump.module" \
"usr/lib/grub/i386-pc/png.module" "%{_libdir}/grub/i386-pc/png.module" \
"usr/lib/grub/i386-pc/pata.module" "%{_libdir}/grub/i386-pc/pata.module" \
"usr/lib/grub/i386-pc/drivemap.module" "%{_libdir}/grub/i386-pc/drivemap.module" \
"usr/lib/grub/i386-pc/json.mod" "%{_libdir}/grub/i386-pc/json.mod" \
"usr/lib/grub/i386-pc/gcry_rsa.module" "%{_libdir}/grub/i386-pc/gcry_rsa.module" \
"usr/lib/grub/i386-pc/afsplitter.mod" "%{_libdir}/grub/i386-pc/afsplitter.mod" \
"usr/lib/grub/i386-pc/boot_hybrid.img" "%{_libdir}/grub/i386-pc/boot_hybrid.img" \
"usr/lib/grub/i386-pc/test.mod" "%{_libdir}/grub/i386-pc/test.mod" \
"usr/lib/grub/i386-pc/datehook.module" "%{_libdir}/grub/i386-pc/datehook.module" \
"usr/lib/grub/i386-pc/syslinuxcfg.mod" "%{_libdir}/grub/i386-pc/syslinuxcfg.mod" \
"usr/lib/grub/i386-pc/trig.module" "%{_libdir}/grub/i386-pc/trig.module" \
"usr/lib/grub/i386-pc/priority_queue.module" "%{_libdir}/grub/i386-pc/priority_queue.module" \
"usr/lib/grub/i386-pc/iorw.module" "%{_libdir}/grub/i386-pc/iorw.module" \
"usr/lib/grub/i386-pc/ohci.module" "%{_libdir}/grub/i386-pc/ohci.module" \
"usr/lib/grub/i386-pc/pci.mod" "%{_libdir}/grub/i386-pc/pci.mod" \
"usr/lib/grub/i386-pc/part_apple.mod" "%{_libdir}/grub/i386-pc/part_apple.mod" \
"usr/lib/grub/i386-pc/serial.mod" "%{_libdir}/grub/i386-pc/serial.mod" \
"usr/lib/grub/i386-pc/loopback.mod" "%{_libdir}/grub/i386-pc/loopback.mod" \
"usr/lib/grub/i386-pc/msdospart.module" "%{_libdir}/grub/i386-pc/msdospart.module" \
"usr/lib/grub/i386-pc/ls.module" "%{_libdir}/grub/i386-pc/ls.module" \
"usr/lib/grub/i386-pc/datetime.module" "%{_libdir}/grub/i386-pc/datetime.module" \
"usr/lib/grub/i386-pc/part_acorn.module" "%{_libdir}/grub/i386-pc/part_acorn.module" \
"usr/lib/grub/i386-pc/part_sunpc.module" "%{_libdir}/grub/i386-pc/part_sunpc.module" \
"usr/lib/grub/i386-pc/sleep.mod" "%{_libdir}/grub/i386-pc/sleep.mod" \
"usr/lib/grub/i386-pc/extcmd.module" "%{_libdir}/grub/i386-pc/extcmd.module" \
"usr/lib/grub/i386-pc/zfsinfo.module" "%{_libdir}/grub/i386-pc/zfsinfo.module" \
"usr/lib/grub/i386-pc/mdraid1x.module" "%{_libdir}/grub/i386-pc/mdraid1x.module" \
"usr/lib/grub/i386-pc/nilfs2.module" "%{_libdir}/grub/i386-pc/nilfs2.module" \
"usr/lib/grub/i386-pc/relocator.mod" "%{_libdir}/grub/i386-pc/relocator.mod" \
"usr/lib/grub/i386-pc/gdb.mod" "%{_libdir}/grub/i386-pc/gdb.mod" \
"usr/lib/grub/i386-pc/odc.module" "%{_libdir}/grub/i386-pc/odc.module" \
"usr/lib/grub/i386-pc/part_acorn.mod" "%{_libdir}/grub/i386-pc/part_acorn.mod" \
"usr/lib/grub/i386-pc/boot.module" "%{_libdir}/grub/i386-pc/boot.module" \
"usr/lib/grub/i386-pc/gettext.mod" "%{_libdir}/grub/i386-pc/gettext.mod" \
"usr/lib/grub/i386-pc/memdisk.mod" "%{_libdir}/grub/i386-pc/memdisk.mod" \
"usr/lib/grub/i386-pc/halt.module" "%{_libdir}/grub/i386-pc/halt.module" \
"usr/lib/grub/i386-pc/halt.mod" "%{_libdir}/grub/i386-pc/halt.mod" \
"usr/lib/grub/i386-pc/eval.module" "%{_libdir}/grub/i386-pc/eval.module" \
"usr/lib/grub/i386-pc/diskboot.image" "%{_libdir}/grub/i386-pc/diskboot.image" \
"usr/lib/grub/i386-pc/part_gpt.module" "%{_libdir}/grub/i386-pc/part_gpt.module" \
"usr/lib/grub/i386-pc/true.mod" "%{_libdir}/grub/i386-pc/true.mod" \
"usr/lib/grub/i386-pc/minix3.mod" "%{_libdir}/grub/i386-pc/minix3.mod" \
"usr/lib/grub/i386-pc/macho.mod" "%{_libdir}/grub/i386-pc/macho.mod" \
"usr/lib/grub/i386-pc/pxeboot.img" "%{_libdir}/grub/i386-pc/pxeboot.img" \
"usr/lib/grub/i386-pc/morse.module" "%{_libdir}/grub/i386-pc/morse.module" \
"usr/lib/grub/i386-pc/cmostest.mod" "%{_libdir}/grub/i386-pc/cmostest.mod" \
"usr/lib/grub/i386-pc/xnu.mod" "%{_libdir}/grub/i386-pc/xnu.mod" \
"usr/lib/grub/i386-pc/geli.module" "%{_libdir}/grub/i386-pc/geli.module" \
"usr/lib/grub/i386-pc/usbtest.module" "%{_libdir}/grub/i386-pc/usbtest.module" \
"usr/lib/grub/i386-pc/search_fs_uuid.module" "%{_libdir}/grub/i386-pc/search_fs_uuid.module" \
"usr/lib/grub/i386-pc/exfat.mod" "%{_libdir}/grub/i386-pc/exfat.mod" \
"usr/lib/grub/i386-pc/nativedisk.module" "%{_libdir}/grub/i386-pc/nativedisk.module" \
"usr/lib/grub/i386-pc/mul_test.module" "%{_libdir}/grub/i386-pc/mul_test.module" \
"usr/lib/grub/i386-pc/random.mod" "%{_libdir}/grub/i386-pc/random.mod" \
"usr/lib/grub/i386-pc/normal.module" "%{_libdir}/grub/i386-pc/normal.module" \
"usr/lib/grub/i386-pc/cpio_be.mod" "%{_libdir}/grub/i386-pc/cpio_be.mod" \
"usr/lib/grub/i386-pc/cdboot.img" "%{_libdir}/grub/i386-pc/cdboot.img" \
"usr/lib/grub/i386-pc/test.module" "%{_libdir}/grub/i386-pc/test.module" \
"usr/lib/grub/i386-pc/video_bochs.module" "%{_libdir}/grub/i386-pc/video_bochs.module" \
"usr/lib/grub/i386-pc/div.mod" "%{_libdir}/grub/i386-pc/div.mod" \
"usr/lib/grub/i386-pc/macbless.module" "%{_libdir}/grub/i386-pc/macbless.module" \
"usr/lib/grub/i386-pc/syslinuxcfg.module" "%{_libdir}/grub/i386-pc/syslinuxcfg.module" \
"usr/lib/grub/i386-pc/bitmap.mod" "%{_libdir}/grub/i386-pc/bitmap.mod" \
"usr/lib/grub/i386-pc/hdparm.mod" "%{_libdir}/grub/i386-pc/hdparm.mod" \
"usr/lib/grub/i386-pc/hfspluscomp.module" "%{_libdir}/grub/i386-pc/hfspluscomp.module" \
"usr/lib/grub/i386-pc/blocklist.mod" "%{_libdir}/grub/i386-pc/blocklist.mod" \
"usr/lib/grub/i386-pc/exfctest.module" "%{_libdir}/grub/i386-pc/exfctest.module" \
"usr/lib/grub/i386-pc/ufs1_be.mod" "%{_libdir}/grub/i386-pc/ufs1_be.mod" \
"usr/lib/grub/i386-pc/kernel.exec" "%{_libdir}/grub/i386-pc/kernel.exec" \
"usr/lib/grub/i386-pc/terminfo.module" "%{_libdir}/grub/i386-pc/terminfo.module" \
"usr/lib/grub/i386-pc/cbmemc.module" "%{_libdir}/grub/i386-pc/cbmemc.module" \
"usr/lib/grub/i386-pc/minix.mod" "%{_libdir}/grub/i386-pc/minix.mod" \
"usr/lib/grub/i386-pc/gcry_dsa.module" "%{_libdir}/grub/i386-pc/gcry_dsa.module" \
"usr/lib/grub/i386-pc/usb.module" "%{_libdir}/grub/i386-pc/usb.module" \
"usr/lib/grub/i386-pc/gcry_dsa.mod" "%{_libdir}/grub/i386-pc/gcry_dsa.mod" \
"usr/lib/grub/i386-pc/gcry_md5.mod" "%{_libdir}/grub/i386-pc/gcry_md5.mod" \
"usr/lib/grub/i386-pc/gfxterm_menu.module" "%{_libdir}/grub/i386-pc/gfxterm_menu.module" \
"usr/lib/grub/i386-pc/usbms.module" "%{_libdir}/grub/i386-pc/usbms.module" \
"usr/lib/grub/i386-pc/lsapm.module" "%{_libdir}/grub/i386-pc/lsapm.module" \
"usr/lib/grub/i386-pc/crc64.mod" "%{_libdir}/grub/i386-pc/crc64.mod" \
"usr/lib/grub/i386-pc/pbkdf2.module" "%{_libdir}/grub/i386-pc/pbkdf2.module" \
"usr/lib/grub/i386-pc/gfxterm.module" "%{_libdir}/grub/i386-pc/gfxterm.module" \
"usr/lib/grub/i386-pc/at_keyboard.mod" "%{_libdir}/grub/i386-pc/at_keyboard.mod" \
"usr/lib/grub/i386-pc/lzma_decompress.image" "%{_libdir}/grub/i386-pc/lzma_decompress.image" \
"usr/lib/grub/i386-pc/functional_test.module" "%{_libdir}/grub/i386-pc/functional_test.module" \
"usr/lib/grub/i386-pc/cs5536.module" "%{_libdir}/grub/i386-pc/cs5536.module" \
"usr/lib/grub/i386-pc/cmosdump.mod" "%{_libdir}/grub/i386-pc/cmosdump.mod" \
"usr/lib/grub/i386-pc/search_fs_file.mod" "%{_libdir}/grub/i386-pc/search_fs_file.mod" \
"usr/lib/grub/i386-pc/cs5536.mod" "%{_libdir}/grub/i386-pc/cs5536.mod" \
"usr/lib/grub/i386-pc/serial.module" "%{_libdir}/grub/i386-pc/serial.module" \
"usr/lib/grub/i386-pc/minix2_be.mod" "%{_libdir}/grub/i386-pc/minix2_be.mod" \
"usr/lib/grub/i386-pc/testload.module" "%{_libdir}/grub/i386-pc/testload.module" \
"usr/lib/grub/i386-pc/read.mod" "%{_libdir}/grub/i386-pc/read.mod" \
"usr/lib/grub/i386-pc/http.module" "%{_libdir}/grub/i386-pc/http.module" \
"usr/lib/grub/i386-pc/pgp.mod" "%{_libdir}/grub/i386-pc/pgp.mod" \
"usr/lib/grub/i386-pc/elf.module" "%{_libdir}/grub/i386-pc/elf.module" \
"usr/lib/grub/i386-pc/cbmemc.mod" "%{_libdir}/grub/i386-pc/cbmemc.mod" \
"usr/lib/grub/i386-pc/ehci.mod" "%{_libdir}/grub/i386-pc/ehci.mod" \
"usr/lib/grub/i386-pc/chain.module" "%{_libdir}/grub/i386-pc/chain.module" \
"usr/lib/grub/i386-pc/luks2.mod" "%{_libdir}/grub/i386-pc/luks2.mod" \
"usr/lib/grub/i386-pc/cbtable.mod" "%{_libdir}/grub/i386-pc/cbtable.mod" \
"usr/lib/grub/i386-pc/xzio.module" "%{_libdir}/grub/i386-pc/xzio.module" \
"usr/lib/grub/i386-pc/play.module" "%{_libdir}/grub/i386-pc/play.module" \
"usr/lib/grub/i386-pc/ufs1.mod" "%{_libdir}/grub/i386-pc/ufs1.mod" \
"usr/lib/grub/i386-pc/password.module" "%{_libdir}/grub/i386-pc/password.module" \
"usr/lib/grub/i386-pc/setpci.mod" "%{_libdir}/grub/i386-pc/setpci.mod" \
"usr/lib/grub/i386-pc/mda_text.mod" "%{_libdir}/grub/i386-pc/mda_text.mod" \
"usr/lib/grub/i386-pc/exfat.module" "%{_libdir}/grub/i386-pc/exfat.module" \
"usr/lib/grub/i386-pc/bswap_test.module" "%{_libdir}/grub/i386-pc/bswap_test.module" \
"usr/lib/grub/i386-pc/cpuid.module" "%{_libdir}/grub/i386-pc/cpuid.module" \
"usr/lib/grub/i386-pc/luks.module" "%{_libdir}/grub/i386-pc/luks.module" \
"usr/lib/grub/i386-pc/msdospart.mod" "%{_libdir}/grub/i386-pc/msdospart.mod" \
"usr/lib/grub/i386-pc/cmdline_cat_test.module" "%{_libdir}/grub/i386-pc/cmdline_cat_test.module" \
"usr/lib/grub/i386-pc/gdb_grub" "%{_libdir}/grub/i386-pc/gdb_grub" \
"usr/lib/grub/i386-pc/tga.mod" "%{_libdir}/grub/i386-pc/tga.mod" \
"usr/lib/grub/i386-pc/lsmmap.mod" "%{_libdir}/grub/i386-pc/lsmmap.mod" \
"usr/lib/grub/i386-pc/hfs.module" "%{_libdir}/grub/i386-pc/hfs.module" \
"usr/lib/grub/i386-pc/help.module" "%{_libdir}/grub/i386-pc/help.module" \
"usr/lib/grub/i386-pc/tftp.module" "%{_libdir}/grub/i386-pc/tftp.module" \
"usr/lib/grub/i386-pc/search_label.module" "%{_libdir}/grub/i386-pc/search_label.module" \
"usr/lib/grub/i386-pc/truecrypt.mod" "%{_libdir}/grub/i386-pc/truecrypt.mod" \
"usr/lib/grub/i386-pc/plan9.module" "%{_libdir}/grub/i386-pc/plan9.module" \
"usr/lib/grub/i386-pc/font.module" "%{_libdir}/grub/i386-pc/font.module" \
"usr/lib/grub/i386-pc/ntfs.module" "%{_libdir}/grub/i386-pc/ntfs.module" \
"usr/lib/grub/i386-pc/gcry_des.module" "%{_libdir}/grub/i386-pc/gcry_des.module" \
"usr/lib/grub/i386-pc/file.mod" "%{_libdir}/grub/i386-pc/file.mod" \
"usr/lib/grub/i386-pc/procfs.mod" "%{_libdir}/grub/i386-pc/procfs.mod" \
"usr/lib/grub/i386-pc/lsacpi.mod" "%{_libdir}/grub/i386-pc/lsacpi.mod" \
"usr/lib/grub/i386-pc/ufs2.module" "%{_libdir}/grub/i386-pc/ufs2.module" \
"usr/lib/grub/i386-pc/hexdump.mod" "%{_libdir}/grub/i386-pc/hexdump.mod" \
"usr/lib/grub/i386-pc/crypto.mod" "%{_libdir}/grub/i386-pc/crypto.mod" \
"usr/lib/grub/i386-pc/plainmount.mod" "%{_libdir}/grub/i386-pc/plainmount.mod" \
"usr/lib/grub/i386-pc/fat.module" "%{_libdir}/grub/i386-pc/fat.module" \
"usr/lib/grub/i386-pc/gfxterm_menu.mod" "%{_libdir}/grub/i386-pc/gfxterm_menu.mod" \
"usr/lib/grub/i386-pc/ntldr.module" "%{_libdir}/grub/i386-pc/ntldr.module" \
"usr/lib/grub/i386-pc/part_dvh.mod" "%{_libdir}/grub/i386-pc/part_dvh.mod" \
"usr/lib/grub/i386-pc/hello.module" "%{_libdir}/grub/i386-pc/hello.module" \
"usr/lib/grub/i386-pc/relocator.module" "%{_libdir}/grub/i386-pc/relocator.module" \
"usr/lib/grub/i386-pc/gcry_rfc2268.module" "%{_libdir}/grub/i386-pc/gcry_rfc2268.module" \
"usr/lib/grub/i386-pc/ldm.module" "%{_libdir}/grub/i386-pc/ldm.module" \
"usr/lib/grub/i386-pc/tftp.mod" "%{_libdir}/grub/i386-pc/tftp.mod" \
"usr/lib/grub/i386-pc/raid6rec.mod" "%{_libdir}/grub/i386-pc/raid6rec.mod" \
"usr/lib/grub/i386-pc/zfs.mod" "%{_libdir}/grub/i386-pc/zfs.mod" \
"usr/lib/grub/i386-pc/at_keyboard.module" "%{_libdir}/grub/i386-pc/at_keyboard.module" \
"usr/lib/grub/i386-pc/usbserial_common.module" "%{_libdir}/grub/i386-pc/usbserial_common.module" \
"usr/lib/grub/i386-pc/efiemu.module" "%{_libdir}/grub/i386-pc/efiemu.module" \
"usr/lib/grub/i386-pc/rdmsr.module" "%{_libdir}/grub/i386-pc/rdmsr.module" \
"usr/lib/grub/i386-pc/lspci.module" "%{_libdir}/grub/i386-pc/lspci.module" \
"usr/lib/grub/i386-pc/multiboot.mod" "%{_libdir}/grub/i386-pc/multiboot.mod" \
"usr/lib/grub/i386-pc/boot.image" "%{_libdir}/grub/i386-pc/boot.image" \
"usr/lib/grub/i386-pc/boot.mod" "%{_libdir}/grub/i386-pc/boot.mod" \
"usr/lib/grub/i386-pc/vga_text.mod" "%{_libdir}/grub/i386-pc/vga_text.mod" \
"usr/lib/grub/i386-pc/datetime.mod" "%{_libdir}/grub/i386-pc/datetime.mod" \
"usr/lib/grub/i386-pc/gcry_crc.mod" "%{_libdir}/grub/i386-pc/gcry_crc.mod" \
"usr/lib/grub/i386-pc/afs.module" "%{_libdir}/grub/i386-pc/afs.module" \
"usr/lib/grub/i386-pc/setjmp_test.module" "%{_libdir}/grub/i386-pc/setjmp_test.module" \
"usr/lib/grub/i386-pc/ctz_test.mod" "%{_libdir}/grub/i386-pc/ctz_test.mod" \
"usr/lib/grub/i386-pc/multiboot2.mod" "%{_libdir}/grub/i386-pc/multiboot2.mod" \
"usr/lib/grub/i386-pc/mdraid09.module" "%{_libdir}/grub/i386-pc/mdraid09.module" \
"usr/lib/grub/i386-pc/hashsum.mod" "%{_libdir}/grub/i386-pc/hashsum.mod" \
"usr/lib/grub/i386-pc/ohci.mod" "%{_libdir}/grub/i386-pc/ohci.mod" \
"usr/lib/grub/i386-pc/acpi.mod" "%{_libdir}/grub/i386-pc/acpi.mod" \
"usr/lib/grub/i386-pc/part_dfly.module" "%{_libdir}/grub/i386-pc/part_dfly.module" \
"usr/lib/grub/i386-pc/fdt.lst" "%{_libdir}/grub/i386-pc/fdt.lst" \
"usr/lib/grub/i386-pc/loadenv.module" "%{_libdir}/grub/i386-pc/loadenv.module" \
"usr/lib/grub/i386-pc/lsapm.mod" "%{_libdir}/grub/i386-pc/lsapm.mod" \
"usr/lib/grub/i386-pc/boot.img" "%{_libdir}/grub/i386-pc/boot.img" \
"usr/lib/grub/i386-pc/hfs.mod" "%{_libdir}/grub/i386-pc/hfs.mod" \
"usr/lib/grub/i386-pc/ufs2.mod" "%{_libdir}/grub/i386-pc/ufs2.mod" \
"usr/lib/grub/i386-pc/macbless.mod" "%{_libdir}/grub/i386-pc/macbless.mod" \
"usr/lib/grub/i386-pc/cat.mod" "%{_libdir}/grub/i386-pc/cat.mod" \
"usr/lib/grub/i386-pc/squash4.module" "%{_libdir}/grub/i386-pc/squash4.module" \
"usr/lib/grub/i386-pc/ahci.module" "%{_libdir}/grub/i386-pc/ahci.module" \
"usr/lib/grub/i386-pc/lsacpi.module" "%{_libdir}/grub/i386-pc/lsacpi.module" \
"usr/lib/grub/i386-pc/minix2_be.module" "%{_libdir}/grub/i386-pc/minix2_be.module" \
"usr/lib/grub/i386-pc/ata.module" "%{_libdir}/grub/i386-pc/ata.module" \
"usr/lib/grub/i386-pc/aout.mod" "%{_libdir}/grub/i386-pc/aout.mod" \
"usr/lib/grub/i386-pc/lzma_decompress.img" "%{_libdir}/grub/i386-pc/lzma_decompress.img" \
"usr/lib/grub/i386-pc/hello.mod" "%{_libdir}/grub/i386-pc/hello.mod" \
"usr/lib/grub/i386-pc/multiboot.module" "%{_libdir}/grub/i386-pc/multiboot.module" \
"usr/lib/grub/i386-pc/gcry_blowfish.module" "%{_libdir}/grub/i386-pc/gcry_blowfish.module" \
"usr/lib/grub/i386-pc/udf.module" "%{_libdir}/grub/i386-pc/udf.module" \
"usr/lib/grub/i386-pc/gcry_cast5.module" "%{_libdir}/grub/i386-pc/gcry_cast5.module" \
"usr/lib/grub/i386-pc/password.mod" "%{_libdir}/grub/i386-pc/password.mod" \
"usr/lib/grub/i386-pc/efiemu64.o" "%{_libdir}/grub/i386-pc/efiemu64.o" \
"usr/lib/grub/i386-pc/hdparm.module" "%{_libdir}/grub/i386-pc/hdparm.module" \
"usr/lib/grub/i386-pc/gcry_sha256.module" "%{_libdir}/grub/i386-pc/gcry_sha256.module" \
"usr/lib/grub/i386-pc/gcry_idea.mod" "%{_libdir}/grub/i386-pc/gcry_idea.mod" \
"usr/lib/grub/i386-pc/hexdump.module" "%{_libdir}/grub/i386-pc/hexdump.module" \
"usr/sbin/grub-probe" "%{_sbindir}/grub-probe" \
"usr/sbin/grub-mkconfig" "%{_sbindir}/grub-mkconfig" \
"usr/sbin/grub-bios-setup" "%{_sbindir}/grub-bios-setup" \
"usr/sbin/grub-set-default" "%{_sbindir}/grub-set-default" \
"usr/sbin/grub-sparc64-setup" "%{_sbindir}/grub-sparc64-setup" \
"usr/sbin/grub-ofpathname" "%{_sbindir}/grub-ofpathname" \
"usr/sbin/grub-macbless" "%{_sbindir}/grub-macbless" \
"usr/sbin/grub-install" "%{_sbindir}/grub-install" \
"usr/sbin/grub-reboot" "%{_sbindir}/grub-reboot" \
"usr/share/locale/de/LC_MESSAGES/grub.mo" "%{_datadir}/locale/de/LC_MESSAGES/grub.mo" \
"usr/share/locale/en@arabic/LC_MESSAGES/grub.mo" "%{_datadir}/locale/en@arabic/LC_MESSAGES/grub.mo" \
"usr/share/locale/ast/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ast/LC_MESSAGES/grub.mo" \
"usr/share/locale/pt_BR/LC_MESSAGES/grub.mo" "%{_datadir}/locale/pt_BR/LC_MESSAGES/grub.mo" \
"usr/share/locale/lg/LC_MESSAGES/grub.mo" "%{_datadir}/locale/lg/LC_MESSAGES/grub.mo" \
"usr/share/locale/tr/LC_MESSAGES/grub.mo" "%{_datadir}/locale/tr/LC_MESSAGES/grub.mo" \
"usr/share/locale/hu/LC_MESSAGES/grub.mo" "%{_datadir}/locale/hu/LC_MESSAGES/grub.mo" \
"usr/share/locale/gl/LC_MESSAGES/grub.mo" "%{_datadir}/locale/gl/LC_MESSAGES/grub.mo" \
"usr/share/locale/da/LC_MESSAGES/grub.mo" "%{_datadir}/locale/da/LC_MESSAGES/grub.mo" \
"usr/share/locale/hr/LC_MESSAGES/grub.mo" "%{_datadir}/locale/hr/LC_MESSAGES/grub.mo" \
"usr/share/locale/he/LC_MESSAGES/grub.mo" "%{_datadir}/locale/he/LC_MESSAGES/grub.mo" \
"usr/share/locale/en@greek/LC_MESSAGES/grub.mo" "%{_datadir}/locale/en@greek/LC_MESSAGES/grub.mo" \
"usr/share/locale/sr/LC_MESSAGES/grub.mo" "%{_datadir}/locale/sr/LC_MESSAGES/grub.mo" \
"usr/share/locale/fi/LC_MESSAGES/grub.mo" "%{_datadir}/locale/fi/LC_MESSAGES/grub.mo" \
"usr/share/locale/de_CH/LC_MESSAGES/grub.mo" "%{_datadir}/locale/de_CH/LC_MESSAGES/grub.mo" \
"usr/share/locale/pa/LC_MESSAGES/grub.mo" "%{_datadir}/locale/pa/LC_MESSAGES/grub.mo" \
"usr/share/locale/ka/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ka/LC_MESSAGES/grub.mo" \
"usr/share/locale/pl/LC_MESSAGES/grub.mo" "%{_datadir}/locale/pl/LC_MESSAGES/grub.mo" \
"usr/share/locale/lt/LC_MESSAGES/grub.mo" "%{_datadir}/locale/lt/LC_MESSAGES/grub.mo" \
"usr/share/locale/ca/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ca/LC_MESSAGES/grub.mo" \
"usr/share/locale/it/LC_MESSAGES/grub.mo" "%{_datadir}/locale/it/LC_MESSAGES/grub.mo" \
"usr/share/locale/nl/LC_MESSAGES/grub.mo" "%{_datadir}/locale/nl/LC_MESSAGES/grub.mo" \
"usr/share/locale/es/LC_MESSAGES/grub.mo" "%{_datadir}/locale/es/LC_MESSAGES/grub.mo" \
"usr/share/locale/eo/LC_MESSAGES/grub.mo" "%{_datadir}/locale/eo/LC_MESSAGES/grub.mo" \
"usr/share/locale/ko/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ko/LC_MESSAGES/grub.mo" \
"usr/share/locale/sl/LC_MESSAGES/grub.mo" "%{_datadir}/locale/sl/LC_MESSAGES/grub.mo" \
"usr/share/locale/fr/LC_MESSAGES/grub.mo" "%{_datadir}/locale/fr/LC_MESSAGES/grub.mo" \
"usr/share/locale/uk/LC_MESSAGES/grub.mo" "%{_datadir}/locale/uk/LC_MESSAGES/grub.mo" \
"usr/share/locale/en@hebrew/LC_MESSAGES/grub.mo" "%{_datadir}/locale/en@hebrew/LC_MESSAGES/grub.mo" \
"usr/share/locale/zh_TW/LC_MESSAGES/grub.mo" "%{_datadir}/locale/zh_TW/LC_MESSAGES/grub.mo" \
"usr/share/locale/vi/LC_MESSAGES/grub.mo" "%{_datadir}/locale/vi/LC_MESSAGES/grub.mo" \
"usr/share/locale/en@piglatin/LC_MESSAGES/grub.mo" "%{_datadir}/locale/en@piglatin/LC_MESSAGES/grub.mo" \
"usr/share/locale/ja/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ja/LC_MESSAGES/grub.mo" \
"usr/share/locale/en@cyrillic/LC_MESSAGES/grub.mo" "%{_datadir}/locale/en@cyrillic/LC_MESSAGES/grub.mo" \
"usr/share/locale/nb/LC_MESSAGES/grub.mo" "%{_datadir}/locale/nb/LC_MESSAGES/grub.mo" \
"usr/share/locale/ru/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ru/LC_MESSAGES/grub.mo" \
"usr/share/locale/sv/LC_MESSAGES/grub.mo" "%{_datadir}/locale/sv/LC_MESSAGES/grub.mo" \
"usr/share/locale/zh_CN/LC_MESSAGES/grub.mo" "%{_datadir}/locale/zh_CN/LC_MESSAGES/grub.mo" \
"usr/share/locale/id/LC_MESSAGES/grub.mo" "%{_datadir}/locale/id/LC_MESSAGES/grub.mo" \
"usr/share/locale/en@quot/LC_MESSAGES/grub.mo" "%{_datadir}/locale/en@quot/LC_MESSAGES/grub.mo" \
"usr/share/locale/de@hebrew/LC_MESSAGES/grub.mo" "%{_datadir}/locale/de@hebrew/LC_MESSAGES/grub.mo" \
"usr/share/locale/ro/LC_MESSAGES/grub.mo" "%{_datadir}/locale/ro/LC_MESSAGES/grub.mo" \
"usr/share/locale/pt/LC_MESSAGES/grub.mo" "%{_datadir}/locale/pt/LC_MESSAGES/grub.mo" \
"usr/share/grub/grub-mkconfig_lib" "%{_datadir}/grub/grub-mkconfig_lib"
